// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=40001 schema_version=1 schema_hash=3233278346470496550

use rkyv::{Archive, Serialize as RkyvSerialize, rancor::Error as RkyvError};

use metamorphic_binary_transport_core::envelope::{
    HEADER_LEN, SchemaHeaderSpec, TransportHeader, decode_header, encode_header, fnv1a64,
    trusted_payload_for_schema, validate_header_for_schema,
};
use metamorphic_binary_transport_core::error::{Result, TransportError};
use metamorphic_binary_transport_core::runtime::{BinaryInspection, MbtSchema};

pub const SCHEMA_ID: u32 = 40001;
pub const SCHEMA_VERSION_VALUE: u16 = 1;
pub const SCHEMA_VERSION: u16 = SCHEMA_VERSION_VALUE;
pub const GENERATED_SCHEMA_HASH: u64 = 3233278346470496550;
pub const TRANSPORT_NAME: &str = "mathilde.test_compatibility.v1";
pub const SCHEMA_HEADER: SchemaHeaderSpec = SchemaHeaderSpec {
    schema_id: SCHEMA_ID,
    schema_version: SCHEMA_VERSION,
    schema_hash: GENERATED_SCHEMA_HASH,
};

pub const TENANT_ALPHA: u16 = 0;
pub const TENANT_BETA: u16 = 1;
pub const TENANT_COUNT: u16 = 2;

pub const ENTITY_ENTITY_A: u16 = 0;
pub const ENTITY_ENTITY_B: u16 = 1;
pub const ENTITY_ENTITY_C: u16 = 2;
pub const ENTITY_COUNT: u16 = 3;

pub const STATUS_NONE: u16 = 0;
pub const STATUS_ACTIVE: u16 = 1;
pub const STATUS_PAUSED: u16 = 2;
pub const STATUS_CLOSED: u16 = 3;

pub const VENUE_BINANCE_BIT: u64 = 0;
pub const VENUE_BYBIT_BIT: u64 = 1;
pub const VENUE_OKX_BIT: u64 = 2;
pub const VALID_VENUE_MASK: u64 =
    (1 << VENUE_BINANCE_BIT) | (1 << VENUE_BYBIT_BIT) | (1 << VENUE_OKX_BIT);

pub const PRESENCE_OPTIONAL_STATUS_ORDINAL: u64 = 1 << 0;
pub const PRESENCE_OPTIONAL_I64: u64 = 1 << 1;
pub const PRESENCE_OPTIONAL_I32: u64 = 1 << 2;
pub const PRESENCE_OPTIONAL_U32: u64 = 1 << 3;
pub const PRESENCE_OPTIONAL_F64: u64 = 1 << 4;
pub const PRESENCE_OPTIONAL_F32: u64 = 1 << 5;
pub const PRESENCE_OPTIONAL_BOOL: u64 = 1 << 6;
pub const PRESENCE_OPTIONAL_TEXT: u64 = 1 << 7;
pub const PRESENCE_OPTIONAL_BYTES: u64 = 1 << 8;
pub const PRESENCE_NULLABLE_I64_ARRAY: u64 = 1 << 9;
pub const PRESENCE_NULLABLE_I32_ARRAY: u64 = 1 << 10;
pub const PRESENCE_NULLABLE_U32_ARRAY: u64 = 1 << 11;
pub const PRESENCE_NULLABLE_F64_ARRAY: u64 = 1 << 12;
pub const PRESENCE_NULLABLE_F32_ARRAY: u64 = 1 << 13;
pub const PRESENCE_ALLOWED_MASK: u64 = (1 << 14) - 1;

#[derive(Clone, Archive, RkyvSerialize)]
pub struct TestCompatibilityResponseV1Payload {
    pub schema_version: u16,
    pub rows: Vec<TestCompatibilityRowV1>,
}

#[derive(Clone, Archive, RkyvSerialize)]
pub struct TestCompatibilityRowV1 {
    pub schema_version: u16,
    pub tenant_ordinal: u16,
    pub entity_ordinal: u16,
    pub close_ms: i64,
    pub status_ordinal: u16,
    pub optional_status_ordinal: u16,
    pub venues_mask: u64,
    pub required_i64: i64,
    pub optional_i64: i64,
    pub required_i32: i32,
    pub optional_i32: i32,
    pub required_u32: u32,
    pub optional_u32: u32,
    pub required_f64: f64,
    pub optional_f64: f64,
    pub required_f32: f32,
    pub optional_f32: f32,
    pub required_bool: bool,
    pub optional_bool: bool,
    pub required_text: String,
    pub optional_text: String,
    pub required_bytes: Vec<u8>,
    pub optional_bytes: Vec<u8>,
    pub uuid_text: String,
    pub jsonb_text: String,
    pub timestamptz_text: String,
    pub numeric_text: String,
    pub required_i64_array: Vec<i64>,
    pub nullable_i64_array: Vec<i64>,
    pub required_i32_array: Vec<i32>,
    pub nullable_i32_array: Vec<i32>,
    pub required_u32_array: Vec<u32>,
    pub nullable_u32_array: Vec<u32>,
    pub required_f64_array: Vec<f64>,
    pub nullable_f64_array: Vec<f64>,
    pub required_f32_array: Vec<f32>,
    pub nullable_f32_array: Vec<f32>,
    pub presence_bits: u64,
}

pub fn validate_rows(rows: &[TestCompatibilityRowV1]) -> Result<()> {
    let mut previous = None;
    for row in rows {
        validate_row(row, previous)?;
        previous = Some(row);
    }
    Ok(())
}

pub fn validate_row(
    row: &TestCompatibilityRowV1,
    previous: Option<&TestCompatibilityRowV1>,
) -> Result<()> {
    if row.schema_version != 1 {
        return Err(TransportError::SchemaVersionMismatch {
            observed: row.schema_version,
            expected: 1,
        });
    }
    tenant_symbol(row.tenant_ordinal)?;
    entity_symbol(row.entity_ordinal)?;
    status_symbol(row.status_ordinal)?;
    if row.optional_status_ordinal != 0 {
        status_symbol(row.optional_status_ordinal)?;
    }
    if row.venues_mask & !VALID_VENUE_MASK != 0 {
        return Err(TransportError::InvalidBitmask {
            field: "venues",
            value: row.venues_mask,
        });
    }
    validate_finite_f64("required_f64", row.required_f64)?;
    validate_finite_f64("optional_f64", row.optional_f64)?;
    validate_finite_f32("required_f32", row.required_f32)?;
    validate_finite_f32("optional_f32", row.optional_f32)?;
    for value in &row.required_f64_array {
        validate_finite_f64("required_f64_array", *value)?;
    }
    for value in &row.nullable_f64_array {
        validate_finite_f64("nullable_f64_array", *value)?;
    }
    for value in &row.required_f32_array {
        validate_finite_f32("required_f32_array", *value)?;
    }
    for value in &row.nullable_f32_array {
        validate_finite_f32("nullable_f32_array", *value)?;
    }
    if row.presence_bits & !PRESENCE_ALLOWED_MASK != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_STATUS_ORDINAL == 0 && row.optional_status_ordinal != 0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_I64 == 0 && row.optional_i64 != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_I32 == 0 && row.optional_i32 != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_U32 == 0 && row.optional_u32 != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_F64 == 0 && row.optional_f64 != 0.0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_F32 == 0 && row.optional_f32 != 0.0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_BOOL == 0 && row.optional_bool {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_TEXT == 0 && !row.optional_text.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_OPTIONAL_BYTES == 0 && !row.optional_bytes.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_NULLABLE_I64_ARRAY == 0 && !row.nullable_i64_array.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_NULLABLE_I32_ARRAY == 0 && !row.nullable_i32_array.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_NULLABLE_U32_ARRAY == 0 && !row.nullable_u32_array.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_NULLABLE_F64_ARRAY == 0 && !row.nullable_f64_array.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_NULLABLE_F32_ARRAY == 0 && !row.nullable_f32_array.is_empty() {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if previous.is_some_and(|prev| {
        (row.tenant_ordinal, row.entity_ordinal, row.close_ms)
            < (prev.tenant_ordinal, prev.entity_ordinal, prev.close_ms)
    }) {
        return Err(TransportError::InvalidTimeGrid(
            "key order regression".to_string(),
        ));
    }
    Ok(())
}

fn validate_finite_f32(field: &'static str, value: f32) -> Result<()> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(TransportError::NonFiniteNumeric(field))
    }
}

fn validate_finite_f64(field: &'static str, value: f64) -> Result<()> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(TransportError::NonFiniteNumeric(field))
    }
}

pub fn semantic_checksum(rows: &[TestCompatibilityRowV1]) -> u64 {
    let mut checksum = fnv1a64("mathilde.test_compatibility.v1".as_bytes());
    for row in rows {
        checksum = checksum_row(checksum, row);
    }
    checksum
}

pub fn minimal_projection_checksum(rows: &[TestCompatibilityRowV1]) -> u64 {
    semantic_checksum(rows)
}

pub fn checksum_row(mut checksum: u64, row: &TestCompatibilityRowV1) -> u64 {
    checksum = update_u16(checksum, row.schema_version);
    checksum = update_u16(checksum, row.tenant_ordinal);
    checksum = update_u16(checksum, row.entity_ordinal);
    checksum = update_i64(checksum, row.close_ms);
    checksum = update_u16(checksum, row.status_ordinal);
    checksum = update_u16(checksum, row.optional_status_ordinal);
    checksum = update_u64(checksum, row.venues_mask);
    checksum = update_i64(checksum, row.required_i64);
    checksum = update_i64(checksum, row.optional_i64);
    checksum = update_i32(checksum, row.required_i32);
    checksum = update_i32(checksum, row.optional_i32);
    checksum = update_u32(checksum, row.required_u32);
    checksum = update_u32(checksum, row.optional_u32);
    checksum = update_f64(checksum, row.required_f64);
    checksum = update_f64(checksum, row.optional_f64);
    checksum = update_f32(checksum, row.required_f32);
    checksum = update_f32(checksum, row.optional_f32);
    checksum = update_bool(checksum, row.required_bool);
    checksum = update_bool(checksum, row.optional_bool);
    checksum = update_bytes(checksum, row.required_text.as_bytes());
    checksum = update_bytes(checksum, row.optional_text.as_bytes());
    checksum = update_bytes(checksum, row.required_bytes.as_slice());
    checksum = update_bytes(checksum, row.optional_bytes.as_slice());
    checksum = update_bytes(checksum, row.uuid_text.as_bytes());
    checksum = update_bytes(checksum, row.jsonb_text.as_bytes());
    checksum = update_bytes(checksum, row.timestamptz_text.as_bytes());
    checksum = update_bytes(checksum, row.numeric_text.as_bytes());
    checksum = update_i64_array(checksum, row.required_i64_array.as_slice());
    checksum = update_i64_array(checksum, row.nullable_i64_array.as_slice());
    checksum = update_i32_array(checksum, row.required_i32_array.as_slice());
    checksum = update_i32_array(checksum, row.nullable_i32_array.as_slice());
    checksum = update_u32_array(checksum, row.required_u32_array.as_slice());
    checksum = update_u32_array(checksum, row.nullable_u32_array.as_slice());
    checksum = update_f64_array(checksum, row.required_f64_array.as_slice());
    checksum = update_f64_array(checksum, row.nullable_f64_array.as_slice());
    checksum = update_f32_array(checksum, row.required_f32_array.as_slice());
    checksum = update_f32_array(checksum, row.nullable_f32_array.as_slice());
    checksum = update_u64(checksum, row.presence_bits);
    checksum
}

pub fn checksum_archived_row(
    mut checksum: u64,
    row: &<TestCompatibilityRowV1 as Archive>::Archived,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.tenant_ordinal.to_native());
    checksum = update_u16(checksum, row.entity_ordinal.to_native());
    checksum = update_i64(checksum, row.close_ms.to_native());
    checksum = update_u16(checksum, row.status_ordinal.to_native());
    checksum = update_u16(checksum, row.optional_status_ordinal.to_native());
    checksum = update_u64(checksum, row.venues_mask.to_native());
    checksum = update_i64(checksum, row.required_i64.to_native());
    checksum = update_i64(checksum, row.optional_i64.to_native());
    checksum = update_i32(checksum, row.required_i32.to_native());
    checksum = update_i32(checksum, row.optional_i32.to_native());
    checksum = update_u32(checksum, row.required_u32.to_native());
    checksum = update_u32(checksum, row.optional_u32.to_native());
    checksum = update_f64(checksum, row.required_f64.to_native());
    checksum = update_f64(checksum, row.optional_f64.to_native());
    checksum = update_f32(checksum, row.required_f32.to_native());
    checksum = update_f32(checksum, row.optional_f32.to_native());
    checksum = update_bool(checksum, row.required_bool);
    checksum = update_bool(checksum, row.optional_bool);
    checksum = update_bytes(checksum, row.required_text.as_bytes());
    checksum = update_bytes(checksum, row.optional_text.as_bytes());
    checksum = update_bytes(checksum, row.required_bytes.as_slice());
    checksum = update_bytes(checksum, row.optional_bytes.as_slice());
    checksum = update_bytes(checksum, row.uuid_text.as_bytes());
    checksum = update_bytes(checksum, row.jsonb_text.as_bytes());
    checksum = update_bytes(checksum, row.timestamptz_text.as_bytes());
    checksum = update_bytes(checksum, row.numeric_text.as_bytes());
    checksum = update_archived_i64_array(checksum, row.required_i64_array.iter());
    checksum = update_archived_i64_array(checksum, row.nullable_i64_array.iter());
    checksum = update_archived_i32_array(checksum, row.required_i32_array.iter());
    checksum = update_archived_i32_array(checksum, row.nullable_i32_array.iter());
    checksum = update_archived_u32_array(checksum, row.required_u32_array.iter());
    checksum = update_archived_u32_array(checksum, row.nullable_u32_array.iter());
    checksum = update_archived_f64_array(checksum, row.required_f64_array.iter());
    checksum = update_archived_f64_array(checksum, row.nullable_f64_array.iter());
    checksum = update_archived_f32_array(checksum, row.required_f32_array.iter());
    checksum = update_archived_f32_array(checksum, row.nullable_f32_array.iter());
    checksum = update_u64(checksum, row.presence_bits.to_native());
    checksum
}

fn update_bytes(mut checksum: u64, bytes: &[u8]) -> u64 {
    checksum = update_u64(checksum, bytes.len() as u64);
    for byte in bytes {
        checksum = fnv1a64_update(checksum, *byte);
    }
    checksum
}

fn fnv1a64_update(mut checksum: u64, byte: u8) -> u64 {
    checksum ^= u64::from(byte);
    checksum.wrapping_mul(0x00000100000001B3)
}

fn update_fixed<const N: usize>(mut checksum: u64, bytes: [u8; N]) -> u64 {
    for byte in checksum.to_le_bytes() {
        checksum = fnv1a64_update(checksum, byte);
    }
    for byte in bytes {
        checksum = fnv1a64_update(checksum, byte);
    }
    checksum
}

fn update_bool(checksum: u64, value: bool) -> u64 {
    update_u64(checksum, u64::from(value))
}

fn update_u16(checksum: u64, value: u16) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_i32(checksum: u64, value: i32) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_u32(checksum: u64, value: u32) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_i64(checksum: u64, value: i64) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_u64(checksum: u64, value: u64) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_f32(checksum: u64, value: f32) -> u64 {
    update_u32(checksum, value.to_bits())
}

fn update_f64(checksum: u64, value: f64) -> u64 {
    update_u64(checksum, value.to_bits())
}

fn update_i64_array(mut checksum: u64, values: &[i64]) -> u64 {
    checksum = update_u64(checksum, values.len() as u64);
    for value in values {
        checksum = update_i64(checksum, *value);
    }
    checksum
}

fn update_i32_array(mut checksum: u64, values: &[i32]) -> u64 {
    checksum = update_u64(checksum, values.len() as u64);
    for value in values {
        checksum = update_i32(checksum, *value);
    }
    checksum
}

fn update_u32_array(mut checksum: u64, values: &[u32]) -> u64 {
    checksum = update_u64(checksum, values.len() as u64);
    for value in values {
        checksum = update_u32(checksum, *value);
    }
    checksum
}

fn update_f64_array(mut checksum: u64, values: &[f64]) -> u64 {
    checksum = update_u64(checksum, values.len() as u64);
    for value in values {
        checksum = update_f64(checksum, *value);
    }
    checksum
}

fn update_f32_array(mut checksum: u64, values: &[f32]) -> u64 {
    checksum = update_u64(checksum, values.len() as u64);
    for value in values {
        checksum = update_f32(checksum, *value);
    }
    checksum
}

fn update_archived_i64_array<'a, I>(mut checksum: u64, values: I) -> u64
where
    I: Iterator<Item = &'a rkyv::rend::i64_le>,
{
    for value in values {
        checksum = update_i64(checksum, value.to_native());
    }
    checksum
}

fn update_archived_i32_array<'a, I>(mut checksum: u64, values: I) -> u64
where
    I: Iterator<Item = &'a rkyv::rend::i32_le>,
{
    for value in values {
        checksum = update_i32(checksum, value.to_native());
    }
    checksum
}

fn update_archived_u32_array<'a, I>(mut checksum: u64, values: I) -> u64
where
    I: Iterator<Item = &'a rkyv::rend::u32_le>,
{
    for value in values {
        checksum = update_u32(checksum, value.to_native());
    }
    checksum
}

fn update_archived_f64_array<'a, I>(mut checksum: u64, values: I) -> u64
where
    I: Iterator<Item = &'a rkyv::rend::f64_le>,
{
    for value in values {
        checksum = update_f64(checksum, value.to_native());
    }
    checksum
}

fn update_archived_f32_array<'a, I>(mut checksum: u64, values: I) -> u64
where
    I: Iterator<Item = &'a rkyv::rend::f32_le>,
{
    for value in values {
        checksum = update_f32(checksum, value.to_native());
    }
    checksum
}

pub fn tenant_symbol(value: u16) -> Result<&'static str> {
    match value {
        0 => Ok("alpha"),
        1 => Ok("beta"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "tenant",
            value: other,
        }),
    }
}

pub fn tenant_ordinal(value: &str) -> Result<u16> {
    match value {
        "alpha" => Ok(0),
        "beta" => Ok(1),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "tenant",
            value: u16::MAX,
        }),
    }
}

pub fn entity_symbol(value: u16) -> Result<&'static str> {
    match value {
        0 => Ok("entity_a"),
        1 => Ok("entity_b"),
        2 => Ok("entity_c"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "entity",
            value: other,
        }),
    }
}

pub fn entity_ordinal(value: &str) -> Result<u16> {
    match value {
        "entity_a" => Ok(0),
        "entity_b" => Ok(1),
        "entity_c" => Ok(2),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "entity",
            value: u16::MAX,
        }),
    }
}

pub fn status_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("active"),
        2 => Ok("paused"),
        3 => Ok("closed"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "status",
            value: other,
        }),
    }
}

pub fn status_ordinal(value: &str) -> Result<u16> {
    match value {
        "active" => Ok(1),
        "paused" => Ok(2),
        "closed" => Ok(3),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "status",
            value: u16::MAX,
        }),
    }
}

pub fn venue_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("binance"),
        2 => Ok("bybit"),
        3 => Ok("okx"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "venue",
            value: other,
        }),
    }
}

pub fn venue_ordinal(value: &str) -> Result<u16> {
    match value {
        "binance" => Ok(1),
        "bybit" => Ok(2),
        "okx" => Ok(3),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "venue",
            value: u16::MAX,
        }),
    }
}

pub struct TestCompatibilityV1;

impl TestCompatibilityV1 {
    pub const SCHEMA_ID: u32 = SCHEMA_ID;
    pub const SCHEMA_VERSION: u16 = SCHEMA_VERSION;
    pub const SCHEMA_HASH: u64 = GENERATED_SCHEMA_HASH;
    pub const TRANSPORT_NAME: &'static str = TRANSPORT_NAME;

    pub fn header_spec() -> SchemaHeaderSpec {
        SCHEMA_HEADER
    }

    pub fn encode(rows: &[TestCompatibilityRowV1], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows.to_vec(), max_response_bytes)
    }

    pub fn encode_owned(
        rows: Vec<TestCompatibilityRowV1>,
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        validate_rows(&rows)?;
        let row_count = rows.len();
        let payload = TestCompatibilityResponseV1Payload {
            schema_version: SCHEMA_VERSION_VALUE,
            rows,
        };
        let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        let payload_len = payload_bytes.len();
        let total_len =
            HEADER_LEN
                .checked_add(payload_len)
                .ok_or(TransportError::ResponseTooLarge {
                    observed: usize::MAX,
                    cap: max_response_bytes,
                })?;
        if total_len > max_response_bytes {
            return Err(TransportError::ResponseTooLarge {
                observed: total_len,
                cap: max_response_bytes,
            });
        }
        let header = TransportHeader::new_with_schema(
            Self::header_spec(),
            row_count as u64,
            payload_len as u64,
            fnv1a64(&payload_bytes),
        );
        let mut header_bytes = [0_u8; HEADER_LEN];
        encode_header(&header, &mut header_bytes);
        let mut out = Vec::with_capacity(total_len);
        out.extend_from_slice(&header_bytes);
        out.extend_from_slice(&payload_bytes);
        Ok(out)
    }

    pub fn access(bytes: &[u8]) -> Result<TestCompatibilityV1View<'_>> {
        Ok(TestCompatibilityV1View {
            archived: Self::access_archived(bytes)?,
        })
    }

    pub(crate) fn access_archived(
        bytes: &[u8],
    ) -> Result<&ArchivedTestCompatibilityResponseV1Payload> {
        let (header, payload) = decode_payload(bytes, Self::header_spec())?;
        let archived =
            rkyv::access::<ArchivedTestCompatibilityResponseV1Payload, RkyvError>(payload)
                .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    /// Returns an archived payload view for immutable bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for this schema and then stored or transported without mutation.
    pub unsafe fn access_archived_trusted_unchecked(
        bytes: &[u8],
    ) -> Result<&ArchivedTestCompatibilityResponseV1Payload> {
        let header = decode_header(bytes)?;
        let payload = trusted_payload_for_schema(bytes, Self::header_spec())?;
        let archived = unsafe {
            rkyv::access_unchecked::<ArchivedTestCompatibilityResponseV1Payload>(payload)
        };
        validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    pub fn inspect(bytes: &[u8]) -> Result<BinaryInspection> {
        inspect_archived_rows(Self::access_archived(bytes)?)
    }
}

impl MbtSchema for TestCompatibilityV1 {
    type Row = TestCompatibilityRowV1;
    type View<'a> = TestCompatibilityV1View<'a>;

    fn encode_rows(rows: &[Self::Row], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode(rows, max_response_bytes)
    }
    fn encode_owned_rows(rows: Vec<Self::Row>, max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows, max_response_bytes)
    }
    fn access_view(bytes: &[u8]) -> Result<Self::View<'_>> {
        Self::access(bytes)
    }
    fn inspect_bytes(bytes: &[u8]) -> Result<BinaryInspection> {
        Self::inspect(bytes)
    }
}

pub struct TestCompatibilityV1View<'a> {
    archived: &'a ArchivedTestCompatibilityResponseV1Payload,
}

impl<'a> TestCompatibilityV1View<'a> {
    pub fn len(&self) -> usize {
        self.archived.rows.len()
    }
    pub fn is_empty(&self) -> bool {
        self.archived.rows.is_empty()
    }
    pub fn rows(&self) -> TestCompatibilityV1Rows<'a> {
        TestCompatibilityV1Rows {
            inner: self.archived.rows.iter(),
        }
    }
}

pub struct TestCompatibilityV1Rows<'a> {
    inner: core::slice::Iter<'a, <TestCompatibilityRowV1 as Archive>::Archived>,
}

impl<'a> Iterator for TestCompatibilityV1Rows<'a> {
    type Item = ArchivedTestCompatibilityV1Row<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        self.inner
            .next()
            .map(|row| ArchivedTestCompatibilityV1Row { row })
    }
}

pub struct ArchivedTestCompatibilityV1Row<'a> {
    row: &'a <TestCompatibilityRowV1 as Archive>::Archived,
}

impl<'a> ArchivedTestCompatibilityV1Row<'a> {
    pub fn schema_version(&self) -> u16 {
        self.row.schema_version.to_native()
    }
    pub fn tenant_ordinal(&self) -> u16 {
        self.row.tenant_ordinal.to_native()
    }
    pub fn tenant(&self) -> Result<&'static str> {
        tenant_symbol(self.row.tenant_ordinal.to_native())
    }
    pub fn entity_ordinal(&self) -> u16 {
        self.row.entity_ordinal.to_native()
    }
    pub fn entity(&self) -> Result<&'static str> {
        entity_symbol(self.row.entity_ordinal.to_native())
    }
    pub fn close_ms(&self) -> i64 {
        self.row.close_ms.to_native()
    }
    pub fn status_ordinal(&self) -> u16 {
        self.row.status_ordinal.to_native()
    }
    pub fn status(&self) -> Result<&'static str> {
        status_symbol(self.row.status_ordinal.to_native())
    }
    pub fn has_optional_status(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_STATUS_ORDINAL != 0
    }
    pub fn optional_status_ordinal(&self) -> u16 {
        self.row.optional_status_ordinal.to_native()
    }
    pub fn optional_status(&self) -> Result<&'static str> {
        status_symbol(self.row.optional_status_ordinal.to_native())
    }
    pub fn venues_mask(&self) -> u64 {
        self.row.venues_mask.to_native()
    }
    pub fn required_i64(&self) -> i64 {
        self.row.required_i64.to_native()
    }
    pub fn has_optional_i64(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_I64 != 0
    }
    pub fn optional_i64(&self) -> i64 {
        self.row.optional_i64.to_native()
    }
    pub fn required_i32(&self) -> i32 {
        self.row.required_i32.to_native()
    }
    pub fn has_optional_i32(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_I32 != 0
    }
    pub fn optional_i32(&self) -> i32 {
        self.row.optional_i32.to_native()
    }
    pub fn required_u32(&self) -> u32 {
        self.row.required_u32.to_native()
    }
    pub fn has_optional_u32(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_U32 != 0
    }
    pub fn optional_u32(&self) -> u32 {
        self.row.optional_u32.to_native()
    }
    pub fn required_f64(&self) -> f64 {
        self.row.required_f64.to_native()
    }
    pub fn has_optional_f64(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_F64 != 0
    }
    pub fn optional_f64(&self) -> f64 {
        self.row.optional_f64.to_native()
    }
    pub fn required_f32(&self) -> f32 {
        self.row.required_f32.to_native()
    }
    pub fn has_optional_f32(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_F32 != 0
    }
    pub fn optional_f32(&self) -> f32 {
        self.row.optional_f32.to_native()
    }
    pub fn required_bool(&self) -> bool {
        self.row.required_bool
    }
    pub fn has_optional_bool(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_BOOL != 0
    }
    pub fn optional_bool(&self) -> bool {
        self.row.optional_bool
    }
    pub fn required_text(&self) -> &'a str {
        self.row.required_text.as_str()
    }
    pub fn has_optional_text(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_TEXT != 0
    }
    pub fn optional_text(&self) -> &'a str {
        self.row.optional_text.as_str()
    }
    pub fn required_bytes(&self) -> &'a [u8] {
        self.row.required_bytes.as_slice()
    }
    pub fn has_optional_bytes(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_OPTIONAL_BYTES != 0
    }
    pub fn optional_bytes(&self) -> &'a [u8] {
        self.row.optional_bytes.as_slice()
    }
    pub fn uuid_text(&self) -> &'a str {
        self.row.uuid_text.as_str()
    }
    pub fn jsonb_text(&self) -> &'a str {
        self.row.jsonb_text.as_str()
    }
    pub fn timestamptz_text(&self) -> &'a str {
        self.row.timestamptz_text.as_str()
    }
    pub fn numeric_text(&self) -> &'a str {
        self.row.numeric_text.as_str()
    }
    pub fn required_i64_array(&self) -> impl Iterator<Item = i64> + '_ {
        self.row
            .required_i64_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn has_nullable_i64_array(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_NULLABLE_I64_ARRAY != 0
    }
    pub fn nullable_i64_array(&self) -> impl Iterator<Item = i64> + '_ {
        self.row
            .nullable_i64_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn required_i32_array(&self) -> impl Iterator<Item = i32> + '_ {
        self.row
            .required_i32_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn has_nullable_i32_array(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_NULLABLE_I32_ARRAY != 0
    }
    pub fn nullable_i32_array(&self) -> impl Iterator<Item = i32> + '_ {
        self.row
            .nullable_i32_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn required_u32_array(&self) -> impl Iterator<Item = u32> + '_ {
        self.row
            .required_u32_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn has_nullable_u32_array(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_NULLABLE_U32_ARRAY != 0
    }
    pub fn nullable_u32_array(&self) -> impl Iterator<Item = u32> + '_ {
        self.row
            .nullable_u32_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn required_f64_array(&self) -> impl Iterator<Item = f64> + '_ {
        self.row
            .required_f64_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn has_nullable_f64_array(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_NULLABLE_F64_ARRAY != 0
    }
    pub fn nullable_f64_array(&self) -> impl Iterator<Item = f64> + '_ {
        self.row
            .nullable_f64_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn required_f32_array(&self) -> impl Iterator<Item = f32> + '_ {
        self.row
            .required_f32_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn has_nullable_f32_array(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_NULLABLE_F32_ARRAY != 0
    }
    pub fn nullable_f32_array(&self) -> impl Iterator<Item = f32> + '_ {
        self.row
            .nullable_f32_array
            .iter()
            .map(|value| value.to_native())
    }
    pub fn presence_bits(&self) -> u64 {
        self.row.presence_bits.to_native()
    }
}

fn decode_payload(bytes: &[u8], schema: SchemaHeaderSpec) -> Result<(TransportHeader, &[u8])> {
    let header = decode_header(bytes)?;
    let payload = &bytes[HEADER_LEN..];
    validate_header_for_schema(&header, payload, schema)?;
    Ok((header, payload))
}

fn validate_archived_payload(
    archived: &ArchivedTestCompatibilityResponseV1Payload,
    expected_rows: u64,
) -> Result<()> {
    if archived.schema_version.to_native() != SCHEMA_VERSION_VALUE {
        return Err(TransportError::SchemaVersionMismatch {
            observed: archived.schema_version.to_native(),
            expected: SCHEMA_VERSION_VALUE,
        });
    }
    let expected = usize::try_from(expected_rows)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
    if archived.rows.len() != expected {
        return Err(TransportError::RowCountMismatch {
            observed: archived.rows.len(),
            expected: expected_rows,
        });
    }
    Ok(())
}

fn inspect_archived_rows(
    archived: &ArchivedTestCompatibilityResponseV1Payload,
) -> Result<BinaryInspection> {
    let mut semantic_checksum = fnv1a64("mathilde.test_compatibility.v1".as_bytes());
    let mut minimal_projection_checksum = semantic_checksum;
    for row in archived.rows.iter() {
        semantic_checksum = checksum_archived_row(semantic_checksum, row);
        minimal_projection_checksum = checksum_archived_row(minimal_projection_checksum, row);
    }
    Ok(BinaryInspection {
        row_count: archived.rows.len(),
        semantic_checksum,
        minimal_projection_checksum,
    })
}
