[package]
name = "mbt_adapter_arrow_ipc"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
arrow-array = "=56.2.1"
arrow-buffer = "=56.2.1"
arrow-ipc = "=56.2.1"
arrow-schema = "=56.2.1"
mbt_core = { path = "../../core" }
mbt_transponding = { path = "../../transponding" }
