// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=1 schema_version=1 schema_hash=6061383958499356843

use rkyv::rancor::{Error as RkyvError, Fallible, Source};
use rkyv::ser::{Allocator, Writer};
use rkyv::vec::{ArchivedVec, VecResolver};
use rkyv::{Archive, Place, Serialize as RkyvSerialize};

use metamorphic_binary_transport_core::envelope::{
    HEADER_LEN, SchemaHeaderSpec, TransportHeader, decode_header, encode_header, fnv1a64,
    trusted_payload_for_schema, validate_header_for_schema,
};
use metamorphic_binary_transport_core::error::{Result, TransportError};
use metamorphic_binary_transport_core::runtime::{BinaryInspection, MbtSchema};

pub const SCHEMA_ID: u32 = 1;
pub const SCHEMA_VERSION_VALUE: u16 = 1;
pub const SCHEMA_VERSION: u16 = SCHEMA_VERSION_VALUE;
pub const GENERATED_SCHEMA_HASH: u64 = 6061383958499356843;
pub const TRANSPORT_NAME: &str = "mathilde.bar.v1";
pub const SCHEMA_HEADER: SchemaHeaderSpec = SchemaHeaderSpec {
    schema_id: SCHEMA_ID,
    schema_version: SCHEMA_VERSION,
    schema_hash: GENERATED_SCHEMA_HASH,
};

pub const PAIR_ADAUSDT: u16 = 0;
pub const PAIR_BTCUSDT: u16 = 1;
pub const PAIR_ETHUSDT: u16 = 2;
pub const PAIR_LTCUSDT: u16 = 3;
pub const PAIR_XRPUSDT: u16 = 4;
pub const PAIR_COUNT: u16 = 5;

pub const TIMEFRAME_1M: u16 = 0;
pub const TIMEFRAME_COUNT: u16 = 1;

pub const SOURCE_NONE: u16 = 0;
pub const SOURCE_FRONTIER: u16 = 1;
pub const SOURCE_API: u16 = 2;
pub const SOURCE_SYNTHETIC: u16 = 3;
pub const SOURCE_FIX_DATA: u16 = 4;

pub const PROCESS_NONE: u16 = 0;
pub const PROCESS_FRONTIER: u16 = 1;
pub const PROCESS_DERIVED: u16 = 2;
pub const PROCESS_REPAIR: u16 = 3;

pub const RECOMPUTED_REASON_NONE: u16 = 0;
pub const RECOMPUTED_REASON_CANONICAL_REPAIR: u16 = 1;

pub const VENUE_BINANCE_BIT: u64 = 0;
pub const VENUE_BYBIT_BIT: u64 = 1;
pub const VENUE_OKX_BIT: u64 = 2;
pub const VALID_VENUE_MASK: u64 =
    (1 << VENUE_BINANCE_BIT) | (1 << VENUE_BYBIT_BIT) | (1 << VENUE_OKX_BIT);

pub const PRESENCE_VW: u64 = 1 << 0;
pub const PRESENCE_N: u64 = 1 << 1;
pub const PRESENCE_PROCESS_ORDINAL: u64 = 1 << 2;
pub const PRESENCE_INGESTED_AT_MS: u64 = 1 << 3;
pub const PRESENCE_TARGET_INGESTED_AT_MS: u64 = 1 << 4;
pub const PRESENCE_BUILT_AT_MS: u64 = 1 << 5;
pub const PRESENCE_COMMITTED_AT_MS: u64 = 1 << 6;
pub const PRESENCE_HARMONIZED_AT_MS: u64 = 1 << 7;
pub const PRESENCE_RECOMPUTED_AT_MS: u64 = 1 << 8;
pub const PRESENCE_RECOMPUTED_REASON_ORDINAL: u64 = 1 << 9;
pub const PRESENCE_COVERED_1M_COUNT: u64 = 1 << 10;
pub const PRESENCE_EXPECTED_1M_COUNT: u64 = 1 << 11;
pub const PRESENCE_COVERAGE_RATIO: u64 = 1 << 12;
pub const PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER: u64 = 1 << 13;
pub const PRESENCE_INPUTS_SOURCE_COUNTS_API: u64 = 1 << 14;
pub const PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC: u64 = 1 << 15;
pub const PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA: u64 = 1 << 16;
pub const PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO: u64 = 1 << 17;
pub const PRESENCE_FRONTIER_5S_EXPECTED: u64 = 1 << 18;
pub const PRESENCE_FRONTIER_5S_SYNTH_N: u64 = 1 << 19;
pub const PRESENCE_FRONTIER_5S_SYNTH_RATIO: u64 = 1 << 20;
pub const PRESENCE_FRONTIER_5S_TRADE_N: u64 = 1 << 21;
pub const PRESENCE_FRONTIER_5S_TRADE_RATIO: u64 = 1 << 22;
pub const PRESENCE_AGE_MS: u64 = 1 << 23;
pub const PRESENCE_ALLOWED_MASK: u64 = (1 << 24) - 1;

#[derive(Clone, Archive, RkyvSerialize)]
pub struct MathildeTransportResponseV1Payload {
    pub schema_version: u16,
    pub rows: Vec<MathildeBarRowV1>,
}

#[derive(Clone, Archive, RkyvSerialize)]
pub struct MathildeBarRowV1 {
    pub schema_version: u16,
    pub pair_ordinal: u16,
    pub tf_ordinal: u16,
    pub open_ms: i64,
    pub close_ms: i64,
    pub o: f64,
    pub h: f64,
    pub l: f64,
    pub c: f64,
    pub v: f64,
    pub quote_v: f64,
    pub taker_known_v: f64,
    pub taker_signed_v: f64,
    pub taker_known_quote_v: f64,
    pub taker_signed_quote_v: f64,
    pub taker_known_n: i64,
    pub taker_signed_n: i64,
    pub vw: f64,
    pub n: i64,
    pub source_ordinal: u16,
    pub process_ordinal: u16,
    pub venues_expected_mask: u64,
    pub venues_with_trades_mask: u64,
    pub ingested_at_ms: i64,
    pub target_ingested_at_ms: i64,
    pub built_at_ms: i64,
    pub committed_at_ms: i64,
    pub harmonized_at_ms: i64,
    pub recomputed_at_ms: i64,
    pub recomputed_reason_ordinal: u16,
    pub covered_1m_count: i64,
    pub expected_1m_count: i64,
    pub coverage_ratio: f64,
    pub inputs_source_counts_frontier: i64,
    pub inputs_source_counts_api: i64,
    pub inputs_source_counts_synthetic: i64,
    pub inputs_source_counts_fix_data: i64,
    pub frontier_5s_inputs_coverage_ratio: f64,
    pub frontier_5s_expected: i64,
    pub frontier_5s_synth_n: i64,
    pub frontier_5s_synth_ratio: f64,
    pub frontier_5s_trade_n: i64,
    pub frontier_5s_trade_ratio: f64,
    pub age_ms: i64,
    pub presence_bits: u64,
}

pub fn validate_rows(rows: &[MathildeBarRowV1]) -> Result<()> {
    let mut previous = None;
    for row in rows {
        validate_row(row, previous)?;
        previous = Some(row);
    }
    Ok(())
}

pub fn validate_row(row: &MathildeBarRowV1, previous: Option<&MathildeBarRowV1>) -> Result<()> {
    if row.schema_version != 1 {
        return Err(TransportError::SchemaVersionMismatch {
            observed: row.schema_version,
            expected: 1,
        });
    }
    pair_symbol(row.pair_ordinal)?;
    tf_symbol(row.tf_ordinal)?;
    validate_finite_f64("o", row.o)?;
    validate_finite_f64("h", row.h)?;
    validate_finite_f64("l", row.l)?;
    validate_finite_f64("c", row.c)?;
    validate_finite_f64("v", row.v)?;
    validate_finite_f64("quote_v", row.quote_v)?;
    validate_finite_f64("taker_known_v", row.taker_known_v)?;
    validate_finite_f64("taker_signed_v", row.taker_signed_v)?;
    validate_finite_f64("taker_known_quote_v", row.taker_known_quote_v)?;
    validate_finite_f64("taker_signed_quote_v", row.taker_signed_quote_v)?;
    validate_finite_f64("vw", row.vw)?;
    source_symbol(row.source_ordinal)?;
    if row.process_ordinal != 0 {
        process_symbol(row.process_ordinal)?;
    }
    if row.venues_expected_mask & !VALID_VENUE_MASK != 0 {
        return Err(TransportError::InvalidBitmask {
            field: "metadata.venues_expected",
            value: row.venues_expected_mask,
        });
    }
    if row.venues_with_trades_mask & !VALID_VENUE_MASK != 0 {
        return Err(TransportError::InvalidBitmask {
            field: "metadata.venues_with_trades",
            value: row.venues_with_trades_mask,
        });
    }
    if row.recomputed_reason_ordinal != 0 {
        recomputed_reason_symbol(row.recomputed_reason_ordinal)?;
    }
    validate_finite_f64("metadata.coverage_ratio", row.coverage_ratio)?;
    validate_finite_f64(
        "metadata.frontier_5s_inputs_coverage_ratio",
        row.frontier_5s_inputs_coverage_ratio,
    )?;
    validate_finite_f64(
        "metadata.frontier_5s_synth_ratio",
        row.frontier_5s_synth_ratio,
    )?;
    validate_finite_f64(
        "metadata.frontier_5s_trade_ratio",
        row.frontier_5s_trade_ratio,
    )?;
    if row.presence_bits & !PRESENCE_ALLOWED_MASK != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_VW == 0 && row.vw != 0.0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_N == 0 && row.n != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_PROCESS_ORDINAL == 0 && row.process_ordinal != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_INGESTED_AT_MS == 0 && row.ingested_at_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_TARGET_INGESTED_AT_MS == 0 && row.target_ingested_at_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_BUILT_AT_MS == 0 && row.built_at_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_COMMITTED_AT_MS == 0 && row.committed_at_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_HARMONIZED_AT_MS == 0 && row.harmonized_at_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_RECOMPUTED_AT_MS == 0 && row.recomputed_at_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_RECOMPUTED_REASON_ORDINAL == 0
        && row.recomputed_reason_ordinal != 0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_COVERED_1M_COUNT == 0 && row.covered_1m_count != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_EXPECTED_1M_COUNT == 0 && row.expected_1m_count != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_COVERAGE_RATIO == 0 && row.coverage_ratio != 0.0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER == 0
        && row.inputs_source_counts_frontier != 0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_INPUTS_SOURCE_COUNTS_API == 0
        && row.inputs_source_counts_api != 0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC == 0
        && row.inputs_source_counts_synthetic != 0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA == 0
        && row.inputs_source_counts_fix_data != 0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO == 0
        && row.frontier_5s_inputs_coverage_ratio != 0.0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_FRONTIER_5S_EXPECTED == 0 && row.frontier_5s_expected != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_FRONTIER_5S_SYNTH_N == 0 && row.frontier_5s_synth_n != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_FRONTIER_5S_SYNTH_RATIO == 0
        && row.frontier_5s_synth_ratio != 0.0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_FRONTIER_5S_TRADE_N == 0 && row.frontier_5s_trade_n != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_FRONTIER_5S_TRADE_RATIO == 0
        && row.frontier_5s_trade_ratio != 0.0
    {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_AGE_MS == 0 && row.age_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if previous.is_some_and(|prev| {
        (row.pair_ordinal, row.tf_ordinal, row.close_ms)
            < (prev.pair_ordinal, prev.tf_ordinal, prev.close_ms)
    }) {
        return Err(TransportError::InvalidTimeGrid(
            "key order regression".to_string(),
        ));
    }
    Ok(())
}

fn validate_finite_f64(field: &'static str, value: f64) -> Result<()> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(TransportError::NonFiniteNumeric(field))
    }
}

pub fn semantic_checksum(rows: &[MathildeBarRowV1]) -> u64 {
    let mut checksum = fnv1a64("mathilde.bar.v1".as_bytes());
    for row in rows {
        checksum = checksum_row(checksum, row);
    }
    checksum
}

pub fn minimal_projection_checksum(rows: &[MathildeBarRowV1]) -> u64 {
    semantic_checksum(rows)
}

pub fn checksum_row(mut checksum: u64, row: &MathildeBarRowV1) -> u64 {
    checksum = update_u16(checksum, row.schema_version);
    checksum = update_u16(checksum, row.pair_ordinal);
    checksum = update_u16(checksum, row.tf_ordinal);
    checksum = update_i64(checksum, row.open_ms);
    checksum = update_i64(checksum, row.close_ms);
    checksum = update_f64(checksum, row.o);
    checksum = update_f64(checksum, row.h);
    checksum = update_f64(checksum, row.l);
    checksum = update_f64(checksum, row.c);
    checksum = update_f64(checksum, row.v);
    checksum = update_f64(checksum, row.quote_v);
    checksum = update_f64(checksum, row.taker_known_v);
    checksum = update_f64(checksum, row.taker_signed_v);
    checksum = update_f64(checksum, row.taker_known_quote_v);
    checksum = update_f64(checksum, row.taker_signed_quote_v);
    checksum = update_i64(checksum, row.taker_known_n);
    checksum = update_i64(checksum, row.taker_signed_n);
    checksum = update_f64(checksum, row.vw);
    checksum = update_i64(checksum, row.n);
    checksum = update_u16(checksum, row.source_ordinal);
    checksum = update_u16(checksum, row.process_ordinal);
    checksum = update_u64(checksum, row.venues_expected_mask);
    checksum = update_u64(checksum, row.venues_with_trades_mask);
    checksum = update_i64(checksum, row.ingested_at_ms);
    checksum = update_i64(checksum, row.target_ingested_at_ms);
    checksum = update_i64(checksum, row.built_at_ms);
    checksum = update_i64(checksum, row.committed_at_ms);
    checksum = update_i64(checksum, row.harmonized_at_ms);
    checksum = update_i64(checksum, row.recomputed_at_ms);
    checksum = update_u16(checksum, row.recomputed_reason_ordinal);
    checksum = update_i64(checksum, row.covered_1m_count);
    checksum = update_i64(checksum, row.expected_1m_count);
    checksum = update_f64(checksum, row.coverage_ratio);
    checksum = update_i64(checksum, row.inputs_source_counts_frontier);
    checksum = update_i64(checksum, row.inputs_source_counts_api);
    checksum = update_i64(checksum, row.inputs_source_counts_synthetic);
    checksum = update_i64(checksum, row.inputs_source_counts_fix_data);
    checksum = update_f64(checksum, row.frontier_5s_inputs_coverage_ratio);
    checksum = update_i64(checksum, row.frontier_5s_expected);
    checksum = update_i64(checksum, row.frontier_5s_synth_n);
    checksum = update_f64(checksum, row.frontier_5s_synth_ratio);
    checksum = update_i64(checksum, row.frontier_5s_trade_n);
    checksum = update_f64(checksum, row.frontier_5s_trade_ratio);
    checksum = update_i64(checksum, row.age_ms);
    checksum = update_u64(checksum, row.presence_bits);
    checksum
}

pub fn checksum_archived_row(
    mut checksum: u64,
    row: &<MathildeBarRowV1 as Archive>::Archived,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.pair_ordinal.to_native());
    checksum = update_u16(checksum, row.tf_ordinal.to_native());
    checksum = update_i64(checksum, row.open_ms.to_native());
    checksum = update_i64(checksum, row.close_ms.to_native());
    checksum = update_f64(checksum, row.o.to_native());
    checksum = update_f64(checksum, row.h.to_native());
    checksum = update_f64(checksum, row.l.to_native());
    checksum = update_f64(checksum, row.c.to_native());
    checksum = update_f64(checksum, row.v.to_native());
    checksum = update_f64(checksum, row.quote_v.to_native());
    checksum = update_f64(checksum, row.taker_known_v.to_native());
    checksum = update_f64(checksum, row.taker_signed_v.to_native());
    checksum = update_f64(checksum, row.taker_known_quote_v.to_native());
    checksum = update_f64(checksum, row.taker_signed_quote_v.to_native());
    checksum = update_i64(checksum, row.taker_known_n.to_native());
    checksum = update_i64(checksum, row.taker_signed_n.to_native());
    checksum = update_f64(checksum, row.vw.to_native());
    checksum = update_i64(checksum, row.n.to_native());
    checksum = update_u16(checksum, row.source_ordinal.to_native());
    checksum = update_u16(checksum, row.process_ordinal.to_native());
    checksum = update_u64(checksum, row.venues_expected_mask.to_native());
    checksum = update_u64(checksum, row.venues_with_trades_mask.to_native());
    checksum = update_i64(checksum, row.ingested_at_ms.to_native());
    checksum = update_i64(checksum, row.target_ingested_at_ms.to_native());
    checksum = update_i64(checksum, row.built_at_ms.to_native());
    checksum = update_i64(checksum, row.committed_at_ms.to_native());
    checksum = update_i64(checksum, row.harmonized_at_ms.to_native());
    checksum = update_i64(checksum, row.recomputed_at_ms.to_native());
    checksum = update_u16(checksum, row.recomputed_reason_ordinal.to_native());
    checksum = update_i64(checksum, row.covered_1m_count.to_native());
    checksum = update_i64(checksum, row.expected_1m_count.to_native());
    checksum = update_f64(checksum, row.coverage_ratio.to_native());
    checksum = update_i64(checksum, row.inputs_source_counts_frontier.to_native());
    checksum = update_i64(checksum, row.inputs_source_counts_api.to_native());
    checksum = update_i64(checksum, row.inputs_source_counts_synthetic.to_native());
    checksum = update_i64(checksum, row.inputs_source_counts_fix_data.to_native());
    checksum = update_f64(checksum, row.frontier_5s_inputs_coverage_ratio.to_native());
    checksum = update_i64(checksum, row.frontier_5s_expected.to_native());
    checksum = update_i64(checksum, row.frontier_5s_synth_n.to_native());
    checksum = update_f64(checksum, row.frontier_5s_synth_ratio.to_native());
    checksum = update_i64(checksum, row.frontier_5s_trade_n.to_native());
    checksum = update_f64(checksum, row.frontier_5s_trade_ratio.to_native());
    checksum = update_i64(checksum, row.age_ms.to_native());
    checksum = update_u64(checksum, row.presence_bits.to_native());
    checksum
}

fn fnv1a64_update(mut checksum: u64, byte: u8) -> u64 {
    checksum ^= u64::from(byte);
    checksum.wrapping_mul(0x00000100000001B3)
}

fn update_fixed<const N: usize>(mut checksum: u64, bytes: [u8; N]) -> u64 {
    for byte in checksum.to_le_bytes() {
        checksum = fnv1a64_update(checksum, byte);
    }
    for byte in bytes {
        checksum = fnv1a64_update(checksum, byte);
    }
    checksum
}

fn update_u16(checksum: u64, value: u16) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_i64(checksum: u64, value: i64) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_u64(checksum: u64, value: u64) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_f64(checksum: u64, value: f64) -> u64 {
    update_u64(checksum, value.to_bits())
}

pub fn pair_symbol(value: u16) -> Result<&'static str> {
    match value {
        0 => Ok("ADAUSDT"),
        1 => Ok("BTCUSDT"),
        2 => Ok("ETHUSDT"),
        3 => Ok("LTCUSDT"),
        4 => Ok("XRPUSDT"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "pair",
            value: other,
        }),
    }
}

pub fn pair_ordinal(value: &str) -> Result<u16> {
    match value {
        "ADAUSDT" => Ok(0),
        "BTCUSDT" => Ok(1),
        "ETHUSDT" => Ok(2),
        "LTCUSDT" => Ok(3),
        "XRPUSDT" => Ok(4),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "pair",
            value: u16::MAX,
        }),
    }
}

pub fn tf_symbol(value: u16) -> Result<&'static str> {
    match value {
        0 => Ok("1m"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "timeframe",
            value: other,
        }),
    }
}

pub fn tf_ordinal(value: &str) -> Result<u16> {
    match value {
        "1m" => Ok(0),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "timeframe",
            value: u16::MAX,
        }),
    }
}

pub fn source_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("frontier"),
        2 => Ok("api"),
        3 => Ok("synthetic"),
        4 => Ok("fix_data"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "source",
            value: other,
        }),
    }
}

pub fn source_ordinal(value: &str) -> Result<u16> {
    match value {
        "frontier" => Ok(1),
        "api" => Ok(2),
        "synthetic" => Ok(3),
        "fix_data" => Ok(4),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "source",
            value: u16::MAX,
        }),
    }
}

pub fn process_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("frontier"),
        2 => Ok("derived"),
        3 => Ok("repair"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "process",
            value: other,
        }),
    }
}

pub fn process_ordinal(value: &str) -> Result<u16> {
    match value {
        "frontier" => Ok(1),
        "derived" => Ok(2),
        "repair" => Ok(3),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "process",
            value: u16::MAX,
        }),
    }
}

pub fn recomputed_reason_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("canonical_repair"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "recomputed_reason",
            value: other,
        }),
    }
}

pub fn recomputed_reason_ordinal(value: &str) -> Result<u16> {
    match value {
        "canonical_repair" => Ok(1),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "recomputed_reason",
            value: u16::MAX,
        }),
    }
}

pub fn venue_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("binance"),
        2 => Ok("bybit"),
        3 => Ok("okx"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "venue",
            value: other,
        }),
    }
}

pub fn venue_ordinal(value: &str) -> Result<u16> {
    match value {
        "binance" => Ok(1),
        "bybit" => Ok(2),
        "okx" => Ok(3),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "venue",
            value: u16::MAX,
        }),
    }
}

pub struct BarsV1;

impl BarsV1 {
    pub const SCHEMA_ID: u32 = SCHEMA_ID;
    pub const SCHEMA_VERSION: u16 = SCHEMA_VERSION;
    pub const SCHEMA_HASH: u64 = GENERATED_SCHEMA_HASH;
    pub const TRANSPORT_NAME: &'static str = TRANSPORT_NAME;

    pub fn header_spec() -> SchemaHeaderSpec {
        SCHEMA_HEADER
    }

    pub fn encode(rows: &[MathildeBarRowV1], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows.to_vec(), max_response_bytes)
    }

    pub fn encode_owned(rows: Vec<MathildeBarRowV1>, max_response_bytes: usize) -> Result<Vec<u8>> {
        validate_rows(&rows)?;
        let row_count = rows.len();
        let payload = MathildeTransportResponseV1Payload {
            schema_version: SCHEMA_VERSION_VALUE,
            rows,
        };
        let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        let payload_len = payload_bytes.len();
        let total_len =
            HEADER_LEN
                .checked_add(payload_len)
                .ok_or(TransportError::ResponseTooLarge {
                    observed: usize::MAX,
                    cap: max_response_bytes,
                })?;
        if total_len > max_response_bytes {
            return Err(TransportError::ResponseTooLarge {
                observed: total_len,
                cap: max_response_bytes,
            });
        }
        let header = TransportHeader::new_with_schema(
            Self::header_spec(),
            row_count as u64,
            payload_len as u64,
            fnv1a64(&payload_bytes),
        );
        let mut header_bytes = [0_u8; HEADER_LEN];
        encode_header(&header, &mut header_bytes);
        let mut out = Vec::with_capacity(total_len);
        out.extend_from_slice(&header_bytes);
        out.extend_from_slice(&payload_bytes);
        Ok(out)
    }

    pub fn access(bytes: &[u8]) -> Result<BarsV1View<'_>> {
        Ok(BarsV1View {
            archived: Self::access_archived(bytes)?,
        })
    }

    pub(crate) fn access_archived(
        bytes: &[u8],
    ) -> Result<&ArchivedMathildeTransportResponseV1Payload> {
        let (header, payload) = decode_payload(bytes, Self::header_spec())?;
        let archived =
            rkyv::access::<ArchivedMathildeTransportResponseV1Payload, RkyvError>(payload)
                .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    /// Returns an archived payload view for immutable bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for this schema and then stored or transported without mutation.
    pub unsafe fn access_archived_trusted_unchecked(
        bytes: &[u8],
    ) -> Result<&ArchivedMathildeTransportResponseV1Payload> {
        let header = decode_header(bytes)?;
        let payload = trusted_payload_for_schema(bytes, Self::header_spec())?;
        let archived = unsafe {
            rkyv::access_unchecked::<ArchivedMathildeTransportResponseV1Payload>(payload)
        };
        validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    pub fn inspect(bytes: &[u8]) -> Result<BinaryInspection> {
        inspect_archived_rows(Self::access_archived(bytes)?)
    }
}

impl MbtSchema for BarsV1 {
    type Row = MathildeBarRowV1;
    type View<'a> = BarsV1View<'a>;

    fn encode_rows(rows: &[Self::Row], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode(rows, max_response_bytes)
    }
    fn encode_owned_rows(rows: Vec<Self::Row>, max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows, max_response_bytes)
    }
    fn access_view(bytes: &[u8]) -> Result<Self::View<'_>> {
        Self::access(bytes)
    }
    fn inspect_bytes(bytes: &[u8]) -> Result<BinaryInspection> {
        Self::inspect(bytes)
    }
}

pub struct BarsV1View<'a> {
    archived: &'a ArchivedMathildeTransportResponseV1Payload,
}

impl<'a> BarsV1View<'a> {
    pub fn len(&self) -> usize {
        self.archived.rows.len()
    }
    pub fn is_empty(&self) -> bool {
        self.archived.rows.is_empty()
    }
    pub fn rows(&self) -> BarsV1Rows<'a> {
        BarsV1Rows {
            inner: self.archived.rows.iter(),
        }
    }
}

pub struct BarsV1Rows<'a> {
    inner: core::slice::Iter<'a, <MathildeBarRowV1 as Archive>::Archived>,
}

impl<'a> Iterator for BarsV1Rows<'a> {
    type Item = ArchivedBarsV1Row<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        self.inner.next().map(|row| ArchivedBarsV1Row { row })
    }
}

pub struct ArchivedBarsV1Row<'a> {
    row: &'a <MathildeBarRowV1 as Archive>::Archived,
}

impl<'a> ArchivedBarsV1Row<'a> {
    pub fn schema_version(&self) -> u16 {
        self.row.schema_version.to_native()
    }
    pub fn pair_ordinal(&self) -> u16 {
        self.row.pair_ordinal.to_native()
    }
    pub fn pair(&self) -> Result<&'static str> {
        pair_symbol(self.row.pair_ordinal.to_native())
    }
    pub fn tf_ordinal(&self) -> u16 {
        self.row.tf_ordinal.to_native()
    }
    pub fn tf(&self) -> Result<&'static str> {
        tf_symbol(self.row.tf_ordinal.to_native())
    }
    pub fn open_ms(&self) -> i64 {
        self.row.open_ms.to_native()
    }
    pub fn close_ms(&self) -> i64 {
        self.row.close_ms.to_native()
    }
    pub fn o(&self) -> f64 {
        self.row.o.to_native()
    }
    pub fn h(&self) -> f64 {
        self.row.h.to_native()
    }
    pub fn l(&self) -> f64 {
        self.row.l.to_native()
    }
    pub fn c(&self) -> f64 {
        self.row.c.to_native()
    }
    pub fn v(&self) -> f64 {
        self.row.v.to_native()
    }
    pub fn quote_v(&self) -> f64 {
        self.row.quote_v.to_native()
    }
    pub fn taker_known_v(&self) -> f64 {
        self.row.taker_known_v.to_native()
    }
    pub fn taker_signed_v(&self) -> f64 {
        self.row.taker_signed_v.to_native()
    }
    pub fn taker_known_quote_v(&self) -> f64 {
        self.row.taker_known_quote_v.to_native()
    }
    pub fn taker_signed_quote_v(&self) -> f64 {
        self.row.taker_signed_quote_v.to_native()
    }
    pub fn taker_known_n(&self) -> i64 {
        self.row.taker_known_n.to_native()
    }
    pub fn taker_signed_n(&self) -> i64 {
        self.row.taker_signed_n.to_native()
    }
    pub fn has_vw(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_VW != 0
    }
    pub fn vw(&self) -> f64 {
        self.row.vw.to_native()
    }
    pub fn has_n(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_N != 0
    }
    pub fn n(&self) -> i64 {
        self.row.n.to_native()
    }
    pub fn source_ordinal(&self) -> u16 {
        self.row.source_ordinal.to_native()
    }
    pub fn source(&self) -> Result<&'static str> {
        source_symbol(self.row.source_ordinal.to_native())
    }
    pub fn has_process(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0
    }
    pub fn process_ordinal(&self) -> u16 {
        self.row.process_ordinal.to_native()
    }
    pub fn process(&self) -> Result<&'static str> {
        process_symbol(self.row.process_ordinal.to_native())
    }
    pub fn venues_expected_mask(&self) -> u64 {
        self.row.venues_expected_mask.to_native()
    }
    pub fn venues_with_trades_mask(&self) -> u64 {
        self.row.venues_with_trades_mask.to_native()
    }
    pub fn has_ingested_at_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0
    }
    pub fn ingested_at_ms(&self) -> i64 {
        self.row.ingested_at_ms.to_native()
    }
    pub fn has_target_ingested_at_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0
    }
    pub fn target_ingested_at_ms(&self) -> i64 {
        self.row.target_ingested_at_ms.to_native()
    }
    pub fn has_built_at_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0
    }
    pub fn built_at_ms(&self) -> i64 {
        self.row.built_at_ms.to_native()
    }
    pub fn has_committed_at_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0
    }
    pub fn committed_at_ms(&self) -> i64 {
        self.row.committed_at_ms.to_native()
    }
    pub fn has_harmonized_at_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0
    }
    pub fn harmonized_at_ms(&self) -> i64 {
        self.row.harmonized_at_ms.to_native()
    }
    pub fn has_recomputed_at_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0
    }
    pub fn recomputed_at_ms(&self) -> i64 {
        self.row.recomputed_at_ms.to_native()
    }
    pub fn has_recomputed_reason(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0
    }
    pub fn recomputed_reason_ordinal(&self) -> u16 {
        self.row.recomputed_reason_ordinal.to_native()
    }
    pub fn recomputed_reason(&self) -> Result<&'static str> {
        recomputed_reason_symbol(self.row.recomputed_reason_ordinal.to_native())
    }
    pub fn has_covered_1m_count(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_COVERED_1M_COUNT != 0
    }
    pub fn covered_1m_count(&self) -> i64 {
        self.row.covered_1m_count.to_native()
    }
    pub fn has_expected_1m_count(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_EXPECTED_1M_COUNT != 0
    }
    pub fn expected_1m_count(&self) -> i64 {
        self.row.expected_1m_count.to_native()
    }
    pub fn has_coverage_ratio(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0
    }
    pub fn coverage_ratio(&self) -> f64 {
        self.row.coverage_ratio.to_native()
    }
    pub fn has_inputs_source_counts_frontier(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER != 0
    }
    pub fn inputs_source_counts_frontier(&self) -> i64 {
        self.row.inputs_source_counts_frontier.to_native()
    }
    pub fn has_inputs_source_counts_api(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0
    }
    pub fn inputs_source_counts_api(&self) -> i64 {
        self.row.inputs_source_counts_api.to_native()
    }
    pub fn has_inputs_source_counts_synthetic(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0
    }
    pub fn inputs_source_counts_synthetic(&self) -> i64 {
        self.row.inputs_source_counts_synthetic.to_native()
    }
    pub fn has_inputs_source_counts_fix_data(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA != 0
    }
    pub fn inputs_source_counts_fix_data(&self) -> i64 {
        self.row.inputs_source_counts_fix_data.to_native()
    }
    pub fn has_frontier_5s_inputs_coverage_ratio(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO != 0
    }
    pub fn frontier_5s_inputs_coverage_ratio(&self) -> f64 {
        self.row.frontier_5s_inputs_coverage_ratio.to_native()
    }
    pub fn has_frontier_5s_expected(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_EXPECTED != 0
    }
    pub fn frontier_5s_expected(&self) -> i64 {
        self.row.frontier_5s_expected.to_native()
    }
    pub fn has_frontier_5s_synth_n(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_N != 0
    }
    pub fn frontier_5s_synth_n(&self) -> i64 {
        self.row.frontier_5s_synth_n.to_native()
    }
    pub fn has_frontier_5s_synth_ratio(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_RATIO != 0
    }
    pub fn frontier_5s_synth_ratio(&self) -> f64 {
        self.row.frontier_5s_synth_ratio.to_native()
    }
    pub fn has_frontier_5s_trade_n(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_N != 0
    }
    pub fn frontier_5s_trade_n(&self) -> i64 {
        self.row.frontier_5s_trade_n.to_native()
    }
    pub fn has_frontier_5s_trade_ratio(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_RATIO != 0
    }
    pub fn frontier_5s_trade_ratio(&self) -> f64 {
        self.row.frontier_5s_trade_ratio.to_native()
    }
    pub fn has_age_ms(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_AGE_MS != 0
    }
    pub fn age_ms(&self) -> i64 {
        self.row.age_ms.to_native()
    }
    pub fn presence_bits(&self) -> u64 {
        self.row.presence_bits.to_native()
    }
}

fn decode_payload(bytes: &[u8], schema: SchemaHeaderSpec) -> Result<(TransportHeader, &[u8])> {
    let header = decode_header(bytes)?;
    let payload = &bytes[HEADER_LEN..];
    validate_header_for_schema(&header, payload, schema)?;
    Ok((header, payload))
}

fn validate_archived_payload(
    archived: &ArchivedMathildeTransportResponseV1Payload,
    expected_rows: u64,
) -> Result<()> {
    if archived.schema_version.to_native() != SCHEMA_VERSION_VALUE {
        return Err(TransportError::SchemaVersionMismatch {
            observed: archived.schema_version.to_native(),
            expected: SCHEMA_VERSION_VALUE,
        });
    }
    let expected = usize::try_from(expected_rows)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
    if archived.rows.len() != expected {
        return Err(TransportError::RowCountMismatch {
            observed: archived.rows.len(),
            expected: expected_rows,
        });
    }
    Ok(())
}

fn inspect_archived_rows(
    archived: &ArchivedMathildeTransportResponseV1Payload,
) -> Result<BinaryInspection> {
    let mut semantic_checksum = fnv1a64("mathilde.bar.v1".as_bytes());
    let mut minimal_projection_checksum = semantic_checksum;
    for row in archived.rows.iter() {
        semantic_checksum = checksum_archived_row(semantic_checksum, row);
        minimal_projection_checksum = checksum_archived_row(minimal_projection_checksum, row);
    }
    Ok(BinaryInspection {
        row_count: archived.rows.len(),
        semantic_checksum,
        minimal_projection_checksum,
    })
}
const NO_METADATA_SCHEMA_ID: u32 = 1;
const NO_METADATA_SCHEMA_VERSION_VALUE: u16 = 1;
const NO_METADATA_SCHEMA_VERSION: u16 = NO_METADATA_SCHEMA_VERSION_VALUE;
const NO_METADATA_GENERATED_SCHEMA_HASH: u64 = 2810655320728765998;
const NO_METADATA_TRANSPORT_NAME: &str = "mathilde.bar.v1.no_metadata";
const NO_METADATA_SCHEMA_HEADER: SchemaHeaderSpec = SchemaHeaderSpec {
    schema_id: NO_METADATA_SCHEMA_ID,
    schema_version: NO_METADATA_SCHEMA_VERSION,
    schema_hash: NO_METADATA_GENERATED_SCHEMA_HASH,
};

const NO_METADATA_PRESENCE_VW: u64 = 1 << 0;
const NO_METADATA_PRESENCE_N: u64 = 1 << 1;
const NO_METADATA_PRESENCE_AGE_MS: u64 = 1 << 2;
const NO_METADATA_PRESENCE_ALLOWED_MASK: u64 = (1 << 3) - 1;

#[derive(Clone, Archive, RkyvSerialize)]
pub struct MathildeTransportResponseV1PayloadNoMetadata {
    pub schema_version: u16,
    pub rows: Vec<MathildeBarRowV1NoMetadata>,
}

#[derive(Clone, Archive, RkyvSerialize)]
pub struct MathildeBarRowV1NoMetadata {
    pub schema_version: u16,
    pub pair_ordinal: u16,
    pub tf_ordinal: u16,
    pub open_ms: i64,
    pub close_ms: i64,
    pub o: f64,
    pub h: f64,
    pub l: f64,
    pub c: f64,
    pub v: f64,
    pub quote_v: f64,
    pub taker_known_v: f64,
    pub taker_signed_v: f64,
    pub taker_known_quote_v: f64,
    pub taker_signed_quote_v: f64,
    pub taker_known_n: i64,
    pub taker_signed_n: i64,
    pub vw: f64,
    pub n: i64,
    pub age_ms: i64,
    pub presence_bits: u64,
}

fn no_metadata_validate_rows(rows: &[MathildeBarRowV1NoMetadata]) -> Result<()> {
    let mut previous = None;
    for row in rows {
        no_metadata_validate_row(row, previous)?;
        previous = Some(row);
    }
    Ok(())
}

fn no_metadata_validate_row(
    row: &MathildeBarRowV1NoMetadata,
    previous: Option<&MathildeBarRowV1NoMetadata>,
) -> Result<()> {
    if row.schema_version != 1 {
        return Err(TransportError::SchemaVersionMismatch {
            observed: row.schema_version,
            expected: 1,
        });
    }
    pair_symbol(row.pair_ordinal)?;
    tf_symbol(row.tf_ordinal)?;
    validate_finite_f64("o", row.o)?;
    validate_finite_f64("h", row.h)?;
    validate_finite_f64("l", row.l)?;
    validate_finite_f64("c", row.c)?;
    validate_finite_f64("v", row.v)?;
    validate_finite_f64("quote_v", row.quote_v)?;
    validate_finite_f64("taker_known_v", row.taker_known_v)?;
    validate_finite_f64("taker_signed_v", row.taker_signed_v)?;
    validate_finite_f64("taker_known_quote_v", row.taker_known_quote_v)?;
    validate_finite_f64("taker_signed_quote_v", row.taker_signed_quote_v)?;
    validate_finite_f64("vw", row.vw)?;
    if row.presence_bits & !NO_METADATA_PRESENCE_ALLOWED_MASK != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & NO_METADATA_PRESENCE_VW == 0 && row.vw != 0.0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & NO_METADATA_PRESENCE_N == 0 && row.n != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & NO_METADATA_PRESENCE_AGE_MS == 0 && row.age_ms != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if previous.is_some_and(|prev| {
        (row.pair_ordinal, row.tf_ordinal, row.close_ms)
            < (prev.pair_ordinal, prev.tf_ordinal, prev.close_ms)
    }) {
        return Err(TransportError::InvalidTimeGrid(
            "key order regression".to_string(),
        ));
    }
    Ok(())
}

fn no_metadata_checksum_archived_row(
    mut checksum: u64,
    row: &<MathildeBarRowV1NoMetadata as Archive>::Archived,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.pair_ordinal.to_native());
    checksum = update_u16(checksum, row.tf_ordinal.to_native());
    checksum = update_i64(checksum, row.open_ms.to_native());
    checksum = update_i64(checksum, row.close_ms.to_native());
    checksum = update_f64(checksum, row.o.to_native());
    checksum = update_f64(checksum, row.h.to_native());
    checksum = update_f64(checksum, row.l.to_native());
    checksum = update_f64(checksum, row.c.to_native());
    checksum = update_f64(checksum, row.v.to_native());
    checksum = update_f64(checksum, row.quote_v.to_native());
    checksum = update_f64(checksum, row.taker_known_v.to_native());
    checksum = update_f64(checksum, row.taker_signed_v.to_native());
    checksum = update_f64(checksum, row.taker_known_quote_v.to_native());
    checksum = update_f64(checksum, row.taker_signed_quote_v.to_native());
    checksum = update_i64(checksum, row.taker_known_n.to_native());
    checksum = update_i64(checksum, row.taker_signed_n.to_native());
    checksum = update_f64(checksum, row.vw.to_native());
    checksum = update_i64(checksum, row.n.to_native());
    checksum = update_i64(checksum, row.age_ms.to_native());
    checksum = update_u64(checksum, row.presence_bits.to_native());
    checksum
}

pub struct BarsV1NoMetadata;

impl BarsV1NoMetadata {
    pub const SCHEMA_ID: u32 = NO_METADATA_SCHEMA_ID;
    pub const SCHEMA_VERSION: u16 = NO_METADATA_SCHEMA_VERSION;
    pub const SCHEMA_HASH: u64 = NO_METADATA_GENERATED_SCHEMA_HASH;
    pub const TRANSPORT_NAME: &'static str = NO_METADATA_TRANSPORT_NAME;

    pub fn header_spec() -> SchemaHeaderSpec {
        NO_METADATA_SCHEMA_HEADER
    }

    pub fn encode(
        rows: &[MathildeBarRowV1NoMetadata],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        Self::encode_owned(rows.to_vec(), max_response_bytes)
    }

    pub fn encode_owned(
        rows: Vec<MathildeBarRowV1NoMetadata>,
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        no_metadata_validate_rows(&rows)?;
        let row_count = rows.len();
        let payload = MathildeTransportResponseV1PayloadNoMetadata {
            schema_version: NO_METADATA_SCHEMA_VERSION_VALUE,
            rows,
        };
        let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        let payload_len = payload_bytes.len();
        let total_len =
            HEADER_LEN
                .checked_add(payload_len)
                .ok_or(TransportError::ResponseTooLarge {
                    observed: usize::MAX,
                    cap: max_response_bytes,
                })?;
        if total_len > max_response_bytes {
            return Err(TransportError::ResponseTooLarge {
                observed: total_len,
                cap: max_response_bytes,
            });
        }
        let header = TransportHeader::new_with_schema(
            Self::header_spec(),
            row_count as u64,
            payload_len as u64,
            fnv1a64(&payload_bytes),
        );
        let mut header_bytes = [0_u8; HEADER_LEN];
        encode_header(&header, &mut header_bytes);
        let mut out = Vec::with_capacity(total_len);
        out.extend_from_slice(&header_bytes);
        out.extend_from_slice(&payload_bytes);
        Ok(out)
    }

    pub fn access(bytes: &[u8]) -> Result<BarsV1NoMetadataView<'_>> {
        Ok(BarsV1NoMetadataView {
            archived: Self::access_archived(bytes)?,
        })
    }

    pub(crate) fn access_archived(
        bytes: &[u8],
    ) -> Result<&ArchivedMathildeTransportResponseV1PayloadNoMetadata> {
        let (header, payload) = decode_payload(bytes, Self::header_spec())?;
        let archived = rkyv::access::<
            ArchivedMathildeTransportResponseV1PayloadNoMetadata,
            RkyvError,
        >(payload)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        no_metadata_validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    /// Returns an archived payload view for immutable bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for this schema and then stored or transported without mutation.
    pub unsafe fn access_archived_trusted_unchecked(
        bytes: &[u8],
    ) -> Result<&ArchivedMathildeTransportResponseV1PayloadNoMetadata> {
        let header = decode_header(bytes)?;
        let payload = trusted_payload_for_schema(bytes, Self::header_spec())?;
        let archived = unsafe {
            rkyv::access_unchecked::<ArchivedMathildeTransportResponseV1PayloadNoMetadata>(payload)
        };
        no_metadata_validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    pub fn inspect(bytes: &[u8]) -> Result<BinaryInspection> {
        no_metadata_inspect_archived_rows(Self::access_archived(bytes)?)
    }
}

impl MbtSchema for BarsV1NoMetadata {
    type Row = MathildeBarRowV1NoMetadata;
    type View<'a> = BarsV1NoMetadataView<'a>;

    fn encode_rows(rows: &[Self::Row], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode(rows, max_response_bytes)
    }
    fn encode_owned_rows(rows: Vec<Self::Row>, max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows, max_response_bytes)
    }
    fn access_view(bytes: &[u8]) -> Result<Self::View<'_>> {
        Self::access(bytes)
    }
    fn inspect_bytes(bytes: &[u8]) -> Result<BinaryInspection> {
        Self::inspect(bytes)
    }
}

pub struct BarsV1NoMetadataView<'a> {
    archived: &'a ArchivedMathildeTransportResponseV1PayloadNoMetadata,
}

impl<'a> BarsV1NoMetadataView<'a> {
    pub fn len(&self) -> usize {
        self.archived.rows.len()
    }
    pub fn is_empty(&self) -> bool {
        self.archived.rows.is_empty()
    }
    pub fn rows(&self) -> BarsV1NoMetadataRows<'a> {
        BarsV1NoMetadataRows {
            inner: self.archived.rows.iter(),
        }
    }
}

pub struct BarsV1NoMetadataRows<'a> {
    inner: core::slice::Iter<'a, <MathildeBarRowV1NoMetadata as Archive>::Archived>,
}

impl<'a> Iterator for BarsV1NoMetadataRows<'a> {
    type Item = ArchivedBarsV1NoMetadataRow<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        self.inner
            .next()
            .map(|row| ArchivedBarsV1NoMetadataRow { row })
    }
}

pub struct ArchivedBarsV1NoMetadataRow<'a> {
    row: &'a <MathildeBarRowV1NoMetadata as Archive>::Archived,
}

impl<'a> ArchivedBarsV1NoMetadataRow<'a> {
    pub fn schema_version(&self) -> u16 {
        self.row.schema_version.to_native()
    }
    pub fn pair_ordinal(&self) -> u16 {
        self.row.pair_ordinal.to_native()
    }
    pub fn pair(&self) -> Result<&'static str> {
        pair_symbol(self.row.pair_ordinal.to_native())
    }
    pub fn tf_ordinal(&self) -> u16 {
        self.row.tf_ordinal.to_native()
    }
    pub fn tf(&self) -> Result<&'static str> {
        tf_symbol(self.row.tf_ordinal.to_native())
    }
    pub fn open_ms(&self) -> i64 {
        self.row.open_ms.to_native()
    }
    pub fn close_ms(&self) -> i64 {
        self.row.close_ms.to_native()
    }
    pub fn o(&self) -> f64 {
        self.row.o.to_native()
    }
    pub fn h(&self) -> f64 {
        self.row.h.to_native()
    }
    pub fn l(&self) -> f64 {
        self.row.l.to_native()
    }
    pub fn c(&self) -> f64 {
        self.row.c.to_native()
    }
    pub fn v(&self) -> f64 {
        self.row.v.to_native()
    }
    pub fn quote_v(&self) -> f64 {
        self.row.quote_v.to_native()
    }
    pub fn taker_known_v(&self) -> f64 {
        self.row.taker_known_v.to_native()
    }
    pub fn taker_signed_v(&self) -> f64 {
        self.row.taker_signed_v.to_native()
    }
    pub fn taker_known_quote_v(&self) -> f64 {
        self.row.taker_known_quote_v.to_native()
    }
    pub fn taker_signed_quote_v(&self) -> f64 {
        self.row.taker_signed_quote_v.to_native()
    }
    pub fn taker_known_n(&self) -> i64 {
        self.row.taker_known_n.to_native()
    }
    pub fn taker_signed_n(&self) -> i64 {
        self.row.taker_signed_n.to_native()
    }
    pub fn has_vw(&self) -> bool {
        self.row.presence_bits.to_native() & NO_METADATA_PRESENCE_VW != 0
    }
    pub fn vw(&self) -> f64 {
        self.row.vw.to_native()
    }
    pub fn has_n(&self) -> bool {
        self.row.presence_bits.to_native() & NO_METADATA_PRESENCE_N != 0
    }
    pub fn n(&self) -> i64 {
        self.row.n.to_native()
    }
    pub fn has_age_ms(&self) -> bool {
        self.row.presence_bits.to_native() & NO_METADATA_PRESENCE_AGE_MS != 0
    }
    pub fn age_ms(&self) -> i64 {
        self.row.age_ms.to_native()
    }
    pub fn presence_bits(&self) -> u64 {
        self.row.presence_bits.to_native()
    }
}

fn no_metadata_validate_archived_payload(
    archived: &ArchivedMathildeTransportResponseV1PayloadNoMetadata,
    expected_rows: u64,
) -> Result<()> {
    if archived.schema_version.to_native() != NO_METADATA_SCHEMA_VERSION_VALUE {
        return Err(TransportError::SchemaVersionMismatch {
            observed: archived.schema_version.to_native(),
            expected: NO_METADATA_SCHEMA_VERSION_VALUE,
        });
    }
    let expected = usize::try_from(expected_rows)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
    if archived.rows.len() != expected {
        return Err(TransportError::RowCountMismatch {
            observed: archived.rows.len(),
            expected: expected_rows,
        });
    }
    Ok(())
}

fn no_metadata_inspect_archived_rows(
    archived: &ArchivedMathildeTransportResponseV1PayloadNoMetadata,
) -> Result<BinaryInspection> {
    let mut semantic_checksum = fnv1a64("mathilde.bar.v1.no_metadata".as_bytes());
    let mut minimal_projection_checksum = semantic_checksum;
    for row in archived.rows.iter() {
        semantic_checksum = no_metadata_checksum_archived_row(semantic_checksum, row);
        minimal_projection_checksum =
            no_metadata_checksum_archived_row(minimal_projection_checksum, row);
    }
    Ok(BinaryInspection {
        row_count: archived.rows.len(),
        semantic_checksum,
        minimal_projection_checksum,
    })
}
#[derive(Archive, RkyvSerialize)]
struct BarsV1NoMetadataProjectionPayloadRef<'a> {
    schema_version: u16,
    rows: BarsV1NoMetadataProjectionRowsRef<'a>,
}

struct BarsV1NoMetadataProjectionRowsRef<'a> {
    rows: &'a ArchivedVec<<MathildeBarRowV1 as Archive>::Archived>,
}

impl<'a> Archive for BarsV1NoMetadataProjectionRowsRef<'a> {
    type Archived = ArchivedVec<<BarsV1NoMetadataProjectionRowRef as Archive>::Archived>;
    type Resolver = VecResolver;
    fn resolve(&self, resolver: Self::Resolver, out: Place<Self::Archived>) {
        ArchivedVec::resolve_from_len(self.rows.len(), resolver, out);
    }
}

impl<'a, S> RkyvSerialize<S> for BarsV1NoMetadataProjectionRowsRef<'a>
where
    S: Fallible + Allocator + Writer + ?Sized,
    S::Error: Source,
{
    fn serialize(&self, serializer: &mut S) -> std::result::Result<Self::Resolver, S::Error> {
        ArchivedVec::serialize_from_iter::<BarsV1NoMetadataProjectionRowRef, _, _>(
            BarsV1NoMetadataProjectionRowsIter {
                inner: self.rows.as_slice().iter(),
            },
            serializer,
        )
    }
}

#[derive(Clone)]
struct BarsV1NoMetadataProjectionRowsIter<'a> {
    inner: core::slice::Iter<'a, <MathildeBarRowV1 as Archive>::Archived>,
}

impl<'a> Iterator for BarsV1NoMetadataProjectionRowsIter<'a> {
    type Item = BarsV1NoMetadataProjectionRowRef;
    fn next(&mut self) -> Option<Self::Item> {
        let source = self.inner.next()?;
        let mut presence_bits = 0_u64;
        if source.presence_bits.to_native() & PRESENCE_VW != 0 {
            presence_bits |= NO_METADATA_PRESENCE_VW;
        }
        if source.presence_bits.to_native() & PRESENCE_N != 0 {
            presence_bits |= NO_METADATA_PRESENCE_N;
        }
        if source.presence_bits.to_native() & PRESENCE_AGE_MS != 0 {
            presence_bits |= NO_METADATA_PRESENCE_AGE_MS;
        }
        Some(BarsV1NoMetadataProjectionRowRef {
            schema_version: source.schema_version.to_native(),
            pair_ordinal: source.pair_ordinal.to_native(),
            tf_ordinal: source.tf_ordinal.to_native(),
            open_ms: source.open_ms.to_native(),
            close_ms: source.close_ms.to_native(),
            o: source.o.to_native(),
            h: source.h.to_native(),
            l: source.l.to_native(),
            c: source.c.to_native(),
            v: source.v.to_native(),
            quote_v: source.quote_v.to_native(),
            taker_known_v: source.taker_known_v.to_native(),
            taker_signed_v: source.taker_signed_v.to_native(),
            taker_known_quote_v: source.taker_known_quote_v.to_native(),
            taker_signed_quote_v: source.taker_signed_quote_v.to_native(),
            taker_known_n: source.taker_known_n.to_native(),
            taker_signed_n: source.taker_signed_n.to_native(),
            vw: source.vw.to_native(),
            n: source.n.to_native(),
            age_ms: source.age_ms.to_native(),
            presence_bits,
        })
    }
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.inner.size_hint()
    }
}

impl<'a> ExactSizeIterator for BarsV1NoMetadataProjectionRowsIter<'a> {
    fn len(&self) -> usize {
        self.inner.len()
    }
}

#[derive(Archive, RkyvSerialize)]
struct BarsV1NoMetadataProjectionRowRef {
    schema_version: u16,
    pair_ordinal: u16,
    tf_ordinal: u16,
    open_ms: i64,
    close_ms: i64,
    o: f64,
    h: f64,
    l: f64,
    c: f64,
    v: f64,
    quote_v: f64,
    taker_known_v: f64,
    taker_signed_v: f64,
    taker_known_quote_v: f64,
    taker_signed_quote_v: f64,
    taker_known_n: i64,
    taker_signed_n: i64,
    vw: f64,
    n: i64,
    age_ms: i64,
    presence_bits: u64,
}

const _: fn(&ArchivedMathildeTransportResponseV1Payload, usize) -> Result<Vec<u8>> =
    project_no_metadata_archived_direct;

impl BarsV1 {
    pub fn project_no_metadata(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        project_no_metadata_archived_direct(archived, max_response_bytes)
    }

    /// Projects immutable source bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for the source schema and then stored or transported without mutation.
    pub unsafe fn project_no_metadata_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        project_no_metadata_archived_direct(archived, max_response_bytes)
    }
}

fn project_no_metadata_archived_direct(
    archived: &ArchivedMathildeTransportResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let row_count = archived.rows.len() as u64;
    let payload = BarsV1NoMetadataProjectionPayloadRef {
        schema_version: NO_METADATA_SCHEMA_VERSION_VALUE,
        rows: BarsV1NoMetadataProjectionRowsRef {
            rows: &archived.rows,
        },
    };
    let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
        .map_err(|_err| TransportError::MalformedArchive(String::new()))?;
    let payload_len = payload_bytes.len();
    let total_len =
        HEADER_LEN
            .checked_add(payload_len)
            .ok_or(TransportError::ResponseTooLarge {
                observed: usize::MAX,
                cap: max_response_bytes,
            })?;
    if total_len > max_response_bytes {
        return Err(TransportError::ResponseTooLarge {
            observed: total_len,
            cap: max_response_bytes,
        });
    }
    let header = TransportHeader::new_with_schema(
        BarsV1NoMetadata::header_spec(),
        row_count,
        payload_len as u64,
        fnv1a64(&payload_bytes),
    );
    let mut header_bytes = [0_u8; HEADER_LEN];
    encode_header(&header, &mut header_bytes);
    let mut out = Vec::with_capacity(total_len);
    out.extend_from_slice(&header_bytes);
    out.extend_from_slice(&payload_bytes);
    Ok(out)
}

const OHLCV_ONLY_SCHEMA_ID: u32 = 1;
const OHLCV_ONLY_SCHEMA_VERSION_VALUE: u16 = 1;
const OHLCV_ONLY_SCHEMA_VERSION: u16 = OHLCV_ONLY_SCHEMA_VERSION_VALUE;
const OHLCV_ONLY_GENERATED_SCHEMA_HASH: u64 = 792323260406987672;
const OHLCV_ONLY_TRANSPORT_NAME: &str = "mathilde.bar.v1.ohlcv_only";
const OHLCV_ONLY_SCHEMA_HEADER: SchemaHeaderSpec = SchemaHeaderSpec {
    schema_id: OHLCV_ONLY_SCHEMA_ID,
    schema_version: OHLCV_ONLY_SCHEMA_VERSION,
    schema_hash: OHLCV_ONLY_GENERATED_SCHEMA_HASH,
};

#[derive(Clone, Archive, RkyvSerialize)]
pub struct MathildeTransportResponseV1PayloadOhlcvOnly {
    pub schema_version: u16,
    pub rows: Vec<MathildeBarRowV1OhlcvOnly>,
}

#[derive(Clone, Archive, RkyvSerialize)]
pub struct MathildeBarRowV1OhlcvOnly {
    pub schema_version: u16,
    pub pair_ordinal: u16,
    pub tf_ordinal: u16,
    pub open_ms: i64,
    pub close_ms: i64,
    pub o: f64,
    pub h: f64,
    pub l: f64,
    pub c: f64,
    pub v: f64,
}

fn ohlcv_only_validate_rows(rows: &[MathildeBarRowV1OhlcvOnly]) -> Result<()> {
    let mut previous = None;
    for row in rows {
        ohlcv_only_validate_row(row, previous)?;
        previous = Some(row);
    }
    Ok(())
}

fn ohlcv_only_validate_row(
    row: &MathildeBarRowV1OhlcvOnly,
    previous: Option<&MathildeBarRowV1OhlcvOnly>,
) -> Result<()> {
    if row.schema_version != 1 {
        return Err(TransportError::SchemaVersionMismatch {
            observed: row.schema_version,
            expected: 1,
        });
    }
    pair_symbol(row.pair_ordinal)?;
    tf_symbol(row.tf_ordinal)?;
    validate_finite_f64("o", row.o)?;
    validate_finite_f64("h", row.h)?;
    validate_finite_f64("l", row.l)?;
    validate_finite_f64("c", row.c)?;
    validate_finite_f64("v", row.v)?;
    if previous.is_some_and(|prev| {
        (row.pair_ordinal, row.tf_ordinal, row.close_ms)
            < (prev.pair_ordinal, prev.tf_ordinal, prev.close_ms)
    }) {
        return Err(TransportError::InvalidTimeGrid(
            "key order regression".to_string(),
        ));
    }
    Ok(())
}

fn ohlcv_only_checksum_archived_row(
    mut checksum: u64,
    row: &<MathildeBarRowV1OhlcvOnly as Archive>::Archived,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.pair_ordinal.to_native());
    checksum = update_u16(checksum, row.tf_ordinal.to_native());
    checksum = update_i64(checksum, row.open_ms.to_native());
    checksum = update_i64(checksum, row.close_ms.to_native());
    checksum = update_f64(checksum, row.o.to_native());
    checksum = update_f64(checksum, row.h.to_native());
    checksum = update_f64(checksum, row.l.to_native());
    checksum = update_f64(checksum, row.c.to_native());
    checksum = update_f64(checksum, row.v.to_native());
    checksum
}

pub struct BarsV1OhlcvOnly;

impl BarsV1OhlcvOnly {
    pub const SCHEMA_ID: u32 = OHLCV_ONLY_SCHEMA_ID;
    pub const SCHEMA_VERSION: u16 = OHLCV_ONLY_SCHEMA_VERSION;
    pub const SCHEMA_HASH: u64 = OHLCV_ONLY_GENERATED_SCHEMA_HASH;
    pub const TRANSPORT_NAME: &'static str = OHLCV_ONLY_TRANSPORT_NAME;

    pub fn header_spec() -> SchemaHeaderSpec {
        OHLCV_ONLY_SCHEMA_HEADER
    }

    pub fn encode(
        rows: &[MathildeBarRowV1OhlcvOnly],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        Self::encode_owned(rows.to_vec(), max_response_bytes)
    }

    pub fn encode_owned(
        rows: Vec<MathildeBarRowV1OhlcvOnly>,
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        ohlcv_only_validate_rows(&rows)?;
        let row_count = rows.len();
        let payload = MathildeTransportResponseV1PayloadOhlcvOnly {
            schema_version: OHLCV_ONLY_SCHEMA_VERSION_VALUE,
            rows,
        };
        let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        let payload_len = payload_bytes.len();
        let total_len =
            HEADER_LEN
                .checked_add(payload_len)
                .ok_or(TransportError::ResponseTooLarge {
                    observed: usize::MAX,
                    cap: max_response_bytes,
                })?;
        if total_len > max_response_bytes {
            return Err(TransportError::ResponseTooLarge {
                observed: total_len,
                cap: max_response_bytes,
            });
        }
        let header = TransportHeader::new_with_schema(
            Self::header_spec(),
            row_count as u64,
            payload_len as u64,
            fnv1a64(&payload_bytes),
        );
        let mut header_bytes = [0_u8; HEADER_LEN];
        encode_header(&header, &mut header_bytes);
        let mut out = Vec::with_capacity(total_len);
        out.extend_from_slice(&header_bytes);
        out.extend_from_slice(&payload_bytes);
        Ok(out)
    }

    pub fn access(bytes: &[u8]) -> Result<BarsV1OhlcvOnlyView<'_>> {
        Ok(BarsV1OhlcvOnlyView {
            archived: Self::access_archived(bytes)?,
        })
    }

    pub(crate) fn access_archived(
        bytes: &[u8],
    ) -> Result<&ArchivedMathildeTransportResponseV1PayloadOhlcvOnly> {
        let (header, payload) = decode_payload(bytes, Self::header_spec())?;
        let archived =
            rkyv::access::<ArchivedMathildeTransportResponseV1PayloadOhlcvOnly, RkyvError>(payload)
                .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        ohlcv_only_validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    /// Returns an archived payload view for immutable bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for this schema and then stored or transported without mutation.
    pub unsafe fn access_archived_trusted_unchecked(
        bytes: &[u8],
    ) -> Result<&ArchivedMathildeTransportResponseV1PayloadOhlcvOnly> {
        let header = decode_header(bytes)?;
        let payload = trusted_payload_for_schema(bytes, Self::header_spec())?;
        let archived = unsafe {
            rkyv::access_unchecked::<ArchivedMathildeTransportResponseV1PayloadOhlcvOnly>(payload)
        };
        ohlcv_only_validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    pub fn inspect(bytes: &[u8]) -> Result<BinaryInspection> {
        ohlcv_only_inspect_archived_rows(Self::access_archived(bytes)?)
    }
}

impl MbtSchema for BarsV1OhlcvOnly {
    type Row = MathildeBarRowV1OhlcvOnly;
    type View<'a> = BarsV1OhlcvOnlyView<'a>;

    fn encode_rows(rows: &[Self::Row], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode(rows, max_response_bytes)
    }
    fn encode_owned_rows(rows: Vec<Self::Row>, max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows, max_response_bytes)
    }
    fn access_view(bytes: &[u8]) -> Result<Self::View<'_>> {
        Self::access(bytes)
    }
    fn inspect_bytes(bytes: &[u8]) -> Result<BinaryInspection> {
        Self::inspect(bytes)
    }
}

pub struct BarsV1OhlcvOnlyView<'a> {
    archived: &'a ArchivedMathildeTransportResponseV1PayloadOhlcvOnly,
}

impl<'a> BarsV1OhlcvOnlyView<'a> {
    pub fn len(&self) -> usize {
        self.archived.rows.len()
    }
    pub fn is_empty(&self) -> bool {
        self.archived.rows.is_empty()
    }
    pub fn rows(&self) -> BarsV1OhlcvOnlyRows<'a> {
        BarsV1OhlcvOnlyRows {
            inner: self.archived.rows.iter(),
        }
    }
}

pub struct BarsV1OhlcvOnlyRows<'a> {
    inner: core::slice::Iter<'a, <MathildeBarRowV1OhlcvOnly as Archive>::Archived>,
}

impl<'a> Iterator for BarsV1OhlcvOnlyRows<'a> {
    type Item = ArchivedBarsV1OhlcvOnlyRow<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        self.inner
            .next()
            .map(|row| ArchivedBarsV1OhlcvOnlyRow { row })
    }
}

pub struct ArchivedBarsV1OhlcvOnlyRow<'a> {
    row: &'a <MathildeBarRowV1OhlcvOnly as Archive>::Archived,
}

impl<'a> ArchivedBarsV1OhlcvOnlyRow<'a> {
    pub fn schema_version(&self) -> u16 {
        self.row.schema_version.to_native()
    }
    pub fn pair_ordinal(&self) -> u16 {
        self.row.pair_ordinal.to_native()
    }
    pub fn pair(&self) -> Result<&'static str> {
        pair_symbol(self.row.pair_ordinal.to_native())
    }
    pub fn tf_ordinal(&self) -> u16 {
        self.row.tf_ordinal.to_native()
    }
    pub fn tf(&self) -> Result<&'static str> {
        tf_symbol(self.row.tf_ordinal.to_native())
    }
    pub fn open_ms(&self) -> i64 {
        self.row.open_ms.to_native()
    }
    pub fn close_ms(&self) -> i64 {
        self.row.close_ms.to_native()
    }
    pub fn o(&self) -> f64 {
        self.row.o.to_native()
    }
    pub fn h(&self) -> f64 {
        self.row.h.to_native()
    }
    pub fn l(&self) -> f64 {
        self.row.l.to_native()
    }
    pub fn c(&self) -> f64 {
        self.row.c.to_native()
    }
    pub fn v(&self) -> f64 {
        self.row.v.to_native()
    }
}

fn ohlcv_only_validate_archived_payload(
    archived: &ArchivedMathildeTransportResponseV1PayloadOhlcvOnly,
    expected_rows: u64,
) -> Result<()> {
    if archived.schema_version.to_native() != OHLCV_ONLY_SCHEMA_VERSION_VALUE {
        return Err(TransportError::SchemaVersionMismatch {
            observed: archived.schema_version.to_native(),
            expected: OHLCV_ONLY_SCHEMA_VERSION_VALUE,
        });
    }
    let expected = usize::try_from(expected_rows)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
    if archived.rows.len() != expected {
        return Err(TransportError::RowCountMismatch {
            observed: archived.rows.len(),
            expected: expected_rows,
        });
    }
    Ok(())
}

fn ohlcv_only_inspect_archived_rows(
    archived: &ArchivedMathildeTransportResponseV1PayloadOhlcvOnly,
) -> Result<BinaryInspection> {
    let mut semantic_checksum = fnv1a64("mathilde.bar.v1.ohlcv_only".as_bytes());
    let mut minimal_projection_checksum = semantic_checksum;
    for row in archived.rows.iter() {
        semantic_checksum = ohlcv_only_checksum_archived_row(semantic_checksum, row);
        minimal_projection_checksum =
            ohlcv_only_checksum_archived_row(minimal_projection_checksum, row);
    }
    Ok(BinaryInspection {
        row_count: archived.rows.len(),
        semantic_checksum,
        minimal_projection_checksum,
    })
}
#[derive(Archive, RkyvSerialize)]
struct BarsV1OhlcvOnlyProjectionPayloadRef<'a> {
    schema_version: u16,
    rows: BarsV1OhlcvOnlyProjectionRowsRef<'a>,
}

struct BarsV1OhlcvOnlyProjectionRowsRef<'a> {
    rows: &'a ArchivedVec<<MathildeBarRowV1 as Archive>::Archived>,
}

impl<'a> Archive for BarsV1OhlcvOnlyProjectionRowsRef<'a> {
    type Archived = ArchivedVec<<BarsV1OhlcvOnlyProjectionRowRef as Archive>::Archived>;
    type Resolver = VecResolver;
    fn resolve(&self, resolver: Self::Resolver, out: Place<Self::Archived>) {
        ArchivedVec::resolve_from_len(self.rows.len(), resolver, out);
    }
}

impl<'a, S> RkyvSerialize<S> for BarsV1OhlcvOnlyProjectionRowsRef<'a>
where
    S: Fallible + Allocator + Writer + ?Sized,
    S::Error: Source,
{
    fn serialize(&self, serializer: &mut S) -> std::result::Result<Self::Resolver, S::Error> {
        ArchivedVec::serialize_from_iter::<BarsV1OhlcvOnlyProjectionRowRef, _, _>(
            BarsV1OhlcvOnlyProjectionRowsIter {
                inner: self.rows.as_slice().iter(),
            },
            serializer,
        )
    }
}

#[derive(Clone)]
struct BarsV1OhlcvOnlyProjectionRowsIter<'a> {
    inner: core::slice::Iter<'a, <MathildeBarRowV1 as Archive>::Archived>,
}

impl<'a> Iterator for BarsV1OhlcvOnlyProjectionRowsIter<'a> {
    type Item = BarsV1OhlcvOnlyProjectionRowRef;
    fn next(&mut self) -> Option<Self::Item> {
        let source = self.inner.next()?;
        Some(BarsV1OhlcvOnlyProjectionRowRef {
            schema_version: source.schema_version.to_native(),
            pair_ordinal: source.pair_ordinal.to_native(),
            tf_ordinal: source.tf_ordinal.to_native(),
            open_ms: source.open_ms.to_native(),
            close_ms: source.close_ms.to_native(),
            o: source.o.to_native(),
            h: source.h.to_native(),
            l: source.l.to_native(),
            c: source.c.to_native(),
            v: source.v.to_native(),
        })
    }
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.inner.size_hint()
    }
}

impl<'a> ExactSizeIterator for BarsV1OhlcvOnlyProjectionRowsIter<'a> {
    fn len(&self) -> usize {
        self.inner.len()
    }
}

#[derive(Archive, RkyvSerialize)]
struct BarsV1OhlcvOnlyProjectionRowRef {
    schema_version: u16,
    pair_ordinal: u16,
    tf_ordinal: u16,
    open_ms: i64,
    close_ms: i64,
    o: f64,
    h: f64,
    l: f64,
    c: f64,
    v: f64,
}

const _: fn(&ArchivedMathildeTransportResponseV1Payload, usize) -> Result<Vec<u8>> =
    project_ohlcv_only_archived_direct;

impl BarsV1 {
    pub fn project_ohlcv_only(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        project_ohlcv_only_archived_direct(archived, max_response_bytes)
    }

    /// Projects immutable source bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for the source schema and then stored or transported without mutation.
    pub unsafe fn project_ohlcv_only_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        project_ohlcv_only_archived_direct(archived, max_response_bytes)
    }
}

fn project_ohlcv_only_archived_direct(
    archived: &ArchivedMathildeTransportResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let row_count = archived.rows.len() as u64;
    let payload = BarsV1OhlcvOnlyProjectionPayloadRef {
        schema_version: OHLCV_ONLY_SCHEMA_VERSION_VALUE,
        rows: BarsV1OhlcvOnlyProjectionRowsRef {
            rows: &archived.rows,
        },
    };
    let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
        .map_err(|_err| TransportError::MalformedArchive(String::new()))?;
    let payload_len = payload_bytes.len();
    let total_len =
        HEADER_LEN
            .checked_add(payload_len)
            .ok_or(TransportError::ResponseTooLarge {
                observed: usize::MAX,
                cap: max_response_bytes,
            })?;
    if total_len > max_response_bytes {
        return Err(TransportError::ResponseTooLarge {
            observed: total_len,
            cap: max_response_bytes,
        });
    }
    let header = TransportHeader::new_with_schema(
        BarsV1OhlcvOnly::header_spec(),
        row_count,
        payload_len as u64,
        fnv1a64(&payload_bytes),
    );
    let mut header_bytes = [0_u8; HEADER_LEN];
    encode_header(&header, &mut header_bytes);
    let mut out = Vec::with_capacity(total_len);
    out.extend_from_slice(&header_bytes);
    out.extend_from_slice(&payload_bytes);
    Ok(out)
}
