// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=1 schema_version=1 schema_hash=6061383958499356843

use crate::bars_v1::*;
use crate::bars_v1_transponding::*;
use metamorphic_binary_transport_adapter_arrow_ipc::{
    ArrowArrayRef, ArrowDataType, ArrowField, ArrowRecordBatch, ArrowSchema, field_metadata,
    record_batch, write_ipc_stream,
};
use metamorphic_binary_transport_core::error::Result;
use metamorphic_binary_transport_metamorphose::{
    ArrowIpcMetamorphoseSchema, runtime::TrustedUnchecked,
};

use std::sync::Arc;

impl BarsV1 {
    pub fn metamorphose_arrow_ipc(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        let batch = Self::transpond_archived(archived, max_response_bytes)?;
        let arrow = arrow_record_batch(batch, max_response_bytes)?;
        write_ipc_stream(&arrow, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into Arrow IPC.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_arrow_ipc_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        let batch = Self::transpond_archived(archived, max_response_bytes)?;
        let arrow = arrow_record_batch(batch, max_response_bytes)?;
        write_ipc_stream(&arrow, max_response_bytes)
    }
}

impl ArrowIpcMetamorphoseSchema for BarsV1 {
    fn metamorphose_arrow_ipc(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_arrow_ipc(bytes, max_response_bytes)
    }
    fn metamorphose_arrow_ipc_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_arrow_ipc_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn arrow_record_batch(
    batch: BarsV1ColumnBatch,
    max_response_bytes: usize,
) -> Result<ArrowRecordBatch> {
    let schema =
        Arc::new(ArrowSchema::new(vec![
            ArrowField::new("schema_version", ArrowDataType::UInt16, false).with_metadata(
                field_metadata("schema_version", "schema_version", None, None),
            ),
            ArrowField::new("pair", ArrowDataType::UInt16, false).with_metadata(field_metadata(
                "pair",
                "pair_ordinal",
                Some("pair"),
                None,
            )),
            ArrowField::new("tf", ArrowDataType::UInt16, false).with_metadata(field_metadata(
                "tf",
                "tf_ordinal",
                Some("timeframe"),
                None,
            )),
            ArrowField::new("open_ms", ArrowDataType::Int64, false)
                .with_metadata(field_metadata("open_ms", "open_ms", None, None)),
            ArrowField::new("close_ms", ArrowDataType::Int64, false)
                .with_metadata(field_metadata("close_ms", "close_ms", None, None)),
            ArrowField::new("o", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("o", "o", None, None)),
            ArrowField::new("h", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("h", "h", None, None)),
            ArrowField::new("l", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("l", "l", None, None)),
            ArrowField::new("c", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("c", "c", None, None)),
            ArrowField::new("v", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("v", "v", None, None)),
            ArrowField::new("quote_v", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("quote_v", "quote_v", None, None)),
            ArrowField::new("taker_known_v", ArrowDataType::Float64, false)
                .with_metadata(field_metadata("taker_known_v", "taker_known_v", None, None)),
            ArrowField::new("taker_signed_v", ArrowDataType::Float64, false).with_metadata(
                field_metadata("taker_signed_v", "taker_signed_v", None, None),
            ),
            ArrowField::new("taker_known_quote_v", ArrowDataType::Float64, false).with_metadata(
                field_metadata("taker_known_quote_v", "taker_known_quote_v", None, None),
            ),
            ArrowField::new("taker_signed_quote_v", ArrowDataType::Float64, false).with_metadata(
                field_metadata("taker_signed_quote_v", "taker_signed_quote_v", None, None),
            ),
            ArrowField::new("taker_known_n", ArrowDataType::Int64, false)
                .with_metadata(field_metadata("taker_known_n", "taker_known_n", None, None)),
            ArrowField::new("taker_signed_n", ArrowDataType::Int64, false).with_metadata(
                field_metadata("taker_signed_n", "taker_signed_n", None, None),
            ),
            ArrowField::new("vw", ArrowDataType::Float64, true)
                .with_metadata(field_metadata("vw", "vw", None, None)),
            ArrowField::new("n", ArrowDataType::Int64, true)
                .with_metadata(field_metadata("n", "n", None, None)),
            ArrowField::new("metadata.source", ArrowDataType::UInt16, false).with_metadata(
                field_metadata("metadata.source", "source_ordinal", Some("source"), None),
            ),
            ArrowField::new("metadata.process", ArrowDataType::UInt16, true).with_metadata(
                field_metadata("metadata.process", "process_ordinal", Some("process"), None),
            ),
            ArrowField::new("metadata.venues_expected", ArrowDataType::UInt64, false)
                .with_metadata(field_metadata(
                    "metadata.venues_expected",
                    "venues_expected_mask",
                    None,
                    Some("venue"),
                )),
            ArrowField::new("metadata.venues_with_trades", ArrowDataType::UInt64, false)
                .with_metadata(field_metadata(
                    "metadata.venues_with_trades",
                    "venues_with_trades_mask",
                    None,
                    Some("venue"),
                )),
            ArrowField::new("metadata.ingested_at_ms", ArrowDataType::Int64, true).with_metadata(
                field_metadata("metadata.ingested_at_ms", "ingested_at_ms", None, None),
            ),
            ArrowField::new("metadata.target_ingested_at_ms", ArrowDataType::Int64, true)
                .with_metadata(field_metadata(
                    "metadata.target_ingested_at_ms",
                    "target_ingested_at_ms",
                    None,
                    None,
                )),
            ArrowField::new("metadata.built_at_ms", ArrowDataType::Int64, true).with_metadata(
                field_metadata("metadata.built_at_ms", "built_at_ms", None, None),
            ),
            ArrowField::new("metadata.committed_at_ms", ArrowDataType::Int64, true).with_metadata(
                field_metadata("metadata.committed_at_ms", "committed_at_ms", None, None),
            ),
            ArrowField::new("metadata.harmonized_at_ms", ArrowDataType::Int64, true).with_metadata(
                field_metadata("metadata.harmonized_at_ms", "harmonized_at_ms", None, None),
            ),
            ArrowField::new("metadata.recomputed_at_ms", ArrowDataType::Int64, true).with_metadata(
                field_metadata("metadata.recomputed_at_ms", "recomputed_at_ms", None, None),
            ),
            ArrowField::new("metadata.recomputed_reason", ArrowDataType::UInt16, true)
                .with_metadata(field_metadata(
                    "metadata.recomputed_reason",
                    "recomputed_reason_ordinal",
                    Some("recomputed_reason"),
                    None,
                )),
            ArrowField::new("metadata.covered_1m_count", ArrowDataType::Int64, true).with_metadata(
                field_metadata("metadata.covered_1m_count", "covered_1m_count", None, None),
            ),
            ArrowField::new("metadata.expected_1m_count", ArrowDataType::Int64, true)
                .with_metadata(field_metadata(
                    "metadata.expected_1m_count",
                    "expected_1m_count",
                    None,
                    None,
                )),
            ArrowField::new("metadata.coverage_ratio", ArrowDataType::Float64, true).with_metadata(
                field_metadata("metadata.coverage_ratio", "coverage_ratio", None, None),
            ),
            ArrowField::new(
                "metadata.inputs_source_counts_frontier",
                ArrowDataType::Int64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.inputs_source_counts_frontier",
                "inputs_source_counts_frontier",
                None,
                None,
            )),
            ArrowField::new(
                "metadata.inputs_source_counts_api",
                ArrowDataType::Int64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.inputs_source_counts_api",
                "inputs_source_counts_api",
                None,
                None,
            )),
            ArrowField::new(
                "metadata.inputs_source_counts_synthetic",
                ArrowDataType::Int64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.inputs_source_counts_synthetic",
                "inputs_source_counts_synthetic",
                None,
                None,
            )),
            ArrowField::new(
                "metadata.inputs_source_counts_fix_data",
                ArrowDataType::Int64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.inputs_source_counts_fix_data",
                "inputs_source_counts_fix_data",
                None,
                None,
            )),
            ArrowField::new(
                "metadata.frontier_5s_inputs_coverage_ratio",
                ArrowDataType::Float64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.frontier_5s_inputs_coverage_ratio",
                "frontier_5s_inputs_coverage_ratio",
                None,
                None,
            )),
            ArrowField::new("metadata.frontier_5s_expected", ArrowDataType::Int64, true)
                .with_metadata(field_metadata(
                    "metadata.frontier_5s_expected",
                    "frontier_5s_expected",
                    None,
                    None,
                )),
            ArrowField::new("metadata.frontier_5s_synth_n", ArrowDataType::Int64, true)
                .with_metadata(field_metadata(
                    "metadata.frontier_5s_synth_n",
                    "frontier_5s_synth_n",
                    None,
                    None,
                )),
            ArrowField::new(
                "metadata.frontier_5s_synth_ratio",
                ArrowDataType::Float64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.frontier_5s_synth_ratio",
                "frontier_5s_synth_ratio",
                None,
                None,
            )),
            ArrowField::new("metadata.frontier_5s_trade_n", ArrowDataType::Int64, true)
                .with_metadata(field_metadata(
                    "metadata.frontier_5s_trade_n",
                    "frontier_5s_trade_n",
                    None,
                    None,
                )),
            ArrowField::new(
                "metadata.frontier_5s_trade_ratio",
                ArrowDataType::Float64,
                true,
            )
            .with_metadata(field_metadata(
                "metadata.frontier_5s_trade_ratio",
                "frontier_5s_trade_ratio",
                None,
                None,
            )),
            ArrowField::new("age_ms", ArrowDataType::Int64, true)
                .with_metadata(field_metadata("age_ms", "age_ms", None, None)),
        ]));
    let columns: Vec<ArrowArrayRef> = vec![
        metamorphic_binary_transport_adapter_arrow_ipc::const_u16_array(batch.schema_version)?,
        metamorphic_binary_transport_adapter_arrow_ipc::u16_array(batch.pair_ordinal)?,
        metamorphic_binary_transport_adapter_arrow_ipc::u16_array(batch.tf_ordinal)?,
        metamorphic_binary_transport_adapter_arrow_ipc::i64_array(batch.open_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::i64_array(batch.close_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.o)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.h)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.l)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.c)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.v)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.quote_v)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.taker_known_v)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.taker_signed_v)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.taker_known_quote_v)?,
        metamorphic_binary_transport_adapter_arrow_ipc::f64_array(batch.taker_signed_quote_v)?,
        metamorphic_binary_transport_adapter_arrow_ipc::i64_array(batch.taker_known_n)?,
        metamorphic_binary_transport_adapter_arrow_ipc::i64_array(batch.taker_signed_n)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_f64_array(batch.vw)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.n)?,
        metamorphic_binary_transport_adapter_arrow_ipc::u16_array(batch.source_ordinal)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_u16_array(batch.process_ordinal)?,
        metamorphic_binary_transport_adapter_arrow_ipc::u64_array(batch.venues_expected_mask)?,
        metamorphic_binary_transport_adapter_arrow_ipc::u64_array(batch.venues_with_trades_mask)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.ingested_at_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.target_ingested_at_ms,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.built_at_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.committed_at_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.harmonized_at_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.recomputed_at_ms)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_u16_array(
            batch.recomputed_reason_ordinal,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.covered_1m_count)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.expected_1m_count,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_f64_array(batch.coverage_ratio)?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.inputs_source_counts_frontier,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.inputs_source_counts_api,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.inputs_source_counts_synthetic,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.inputs_source_counts_fix_data,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_f64_array(
            batch.frontier_5s_inputs_coverage_ratio,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.frontier_5s_expected,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.frontier_5s_synth_n,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_f64_array(
            batch.frontier_5s_synth_ratio,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(
            batch.frontier_5s_trade_n,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_f64_array(
            batch.frontier_5s_trade_ratio,
        )?,
        metamorphic_binary_transport_adapter_arrow_ipc::optional_i64_array(batch.age_ms)?,
    ];
    record_batch(schema, columns, max_response_bytes)
}
