// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=1 schema_version=1 schema_hash=6061383958499356843

use crate::bars_v1::*;
use mbt_adapter_csv::CsvWriter;
use mbt_core::error::Result;
use mbt_metamorphose::{CsvMetamorphoseSchema, runtime::TrustedUnchecked};
use rkyv::Archive;

const CSV_HEADER: &[u8] = b"schema_version,pair,tf,open_ms,close_ms,open_utc,close_utc,o,h,l,c,v,quote_v,taker_known_v,taker_signed_v,taker_known_quote_v,taker_signed_quote_v,taker_known_n,taker_signed_n,vw,n,metadata.source,metadata.process,metadata.venues_expected,metadata.venues_with_trades,metadata.ingested_at_ms,metadata.ingested_at_utc,metadata.target_ingested_at_ms,metadata.target_ingested_at_utc,metadata.built_at_ms,metadata.built_at_utc,metadata.committed_at_ms,metadata.committed_at_utc,metadata.harmonized_at_ms,metadata.harmonized_at_utc,metadata.recomputed_at_ms,metadata.recomputed_at_utc,metadata.recomputed_reason,metadata.covered_1m_count,metadata.expected_1m_count,metadata.coverage_ratio,metadata.inputs_source_counts_frontier,metadata.inputs_source_counts_api,metadata.inputs_source_counts_synthetic,metadata.inputs_source_counts_fix_data,metadata.frontier_5s_inputs_coverage_ratio,metadata.frontier_5s_expected,metadata.frontier_5s_synth_n,metadata.frontier_5s_synth_ratio,metadata.frontier_5s_trade_n,metadata.frontier_5s_trade_ratio,age_ms";

impl BarsV1 {
    pub fn metamorphose_csv(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        write_csv_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into CSV.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_csv_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        write_csv_response(archived, max_response_bytes)
    }
}

impl CsvMetamorphoseSchema for BarsV1 {
    fn metamorphose_csv(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_csv(bytes, max_response_bytes)
    }
    fn metamorphose_csv_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_csv_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn write_csv_response(
    archived: &ArchivedMathildeTransportResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = CsvWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.raw_static(CSV_HEADER)?;
    writer.newline()?;
    for row in archived.rows.iter() {
        write_csv_row(row, &mut writer)?;
    }
    Ok(writer.finish())
}

fn write_csv_row(
    row: &<MathildeBarRowV1 as Archive>::Archived,
    writer: &mut CsvWriter,
) -> Result<()> {
    writer.u32_cell(u32::from(1_u16))?;
    writer.comma()?;
    writer.string_cell(pair_symbol(row.pair_ordinal.to_native())?)?;
    writer.comma()?;
    writer.string_cell(tf_symbol(row.tf_ordinal.to_native())?)?;
    writer.comma()?;
    writer.i64_cell(row.open_ms.to_native())?;
    writer.comma()?;
    writer.i64_cell(row.close_ms.to_native())?;
    writer.comma()?;
    writer.utc_cell(row.open_ms.to_native())?;
    writer.comma()?;
    writer.utc_cell(row.close_ms.to_native())?;
    writer.comma()?;
    writer.f64_cell("o", row.o.to_native())?;
    writer.comma()?;
    writer.f64_cell("h", row.h.to_native())?;
    writer.comma()?;
    writer.f64_cell("l", row.l.to_native())?;
    writer.comma()?;
    writer.f64_cell("c", row.c.to_native())?;
    writer.comma()?;
    writer.f64_cell("v", row.v.to_native())?;
    writer.comma()?;
    writer.f64_cell("quote_v", row.quote_v.to_native())?;
    writer.comma()?;
    writer.f64_cell("taker_known_v", row.taker_known_v.to_native())?;
    writer.comma()?;
    writer.f64_cell("taker_signed_v", row.taker_signed_v.to_native())?;
    writer.comma()?;
    writer.f64_cell("taker_known_quote_v", row.taker_known_quote_v.to_native())?;
    writer.comma()?;
    writer.f64_cell("taker_signed_quote_v", row.taker_signed_quote_v.to_native())?;
    writer.comma()?;
    writer.i64_cell(row.taker_known_n.to_native())?;
    writer.comma()?;
    writer.i64_cell(row.taker_signed_n.to_native())?;
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_VW != 0 {
        writer.f64_cell("vw", row.vw.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_N != 0 {
        writer.i64_cell(row.n.to_native())?;
    }
    writer.comma()?;
    writer.string_cell(source_symbol(row.source_ordinal.to_native())?)?;
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0 {
        writer.string_cell(process_symbol(row.process_ordinal.to_native())?)?;
    }
    writer.comma()?;
    write_csv_venue_bitmask(row.venues_expected_mask.to_native(), writer)?;
    writer.comma()?;
    write_csv_venue_bitmask(row.venues_with_trades_mask.to_native(), writer)?;
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        writer.i64_cell(row.ingested_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        writer.utc_cell(row.ingested_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        writer.i64_cell(row.target_ingested_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        writer.utc_cell(row.target_ingested_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        writer.i64_cell(row.built_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        writer.utc_cell(row.built_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        writer.i64_cell(row.committed_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        writer.utc_cell(row.committed_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        writer.i64_cell(row.harmonized_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        writer.utc_cell(row.harmonized_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        writer.i64_cell(row.recomputed_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        writer.utc_cell(row.recomputed_at_ms.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0 {
        writer.string_cell(recomputed_reason_symbol(
            row.recomputed_reason_ordinal.to_native(),
        )?)?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_COVERED_1M_COUNT != 0 {
        writer.i64_cell(row.covered_1m_count.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_EXPECTED_1M_COUNT != 0 {
        writer.i64_cell(row.expected_1m_count.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0 {
        writer.f64_cell("metadata.coverage_ratio", row.coverage_ratio.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER != 0 {
        writer.i64_cell(row.inputs_source_counts_frontier.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0 {
        writer.i64_cell(row.inputs_source_counts_api.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0 {
        writer.i64_cell(row.inputs_source_counts_synthetic.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA != 0 {
        writer.i64_cell(row.inputs_source_counts_fix_data.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO != 0 {
        writer.f64_cell(
            "metadata.frontier_5s_inputs_coverage_ratio",
            row.frontier_5s_inputs_coverage_ratio.to_native(),
        )?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_EXPECTED != 0 {
        writer.i64_cell(row.frontier_5s_expected.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_N != 0 {
        writer.i64_cell(row.frontier_5s_synth_n.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_RATIO != 0 {
        writer.f64_cell(
            "metadata.frontier_5s_synth_ratio",
            row.frontier_5s_synth_ratio.to_native(),
        )?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_N != 0 {
        writer.i64_cell(row.frontier_5s_trade_n.to_native())?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_RATIO != 0 {
        writer.f64_cell(
            "metadata.frontier_5s_trade_ratio",
            row.frontier_5s_trade_ratio.to_native(),
        )?;
    }
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_AGE_MS != 0 {
        writer.i64_cell(row.age_ms.to_native())?;
    }
    writer.newline()
}

fn write_csv_venue_bitmask(mask: u64, writer: &mut CsvWriter) -> Result<()> {
    writer.begin_array_cell()?;
    let mut first = true;
    if mask & (1_u64 << 0) != 0 {
        if first {
            first = false;
        } else {
            writer.array_cell_comma()?;
        }
        writer.string_cell("binance")?;
    }
    if mask & (1_u64 << 1) != 0 {
        if first {
            first = false;
        } else {
            writer.array_cell_comma()?;
        }
        writer.string_cell("bybit")?;
    }
    if mask & (1_u64 << 2) != 0 {
        if first {
            first = false;
        } else {
            writer.array_cell_comma()?;
        }
        writer.string_cell("okx")?;
    }
    let _ = first;
    writer.end_array_cell()
}
