// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=1 schema_version=1 schema_hash=6061383958499356843

use crate::bars_v1::*;
use mbt_adapter_protobuf::{self as proto, ProtoWriter};
use mbt_core::error::Result;
use mbt_core::output;
use mbt_metamorphose::{ProtobufMetamorphoseSchema, runtime::TrustedUnchecked};
use rkyv::Archive;

impl BarsV1 {
    pub fn metamorphose_protobuf(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        write_protobuf_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into protobuf.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_protobuf_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        write_protobuf_response(archived, max_response_bytes)
    }
}

impl ProtobufMetamorphoseSchema for BarsV1 {
    fn metamorphose_protobuf(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_protobuf(bytes, max_response_bytes)
    }
    fn metamorphose_protobuf_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_protobuf_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn write_protobuf_response(
    archived: &ArchivedMathildeTransportResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = ProtoWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.uint32(1, u32::from(SCHEMA_VERSION_VALUE))?;
    for row in archived.rows.iter() {
        let row_len = encoded_len_row(row, max_response_bytes)?;
        writer.message_prefix(2, row_len)?;
        write_protobuf_row(row, &mut writer)?;
    }
    Ok(writer.finish())
}

fn encoded_len_row(
    row: &<MathildeBarRowV1 as Archive>::Archived,
    max_response_bytes: usize,
) -> Result<usize> {
    let mut len = 0_usize;
    len = output::checked_len_add(
        len,
        proto::encoded_len_uint32(1, u32::from(1_u16)),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_string(2, pair_symbol(row.pair_ordinal.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_string(3, tf_symbol(row.tf_ordinal.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_int64(4, row.open_ms.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_int64(5, row.close_ms.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_message(6, output::utc_len(row.open_ms.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_message(7, output::utc_len(row.close_ms.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(8, row.o.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(9, row.h.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(10, row.l.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(11, row.c.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(12, row.v.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(13, row.quote_v.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(14, row.taker_known_v.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(15, row.taker_signed_v.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(16, row.taker_known_quote_v.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(17, row.taker_signed_quote_v.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_int64(18, row.taker_known_n.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_int64(19, row.taker_signed_n.to_native()),
        max_response_bytes,
    )?;
    if row.presence_bits.to_native() & PRESENCE_VW != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_double(20, row.vw.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_N != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(21, row.n.to_native()),
            max_response_bytes,
        )?;
    }
    let message_len = encoded_len_metadata(row, max_response_bytes)?;
    if message_len > 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(22, message_len),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_AGE_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(23, row.age_ms.to_native()),
            max_response_bytes,
        )?;
    }
    Ok(len)
}

fn write_protobuf_row(
    row: &<MathildeBarRowV1 as Archive>::Archived,
    writer: &mut ProtoWriter,
) -> Result<()> {
    writer.uint32(1, u32::from(1_u16))?;
    writer.string(2, pair_symbol(row.pair_ordinal.to_native())?)?;
    writer.string(3, tf_symbol(row.tf_ordinal.to_native())?)?;
    writer.int64(4, row.open_ms.to_native())?;
    writer.int64(5, row.close_ms.to_native())?;
    writer.utc(6, row.open_ms.to_native())?;
    writer.utc(7, row.close_ms.to_native())?;
    writer.double(8, "o", row.o.to_native())?;
    writer.double(9, "h", row.h.to_native())?;
    writer.double(10, "l", row.l.to_native())?;
    writer.double(11, "c", row.c.to_native())?;
    writer.double(12, "v", row.v.to_native())?;
    writer.double(13, "quote_v", row.quote_v.to_native())?;
    writer.double(14, "taker_known_v", row.taker_known_v.to_native())?;
    writer.double(15, "taker_signed_v", row.taker_signed_v.to_native())?;
    writer.double(
        16,
        "taker_known_quote_v",
        row.taker_known_quote_v.to_native(),
    )?;
    writer.double(
        17,
        "taker_signed_quote_v",
        row.taker_signed_quote_v.to_native(),
    )?;
    writer.int64(18, row.taker_known_n.to_native())?;
    writer.int64(19, row.taker_signed_n.to_native())?;
    if row.presence_bits.to_native() & PRESENCE_VW != 0 {
        writer.double(20, "vw", row.vw.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_N != 0 {
        writer.int64(21, row.n.to_native())?;
    }
    let message_len = encoded_len_metadata(row, usize::MAX)?;
    if message_len > 0 {
        writer.message_prefix(22, message_len)?;
        write_protobuf_metadata(row, writer)?;
    }
    if row.presence_bits.to_native() & PRESENCE_AGE_MS != 0 {
        writer.int64(23, row.age_ms.to_native())?;
    }
    Ok(())
}

fn encoded_len_metadata(
    row: &<MathildeBarRowV1 as Archive>::Archived,
    max_response_bytes: usize,
) -> Result<usize> {
    let mut len = 0_usize;
    len = output::checked_len_add(
        len,
        output::encoded_len_string(1, source_symbol(row.source_ordinal.to_native())?),
        max_response_bytes,
    )?;
    if row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(2, process_symbol(row.process_ordinal.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.venues_expected_mask.to_native() & (1_u64 << 0) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(3, "binance"),
            max_response_bytes,
        )?;
    }
    if row.venues_expected_mask.to_native() & (1_u64 << 1) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(3, "bybit"),
            max_response_bytes,
        )?;
    }
    if row.venues_expected_mask.to_native() & (1_u64 << 2) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(3, "okx"),
            max_response_bytes,
        )?;
    }
    if row.venues_with_trades_mask.to_native() & (1_u64 << 0) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(4, "binance"),
            max_response_bytes,
        )?;
    }
    if row.venues_with_trades_mask.to_native() & (1_u64 << 1) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(4, "bybit"),
            max_response_bytes,
        )?;
    }
    if row.venues_with_trades_mask.to_native() & (1_u64 << 2) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(4, "okx"),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(5, row.ingested_at_ms.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(6, output::utc_len(row.ingested_at_ms.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(7, row.target_ingested_at_ms.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(8, output::utc_len(row.target_ingested_at_ms.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(9, row.built_at_ms.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(10, output::utc_len(row.built_at_ms.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(11, row.committed_at_ms.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(12, output::utc_len(row.committed_at_ms.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(13, row.harmonized_at_ms.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(14, output::utc_len(row.harmonized_at_ms.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(15, row.recomputed_at_ms.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_message(16, output::utc_len(row.recomputed_at_ms.to_native())?),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(
                17,
                recomputed_reason_symbol(row.recomputed_reason_ordinal.to_native())?,
            ),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_COVERED_1M_COUNT != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(18, row.covered_1m_count.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_EXPECTED_1M_COUNT != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(19, row.expected_1m_count.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_double(20, row.coverage_ratio.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(21, row.inputs_source_counts_frontier.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(22, row.inputs_source_counts_api.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(23, row.inputs_source_counts_synthetic.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(24, row.inputs_source_counts_fix_data.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_double(25, row.frontier_5s_inputs_coverage_ratio.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_EXPECTED != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(26, row.frontier_5s_expected.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_N != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(27, row.frontier_5s_synth_n.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_RATIO != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_double(28, row.frontier_5s_synth_ratio.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_N != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_int64(29, row.frontier_5s_trade_n.to_native()),
            max_response_bytes,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_RATIO != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_double(30, row.frontier_5s_trade_ratio.to_native()),
            max_response_bytes,
        )?;
    }
    Ok(len)
}

fn write_protobuf_metadata(
    row: &<MathildeBarRowV1 as Archive>::Archived,
    writer: &mut ProtoWriter,
) -> Result<()> {
    writer.string(1, source_symbol(row.source_ordinal.to_native())?)?;
    if row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0 {
        writer.string(2, process_symbol(row.process_ordinal.to_native())?)?;
    }
    if row.venues_expected_mask.to_native() & (1_u64 << 0) != 0 {
        writer.string(3, "binance")?;
    }
    if row.venues_expected_mask.to_native() & (1_u64 << 1) != 0 {
        writer.string(3, "bybit")?;
    }
    if row.venues_expected_mask.to_native() & (1_u64 << 2) != 0 {
        writer.string(3, "okx")?;
    }
    if row.venues_with_trades_mask.to_native() & (1_u64 << 0) != 0 {
        writer.string(4, "binance")?;
    }
    if row.venues_with_trades_mask.to_native() & (1_u64 << 1) != 0 {
        writer.string(4, "bybit")?;
    }
    if row.venues_with_trades_mask.to_native() & (1_u64 << 2) != 0 {
        writer.string(4, "okx")?;
    }
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        writer.int64(5, row.ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        writer.utc(6, row.ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        writer.int64(7, row.target_ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        writer.utc(8, row.target_ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        writer.int64(9, row.built_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        writer.utc(10, row.built_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        writer.int64(11, row.committed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        writer.utc(12, row.committed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        writer.int64(13, row.harmonized_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        writer.utc(14, row.harmonized_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        writer.int64(15, row.recomputed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        writer.utc(16, row.recomputed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0 {
        writer.string(
            17,
            recomputed_reason_symbol(row.recomputed_reason_ordinal.to_native())?,
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_COVERED_1M_COUNT != 0 {
        writer.int64(18, row.covered_1m_count.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_EXPECTED_1M_COUNT != 0 {
        writer.int64(19, row.expected_1m_count.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0 {
        writer.double(
            20,
            "metadata.coverage_ratio",
            row.coverage_ratio.to_native(),
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER != 0 {
        writer.int64(21, row.inputs_source_counts_frontier.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0 {
        writer.int64(22, row.inputs_source_counts_api.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0 {
        writer.int64(23, row.inputs_source_counts_synthetic.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA != 0 {
        writer.int64(24, row.inputs_source_counts_fix_data.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO != 0 {
        writer.double(
            25,
            "metadata.frontier_5s_inputs_coverage_ratio",
            row.frontier_5s_inputs_coverage_ratio.to_native(),
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_EXPECTED != 0 {
        writer.int64(26, row.frontier_5s_expected.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_N != 0 {
        writer.int64(27, row.frontier_5s_synth_n.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_RATIO != 0 {
        writer.double(
            28,
            "metadata.frontier_5s_synth_ratio",
            row.frontier_5s_synth_ratio.to_native(),
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_N != 0 {
        writer.int64(29, row.frontier_5s_trade_n.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_RATIO != 0 {
        writer.double(
            30,
            "metadata.frontier_5s_trade_ratio",
            row.frontier_5s_trade_ratio.to_native(),
        )?;
    }
    Ok(())
}
