// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=1 schema_version=1 schema_hash=6061383958499356843

use crate::bars_v1::*;
use metamorphic_binary_transport_core::error::Result;
use metamorphic_binary_transport_transponding::*;

pub(crate) struct BarsV1ColumnBatch {
    pub(crate) schema_version: ConstU16Column,
    pub(crate) pair_ordinal: U16Column,
    pub(crate) tf_ordinal: U16Column,
    pub(crate) open_ms: I64Column,
    pub(crate) close_ms: I64Column,
    pub(crate) o: F64Column,
    pub(crate) h: F64Column,
    pub(crate) l: F64Column,
    pub(crate) c: F64Column,
    pub(crate) v: F64Column,
    pub(crate) quote_v: F64Column,
    pub(crate) taker_known_v: F64Column,
    pub(crate) taker_signed_v: F64Column,
    pub(crate) taker_known_quote_v: F64Column,
    pub(crate) taker_signed_quote_v: F64Column,
    pub(crate) taker_known_n: I64Column,
    pub(crate) taker_signed_n: I64Column,
    pub(crate) vw: OptionalF64Column,
    pub(crate) n: OptionalI64Column,
    pub(crate) source_ordinal: U16Column,
    pub(crate) process_ordinal: OptionalU16Column,
    pub(crate) venues_expected_mask: U64Column,
    pub(crate) venues_with_trades_mask: U64Column,
    pub(crate) ingested_at_ms: OptionalI64Column,
    pub(crate) target_ingested_at_ms: OptionalI64Column,
    pub(crate) built_at_ms: OptionalI64Column,
    pub(crate) committed_at_ms: OptionalI64Column,
    pub(crate) harmonized_at_ms: OptionalI64Column,
    pub(crate) recomputed_at_ms: OptionalI64Column,
    pub(crate) recomputed_reason_ordinal: OptionalU16Column,
    pub(crate) covered_1m_count: OptionalI64Column,
    pub(crate) expected_1m_count: OptionalI64Column,
    pub(crate) coverage_ratio: OptionalF64Column,
    pub(crate) inputs_source_counts_frontier: OptionalI64Column,
    pub(crate) inputs_source_counts_api: OptionalI64Column,
    pub(crate) inputs_source_counts_synthetic: OptionalI64Column,
    pub(crate) inputs_source_counts_fix_data: OptionalI64Column,
    pub(crate) frontier_5s_inputs_coverage_ratio: OptionalF64Column,
    pub(crate) frontier_5s_expected: OptionalI64Column,
    pub(crate) frontier_5s_synth_n: OptionalI64Column,
    pub(crate) frontier_5s_synth_ratio: OptionalF64Column,
    pub(crate) frontier_5s_trade_n: OptionalI64Column,
    pub(crate) frontier_5s_trade_ratio: OptionalF64Column,
    pub(crate) age_ms: OptionalI64Column,
}

impl BarsV1ColumnBatch {
    pub(crate) fn byte_len(&self) -> usize {
        let mut len = 0_usize;
        len = len.saturating_add(self.schema_version.byte_len());
        len = len.saturating_add(self.pair_ordinal.byte_len());
        len = len.saturating_add(self.tf_ordinal.byte_len());
        len = len.saturating_add(self.open_ms.byte_len());
        len = len.saturating_add(self.close_ms.byte_len());
        len = len.saturating_add(self.o.byte_len());
        len = len.saturating_add(self.h.byte_len());
        len = len.saturating_add(self.l.byte_len());
        len = len.saturating_add(self.c.byte_len());
        len = len.saturating_add(self.v.byte_len());
        len = len.saturating_add(self.quote_v.byte_len());
        len = len.saturating_add(self.taker_known_v.byte_len());
        len = len.saturating_add(self.taker_signed_v.byte_len());
        len = len.saturating_add(self.taker_known_quote_v.byte_len());
        len = len.saturating_add(self.taker_signed_quote_v.byte_len());
        len = len.saturating_add(self.taker_known_n.byte_len());
        len = len.saturating_add(self.taker_signed_n.byte_len());
        len = len.saturating_add(self.vw.byte_len());
        len = len.saturating_add(self.n.byte_len());
        len = len.saturating_add(self.source_ordinal.byte_len());
        len = len.saturating_add(self.process_ordinal.byte_len());
        len = len.saturating_add(self.venues_expected_mask.byte_len());
        len = len.saturating_add(self.venues_with_trades_mask.byte_len());
        len = len.saturating_add(self.ingested_at_ms.byte_len());
        len = len.saturating_add(self.target_ingested_at_ms.byte_len());
        len = len.saturating_add(self.built_at_ms.byte_len());
        len = len.saturating_add(self.committed_at_ms.byte_len());
        len = len.saturating_add(self.harmonized_at_ms.byte_len());
        len = len.saturating_add(self.recomputed_at_ms.byte_len());
        len = len.saturating_add(self.recomputed_reason_ordinal.byte_len());
        len = len.saturating_add(self.covered_1m_count.byte_len());
        len = len.saturating_add(self.expected_1m_count.byte_len());
        len = len.saturating_add(self.coverage_ratio.byte_len());
        len = len.saturating_add(self.inputs_source_counts_frontier.byte_len());
        len = len.saturating_add(self.inputs_source_counts_api.byte_len());
        len = len.saturating_add(self.inputs_source_counts_synthetic.byte_len());
        len = len.saturating_add(self.inputs_source_counts_fix_data.byte_len());
        len = len.saturating_add(self.frontier_5s_inputs_coverage_ratio.byte_len());
        len = len.saturating_add(self.frontier_5s_expected.byte_len());
        len = len.saturating_add(self.frontier_5s_synth_n.byte_len());
        len = len.saturating_add(self.frontier_5s_synth_ratio.byte_len());
        len = len.saturating_add(self.frontier_5s_trade_n.byte_len());
        len = len.saturating_add(self.frontier_5s_trade_ratio.byte_len());
        len = len.saturating_add(self.age_ms.byte_len());
        len
    }
}

impl BarsV1 {
    pub(crate) fn transpond_archived(
        archived: &ArchivedMathildeTransportResponseV1Payload,
        max_columnar_bytes: usize,
    ) -> Result<BarsV1ColumnBatch> {
        let row_count = archived.rows.len();
        let schema_version = ConstU16Column::new(1, row_count);
        let mut pair_ordinal = U16Column::new(row_count);
        let mut tf_ordinal = U16Column::new(row_count);
        let mut open_ms = I64Column::new(row_count);
        let mut close_ms = I64Column::new(row_count);
        let mut o = F64Column::new(row_count);
        let mut h = F64Column::new(row_count);
        let mut l = F64Column::new(row_count);
        let mut c = F64Column::new(row_count);
        let mut v = F64Column::new(row_count);
        let mut quote_v = F64Column::new(row_count);
        let mut taker_known_v = F64Column::new(row_count);
        let mut taker_signed_v = F64Column::new(row_count);
        let mut taker_known_quote_v = F64Column::new(row_count);
        let mut taker_signed_quote_v = F64Column::new(row_count);
        let mut taker_known_n = I64Column::new(row_count);
        let mut taker_signed_n = I64Column::new(row_count);
        let mut vw = OptionalF64Column::new(row_count);
        let mut n = OptionalI64Column::new(row_count);
        let mut source_ordinal = U16Column::new(row_count);
        let mut process_ordinal = OptionalU16Column::new(row_count);
        let mut venues_expected_mask = U64Column::new(row_count);
        let mut venues_with_trades_mask = U64Column::new(row_count);
        let mut ingested_at_ms = OptionalI64Column::new(row_count);
        let mut target_ingested_at_ms = OptionalI64Column::new(row_count);
        let mut built_at_ms = OptionalI64Column::new(row_count);
        let mut committed_at_ms = OptionalI64Column::new(row_count);
        let mut harmonized_at_ms = OptionalI64Column::new(row_count);
        let mut recomputed_at_ms = OptionalI64Column::new(row_count);
        let mut recomputed_reason_ordinal = OptionalU16Column::new(row_count);
        let mut covered_1m_count = OptionalI64Column::new(row_count);
        let mut expected_1m_count = OptionalI64Column::new(row_count);
        let mut coverage_ratio = OptionalF64Column::new(row_count);
        let mut inputs_source_counts_frontier = OptionalI64Column::new(row_count);
        let mut inputs_source_counts_api = OptionalI64Column::new(row_count);
        let mut inputs_source_counts_synthetic = OptionalI64Column::new(row_count);
        let mut inputs_source_counts_fix_data = OptionalI64Column::new(row_count);
        let mut frontier_5s_inputs_coverage_ratio = OptionalF64Column::new(row_count);
        let mut frontier_5s_expected = OptionalI64Column::new(row_count);
        let mut frontier_5s_synth_n = OptionalI64Column::new(row_count);
        let mut frontier_5s_synth_ratio = OptionalF64Column::new(row_count);
        let mut frontier_5s_trade_n = OptionalI64Column::new(row_count);
        let mut frontier_5s_trade_ratio = OptionalF64Column::new(row_count);
        let mut age_ms = OptionalI64Column::new(row_count);
        for row in archived.rows.iter() {
            pair_ordinal.push_required(row.pair_ordinal.to_native());
            tf_ordinal.push_required(row.tf_ordinal.to_native());
            open_ms.push_required(row.open_ms.to_native());
            close_ms.push_required(row.close_ms.to_native());
            o.push_required(row.o.to_native());
            h.push_required(row.h.to_native());
            l.push_required(row.l.to_native());
            c.push_required(row.c.to_native());
            v.push_required(row.v.to_native());
            quote_v.push_required(row.quote_v.to_native());
            taker_known_v.push_required(row.taker_known_v.to_native());
            taker_signed_v.push_required(row.taker_signed_v.to_native());
            taker_known_quote_v.push_required(row.taker_known_quote_v.to_native());
            taker_signed_quote_v.push_required(row.taker_signed_quote_v.to_native());
            taker_known_n.push_required(row.taker_known_n.to_native());
            taker_signed_n.push_required(row.taker_signed_n.to_native());
            vw.push_optional(
                row.presence_bits.to_native() & PRESENCE_VW != 0,
                row.vw.to_native(),
            )?;
            n.push_optional(
                row.presence_bits.to_native() & PRESENCE_N != 0,
                row.n.to_native(),
            )?;
            source_ordinal.push_required(row.source_ordinal.to_native());
            process_ordinal.push_optional(
                row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0,
                row.process_ordinal.to_native(),
            )?;
            venues_expected_mask.push_required(row.venues_expected_mask.to_native());
            venues_with_trades_mask.push_required(row.venues_with_trades_mask.to_native());
            ingested_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0,
                row.ingested_at_ms.to_native(),
            )?;
            target_ingested_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0,
                row.target_ingested_at_ms.to_native(),
            )?;
            built_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0,
                row.built_at_ms.to_native(),
            )?;
            committed_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0,
                row.committed_at_ms.to_native(),
            )?;
            harmonized_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0,
                row.harmonized_at_ms.to_native(),
            )?;
            recomputed_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0,
                row.recomputed_at_ms.to_native(),
            )?;
            recomputed_reason_ordinal.push_optional(
                row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0,
                row.recomputed_reason_ordinal.to_native(),
            )?;
            covered_1m_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_COVERED_1M_COUNT != 0,
                row.covered_1m_count.to_native(),
            )?;
            expected_1m_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_EXPECTED_1M_COUNT != 0,
                row.expected_1m_count.to_native(),
            )?;
            coverage_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0,
                row.coverage_ratio.to_native(),
            )?;
            inputs_source_counts_frontier.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FRONTIER != 0,
                row.inputs_source_counts_frontier.to_native(),
            )?;
            inputs_source_counts_api.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0,
                row.inputs_source_counts_api.to_native(),
            )?;
            inputs_source_counts_synthetic.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0,
                row.inputs_source_counts_synthetic.to_native(),
            )?;
            inputs_source_counts_fix_data.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_FIX_DATA != 0,
                row.inputs_source_counts_fix_data.to_native(),
            )?;
            frontier_5s_inputs_coverage_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_INPUTS_COVERAGE_RATIO != 0,
                row.frontier_5s_inputs_coverage_ratio.to_native(),
            )?;
            frontier_5s_expected.push_optional(
                row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_EXPECTED != 0,
                row.frontier_5s_expected.to_native(),
            )?;
            frontier_5s_synth_n.push_optional(
                row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_N != 0,
                row.frontier_5s_synth_n.to_native(),
            )?;
            frontier_5s_synth_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_SYNTH_RATIO != 0,
                row.frontier_5s_synth_ratio.to_native(),
            )?;
            frontier_5s_trade_n.push_optional(
                row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_N != 0,
                row.frontier_5s_trade_n.to_native(),
            )?;
            frontier_5s_trade_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_FRONTIER_5S_TRADE_RATIO != 0,
                row.frontier_5s_trade_ratio.to_native(),
            )?;
            age_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_AGE_MS != 0,
                row.age_ms.to_native(),
            )?;
        }
        let batch = BarsV1ColumnBatch {
            schema_version,
            pair_ordinal,
            tf_ordinal,
            open_ms,
            close_ms,
            o,
            h,
            l,
            c,
            v,
            quote_v,
            taker_known_v,
            taker_signed_v,
            taker_known_quote_v,
            taker_signed_quote_v,
            taker_known_n,
            taker_signed_n,
            vw,
            n,
            source_ordinal,
            process_ordinal,
            venues_expected_mask,
            venues_with_trades_mask,
            ingested_at_ms,
            target_ingested_at_ms,
            built_at_ms,
            committed_at_ms,
            harmonized_at_ms,
            recomputed_at_ms,
            recomputed_reason_ordinal,
            covered_1m_count,
            expected_1m_count,
            coverage_ratio,
            inputs_source_counts_frontier,
            inputs_source_counts_api,
            inputs_source_counts_synthetic,
            inputs_source_counts_fix_data,
            frontier_5s_inputs_coverage_ratio,
            frontier_5s_expected,
            frontier_5s_synth_n,
            frontier_5s_synth_ratio,
            frontier_5s_trade_n,
            frontier_5s_trade_ratio,
            age_ms,
        };
        ensure_columnar_size(batch.byte_len(), max_columnar_bytes)?;
        Ok(batch)
    }
}
