[package]
name = "mbt_benches"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
mbt_core = { path = "../core" }
mbt_compression = { path = "../compression" }
mbt_schema_bars = { path = "../schemas/bars_core", features = ["json", "protobuf", "csv", "arrow_ipc", "parquet"] }
mbt_schema_test_compatibility = { path = "../schemas/test_compatibility_core" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
