[package]
name = "mbt_adapter_parquet"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
arrow-array = "=56.2.1"
arrow-buffer = "=56.2.1"
arrow-schema = "=56.2.1"
mbt_core = { path = "../../core" }
mbt_transponding = { path = "../../transponding" }
parquet = "=56.2.1"

[dev-dependencies]
bytes = "=1.11.1"
