[package]
name = "metamorphic_binary_transport_codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "mbt_codegen"
path = "src/main.rs"

[dependencies]
prost-reflect = { version = "=0.16.4", default-features = false }
thiserror = "=2.0.17"
