[package]
name = "mbt_schema_test_compatibility"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
mbt_core = { path = "../../core" }
mbt_metamorphose = { path = "../../metamorphose", optional = true }
mbt_transponding = { path = "../../transponding", optional = true }
mbt_adapter_json = { path = "../../adapters/json", optional = true }
mbt_adapter_protobuf = { path = "../../adapters/protobuf", optional = true }
mbt_adapter_csv = { path = "../../adapters/csv", optional = true }
mbt_adapter_arrow = { path = "../../adapters/arrow", optional = true }
mbt_adapter_arrow_ipc = { path = "../../adapters/arrow_ipc", optional = true }
mbt_adapter_parquet = { path = "../../adapters/parquet", optional = true }
rkyv = { workspace = true }

[features]
default = []
json = [
    "dep:mbt_metamorphose",
    "dep:mbt_adapter_json",
]
protobuf = [
    "dep:mbt_metamorphose",
    "dep:mbt_adapter_protobuf",
]
csv = [
    "dep:mbt_metamorphose",
    "dep:mbt_adapter_csv",
]
arrow = [
    "dep:mbt_metamorphose",
    "dep:mbt_transponding",
    "dep:mbt_adapter_arrow",
]
arrow_ipc = [
    "dep:mbt_metamorphose",
    "dep:mbt_transponding",
    "dep:mbt_adapter_arrow_ipc",
]
parquet = [
    "dep:mbt_metamorphose",
    "dep:mbt_transponding",
    "dep:mbt_adapter_parquet",
]
