// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=50001 schema_version=1 schema_hash=232196938863914698

use rkyv::rancor::{Error as RkyvError, Fallible, Source};
use rkyv::ser::{Allocator, Writer};
use rkyv::vec::{ArchivedVec, VecResolver};
use rkyv::{Archive, Place, Serialize as RkyvSerialize};

use mbt_core::envelope::{
    HEADER_LEN, SchemaHeaderSpec, TransportHeader, decode_header, encode_header, fnv1a64,
    trusted_payload_for_schema, validate_header_for_schema,
};
use mbt_core::error::{Result, TransportError};
use mbt_core::runtime::{BinaryInspection, MbtSchema};

pub const SCHEMA_ID: u32 = 50001;
pub const SCHEMA_VERSION_VALUE: u16 = 1;
pub const SCHEMA_VERSION: u16 = SCHEMA_VERSION_VALUE;
pub const GENERATED_SCHEMA_HASH: u64 = 232196938863914698;
pub const TRANSPORT_NAME: &str = "mbt.example.telemetry.v1";
pub const SCHEMA_HEADER: SchemaHeaderSpec = SchemaHeaderSpec {
    schema_id: SCHEMA_ID,
    schema_version: SCHEMA_VERSION,
    schema_hash: GENERATED_SCHEMA_HASH,
};

pub const DEVICE_SENSOR_A: u16 = 0;
pub const DEVICE_SENSOR_B: u16 = 1;
pub const DEVICE_SENSOR_C: u16 = 2;
pub const DEVICE_COUNT: u16 = 3;

pub const STATUS_NONE: u16 = 0;
pub const STATUS_ACTIVE: u16 = 1;
pub const STATUS_IDLE: u16 = 2;
pub const STATUS_OFFLINE: u16 = 3;

pub const TAG_INDOOR_BIT: u64 = 0;
pub const TAG_OUTDOOR_BIT: u64 = 1;
pub const TAG_TEST_BIT: u64 = 2;
pub const VALID_TAG_MASK: u64 =
    (1 << TAG_INDOOR_BIT) | (1 << TAG_OUTDOOR_BIT) | (1 << TAG_TEST_BIT);

pub const PRESENCE_BATTERY_PERCENT: u64 = 1 << 0;
pub const PRESENCE_ALLOWED_MASK: u64 = (1 << 1) - 1;

#[derive(Clone, Archive, RkyvSerialize)]
pub struct TelemetryResponseV1Payload {
    pub schema_version: u16,
    pub rows: Vec<TelemetryRowV1>,
}

#[derive(Clone, Archive, RkyvSerialize)]
pub struct TelemetryRowV1 {
    pub schema_version: u16,
    pub device_ordinal: u16,
    pub recorded_at_ms: i64,
    pub temperature_c: f64,
    pub battery_percent: f64,
    pub status_ordinal: u16,
    pub tags_mask: u64,
    pub presence_bits: u64,
}

pub fn validate_rows(rows: &[TelemetryRowV1]) -> Result<()> {
    let mut previous = None;
    for row in rows {
        validate_row(row, previous)?;
        previous = Some(row);
    }
    Ok(())
}

pub fn validate_row(row: &TelemetryRowV1, previous: Option<&TelemetryRowV1>) -> Result<()> {
    if row.schema_version != 1 {
        return Err(TransportError::SchemaVersionMismatch {
            observed: row.schema_version,
            expected: 1,
        });
    }
    device_symbol(row.device_ordinal)?;
    validate_finite_f64("temperature_c", row.temperature_c)?;
    validate_finite_f64("battery_percent", row.battery_percent)?;
    status_symbol(row.status_ordinal)?;
    if row.tags_mask & !VALID_TAG_MASK != 0 {
        return Err(TransportError::InvalidBitmask {
            field: "tags",
            value: row.tags_mask,
        });
    }
    if row.presence_bits & !PRESENCE_ALLOWED_MASK != 0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if row.presence_bits & PRESENCE_BATTERY_PERCENT == 0 && row.battery_percent != 0.0 {
        return Err(TransportError::InvalidPresenceBits(row.presence_bits));
    }
    if previous.is_some_and(|prev| {
        (row.device_ordinal, row.recorded_at_ms) < (prev.device_ordinal, prev.recorded_at_ms)
    }) {
        return Err(TransportError::InvalidTimeGrid(
            "key order regression".to_string(),
        ));
    }
    Ok(())
}

fn validate_finite_f64(field: &'static str, value: f64) -> Result<()> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(TransportError::NonFiniteNumeric(field))
    }
}

pub fn semantic_checksum(rows: &[TelemetryRowV1]) -> u64 {
    let mut checksum = fnv1a64("mbt.example.telemetry.v1".as_bytes());
    for row in rows {
        checksum = checksum_row(checksum, row, true);
    }
    checksum
}

pub fn minimal_projection_checksum(rows: &[TelemetryRowV1]) -> u64 {
    let mut checksum = fnv1a64("mbt.example.telemetry.v1-minimal".as_bytes());
    for row in rows {
        checksum = checksum_row(checksum, row, false);
    }
    checksum
}

pub fn checksum_row(mut checksum: u64, row: &TelemetryRowV1, include_metadata: bool) -> u64 {
    checksum = update_u16(checksum, row.schema_version);
    checksum = update_u16(checksum, row.device_ordinal);
    checksum = update_i64(checksum, row.recorded_at_ms);
    checksum = update_f64(checksum, row.temperature_c);
    if include_metadata {
        checksum = update_u64(checksum, row.presence_bits);
        checksum = update_f64(checksum, row.battery_percent);
        checksum = update_u16(checksum, row.status_ordinal);
        checksum = update_u64(checksum, row.tags_mask);
    }
    checksum
}

pub fn checksum_archived_row(
    mut checksum: u64,
    row: &<TelemetryRowV1 as Archive>::Archived,
    include_metadata: bool,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.device_ordinal.to_native());
    checksum = update_i64(checksum, row.recorded_at_ms.to_native());
    checksum = update_f64(checksum, row.temperature_c.to_native());
    if include_metadata {
        checksum = update_u64(checksum, row.presence_bits.to_native());
        checksum = update_f64(checksum, row.battery_percent.to_native());
        checksum = update_u16(checksum, row.status_ordinal.to_native());
        checksum = update_u64(checksum, row.tags_mask.to_native());
    }
    checksum
}

pub fn minimal_projection_archived_row(
    mut checksum: u64,
    row: &<TelemetryRowV1 as Archive>::Archived,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.device_ordinal.to_native());
    checksum = update_i64(checksum, row.recorded_at_ms.to_native());
    checksum = update_f64(checksum, row.temperature_c.to_native());
    checksum
}

fn fnv1a64_update(mut checksum: u64, byte: u8) -> u64 {
    checksum ^= u64::from(byte);
    checksum.wrapping_mul(0x00000100000001B3)
}

fn update_fixed<const N: usize>(mut checksum: u64, bytes: [u8; N]) -> u64 {
    for byte in bytes {
        checksum = fnv1a64_update(checksum, byte);
    }
    checksum
}

fn update_u16(checksum: u64, value: u16) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_i64(checksum: u64, value: i64) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_u64(checksum: u64, value: u64) -> u64 {
    update_fixed(checksum, value.to_le_bytes())
}

fn update_f64(checksum: u64, value: f64) -> u64 {
    update_u64(checksum, value.to_bits())
}

pub fn device_symbol(value: u16) -> Result<&'static str> {
    match value {
        0 => Ok("sensor_a"),
        1 => Ok("sensor_b"),
        2 => Ok("sensor_c"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "device",
            value: other,
        }),
    }
}

pub fn device_ordinal(value: &str) -> Result<u16> {
    match value {
        "sensor_a" => Ok(0),
        "sensor_b" => Ok(1),
        "sensor_c" => Ok(2),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "device",
            value: u16::MAX,
        }),
    }
}

pub fn status_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("active"),
        2 => Ok("idle"),
        3 => Ok("offline"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "status",
            value: other,
        }),
    }
}

pub fn status_ordinal(value: &str) -> Result<u16> {
    match value {
        "active" => Ok(1),
        "idle" => Ok(2),
        "offline" => Ok(3),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "status",
            value: u16::MAX,
        }),
    }
}

pub fn tag_symbol(value: u16) -> Result<&'static str> {
    match value {
        1 => Ok("indoor"),
        2 => Ok("outdoor"),
        3 => Ok("test"),
        other => Err(TransportError::InvalidEnumOrdinal {
            field: "tag",
            value: other,
        }),
    }
}

pub fn tag_ordinal(value: &str) -> Result<u16> {
    match value {
        "indoor" => Ok(1),
        "outdoor" => Ok(2),
        "test" => Ok(3),
        _ => Err(TransportError::InvalidEnumOrdinal {
            field: "tag",
            value: u16::MAX,
        }),
    }
}

pub struct TelemetryV1;

impl TelemetryV1 {
    pub const SCHEMA_ID: u32 = SCHEMA_ID;
    pub const SCHEMA_VERSION: u16 = SCHEMA_VERSION;
    pub const SCHEMA_HASH: u64 = GENERATED_SCHEMA_HASH;
    pub const TRANSPORT_NAME: &'static str = TRANSPORT_NAME;

    pub fn header_spec() -> SchemaHeaderSpec {
        SCHEMA_HEADER
    }

    pub fn encode(rows: &[TelemetryRowV1], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows.to_vec(), max_response_bytes)
    }

    pub fn encode_owned(rows: Vec<TelemetryRowV1>, max_response_bytes: usize) -> Result<Vec<u8>> {
        validate_rows(&rows)?;
        let row_count = rows.len();
        let payload = TelemetryResponseV1Payload {
            schema_version: SCHEMA_VERSION_VALUE,
            rows,
        };
        let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        let payload_len = payload_bytes.len();
        let total_len =
            HEADER_LEN
                .checked_add(payload_len)
                .ok_or(TransportError::ResponseTooLarge {
                    observed: usize::MAX,
                    cap: max_response_bytes,
                })?;
        if total_len > max_response_bytes {
            return Err(TransportError::ResponseTooLarge {
                observed: total_len,
                cap: max_response_bytes,
            });
        }
        let header = TransportHeader::new_with_schema(
            Self::header_spec(),
            row_count as u64,
            payload_len as u64,
            fnv1a64(&payload_bytes),
        );
        let mut header_bytes = [0_u8; HEADER_LEN];
        encode_header(&header, &mut header_bytes);
        let mut out = Vec::with_capacity(total_len);
        out.extend_from_slice(&header_bytes);
        out.extend_from_slice(&payload_bytes);
        Ok(out)
    }

    pub fn access(bytes: &[u8]) -> Result<TelemetryV1View<'_>> {
        Ok(TelemetryV1View {
            archived: Self::access_archived(bytes)?,
        })
    }

    pub(crate) fn access_archived(bytes: &[u8]) -> Result<&ArchivedTelemetryResponseV1Payload> {
        let (header, payload) = decode_payload(bytes, Self::header_spec())?;
        let archived = rkyv::access::<ArchivedTelemetryResponseV1Payload, RkyvError>(payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    /// Returns an archived payload view for immutable bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for this schema and then stored or transported without mutation.
    pub unsafe fn access_archived_trusted_unchecked(
        bytes: &[u8],
    ) -> Result<&ArchivedTelemetryResponseV1Payload> {
        let payload = trusted_payload_for_schema(bytes, Self::header_spec())?;
        Ok(unsafe { rkyv::access_unchecked::<ArchivedTelemetryResponseV1Payload>(payload) })
    }

    pub fn inspect(bytes: &[u8]) -> Result<BinaryInspection> {
        inspect_archived_rows(Self::access_archived(bytes)?)
    }
}

impl MbtSchema for TelemetryV1 {
    type Row = TelemetryRowV1;
    type View<'a> = TelemetryV1View<'a>;

    fn encode_rows(rows: &[Self::Row], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode(rows, max_response_bytes)
    }
    fn encode_owned_rows(rows: Vec<Self::Row>, max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows, max_response_bytes)
    }
    fn access_view(bytes: &[u8]) -> Result<Self::View<'_>> {
        Self::access(bytes)
    }
    fn inspect_bytes(bytes: &[u8]) -> Result<BinaryInspection> {
        Self::inspect(bytes)
    }
}

pub struct TelemetryV1View<'a> {
    archived: &'a ArchivedTelemetryResponseV1Payload,
}

impl<'a> TelemetryV1View<'a> {
    pub fn len(&self) -> usize {
        self.archived.rows.len()
    }
    pub fn is_empty(&self) -> bool {
        self.archived.rows.is_empty()
    }
    pub fn rows(&self) -> TelemetryV1Rows<'a> {
        TelemetryV1Rows {
            inner: self.archived.rows.iter(),
        }
    }
}

pub struct TelemetryV1Rows<'a> {
    inner: core::slice::Iter<'a, <TelemetryRowV1 as Archive>::Archived>,
}

impl<'a> Iterator for TelemetryV1Rows<'a> {
    type Item = ArchivedTelemetryV1Row<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        self.inner.next().map(|row| ArchivedTelemetryV1Row { row })
    }
}

pub struct ArchivedTelemetryV1Row<'a> {
    row: &'a <TelemetryRowV1 as Archive>::Archived,
}

impl<'a> ArchivedTelemetryV1Row<'a> {
    pub fn schema_version(&self) -> u16 {
        self.row.schema_version.to_native()
    }
    pub fn device_ordinal(&self) -> u16 {
        self.row.device_ordinal.to_native()
    }
    pub fn device(&self) -> Result<&'static str> {
        device_symbol(self.row.device_ordinal.to_native())
    }
    pub fn recorded_at_ms(&self) -> i64 {
        self.row.recorded_at_ms.to_native()
    }
    pub fn temperature_c(&self) -> f64 {
        self.row.temperature_c.to_native()
    }
    pub fn has_battery_percent(&self) -> bool {
        self.row.presence_bits.to_native() & PRESENCE_BATTERY_PERCENT != 0
    }
    pub fn battery_percent(&self) -> f64 {
        self.row.battery_percent.to_native()
    }
    pub fn status_ordinal(&self) -> u16 {
        self.row.status_ordinal.to_native()
    }
    pub fn status(&self) -> Result<&'static str> {
        status_symbol(self.row.status_ordinal.to_native())
    }
    pub fn tags_mask(&self) -> u64 {
        self.row.tags_mask.to_native()
    }
    pub fn presence_bits(&self) -> u64 {
        self.row.presence_bits.to_native()
    }
}

fn decode_payload(bytes: &[u8], schema: SchemaHeaderSpec) -> Result<(TransportHeader, &[u8])> {
    let header = decode_header(bytes)?;
    let payload = &bytes[HEADER_LEN..];
    validate_header_for_schema(&header, payload, schema)?;
    Ok((header, payload))
}

fn validate_archived_payload(
    archived: &ArchivedTelemetryResponseV1Payload,
    expected_rows: u64,
) -> Result<()> {
    if archived.schema_version.to_native() != SCHEMA_VERSION_VALUE {
        return Err(TransportError::SchemaVersionMismatch {
            observed: archived.schema_version.to_native(),
            expected: SCHEMA_VERSION_VALUE,
        });
    }
    let expected = usize::try_from(expected_rows)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
    if archived.rows.len() != expected {
        return Err(TransportError::RowCountMismatch {
            observed: archived.rows.len(),
            expected: expected_rows,
        });
    }
    validate_archived_rows(archived)
}

fn validate_archived_rows(archived: &ArchivedTelemetryResponseV1Payload) -> Result<()> {
    let mut previous = None;
    for archived_row in archived.rows.iter() {
        let row = row_from_archived(archived_row);
        validate_row(&row, previous.as_ref())?;
        previous = Some(row);
    }
    Ok(())
}

fn inspect_archived_rows(
    archived: &ArchivedTelemetryResponseV1Payload,
) -> Result<BinaryInspection> {
    let mut previous = None;
    let mut semantic_checksum = fnv1a64("mbt.example.telemetry.v1".as_bytes());
    let mut minimal_projection_checksum = fnv1a64("mbt.example.telemetry.v1-minimal".as_bytes());
    for archived_row in archived.rows.iter() {
        let row = row_from_archived(archived_row);
        validate_row(&row, previous.as_ref())?;
        semantic_checksum = checksum_archived_row(semantic_checksum, archived_row, true);
        minimal_projection_checksum =
            minimal_projection_archived_row(minimal_projection_checksum, archived_row);
        previous = Some(row);
    }
    Ok(BinaryInspection {
        row_count: archived.rows.len(),
        semantic_checksum,
        minimal_projection_checksum,
    })
}

fn row_from_archived(row: &<TelemetryRowV1 as Archive>::Archived) -> TelemetryRowV1 {
    TelemetryRowV1 {
        schema_version: row.schema_version.to_native(),
        device_ordinal: row.device_ordinal.to_native(),
        recorded_at_ms: row.recorded_at_ms.to_native(),
        temperature_c: row.temperature_c.to_native(),
        battery_percent: row.battery_percent.to_native(),
        status_ordinal: row.status_ordinal.to_native(),
        tags_mask: row.tags_mask.to_native(),
        presence_bits: row.presence_bits.to_native(),
    }
}
const TEMPERATURE_ONLY_SCHEMA_ID: u32 = 50001;
const TEMPERATURE_ONLY_SCHEMA_VERSION_VALUE: u16 = 1;
const TEMPERATURE_ONLY_SCHEMA_VERSION: u16 = TEMPERATURE_ONLY_SCHEMA_VERSION_VALUE;
const TEMPERATURE_ONLY_GENERATED_SCHEMA_HASH: u64 = 2197847999187611970;
const TEMPERATURE_ONLY_TRANSPORT_NAME: &str = "mbt.example.telemetry.v1.temperature_only";
const TEMPERATURE_ONLY_SCHEMA_HEADER: SchemaHeaderSpec = SchemaHeaderSpec {
    schema_id: TEMPERATURE_ONLY_SCHEMA_ID,
    schema_version: TEMPERATURE_ONLY_SCHEMA_VERSION,
    schema_hash: TEMPERATURE_ONLY_GENERATED_SCHEMA_HASH,
};

#[derive(Clone, Archive, RkyvSerialize)]
pub struct TelemetryResponseV1PayloadTemperatureOnly {
    pub schema_version: u16,
    pub rows: Vec<TelemetryRowV1TemperatureOnly>,
}

#[derive(Clone, Archive, RkyvSerialize)]
pub struct TelemetryRowV1TemperatureOnly {
    pub schema_version: u16,
    pub device_ordinal: u16,
    pub recorded_at_ms: i64,
    pub temperature_c: f64,
}

fn temperature_only_validate_rows(rows: &[TelemetryRowV1TemperatureOnly]) -> Result<()> {
    let mut previous = None;
    for row in rows {
        temperature_only_validate_row(row, previous)?;
        previous = Some(row);
    }
    Ok(())
}

fn temperature_only_validate_row(
    row: &TelemetryRowV1TemperatureOnly,
    previous: Option<&TelemetryRowV1TemperatureOnly>,
) -> Result<()> {
    if row.schema_version != 1 {
        return Err(TransportError::SchemaVersionMismatch {
            observed: row.schema_version,
            expected: 1,
        });
    }
    device_symbol(row.device_ordinal)?;
    validate_finite_f64("temperature_c", row.temperature_c)?;
    if previous.is_some_and(|prev| {
        (row.device_ordinal, row.recorded_at_ms) < (prev.device_ordinal, prev.recorded_at_ms)
    }) {
        return Err(TransportError::InvalidTimeGrid(
            "key order regression".to_string(),
        ));
    }
    Ok(())
}

fn temperature_only_checksum_archived_row(
    mut checksum: u64,
    row: &<TelemetryRowV1TemperatureOnly as Archive>::Archived,
    include_metadata: bool,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.device_ordinal.to_native());
    checksum = update_i64(checksum, row.recorded_at_ms.to_native());
    checksum = update_f64(checksum, row.temperature_c.to_native());
    let _ = include_metadata;
    checksum
}

fn temperature_only_minimal_projection_archived_row(
    mut checksum: u64,
    row: &<TelemetryRowV1TemperatureOnly as Archive>::Archived,
) -> u64 {
    checksum = update_u16(checksum, row.schema_version.to_native());
    checksum = update_u16(checksum, row.device_ordinal.to_native());
    checksum = update_i64(checksum, row.recorded_at_ms.to_native());
    checksum = update_f64(checksum, row.temperature_c.to_native());
    checksum
}

pub struct TelemetryV1TemperatureOnly;

impl TelemetryV1TemperatureOnly {
    pub const SCHEMA_ID: u32 = TEMPERATURE_ONLY_SCHEMA_ID;
    pub const SCHEMA_VERSION: u16 = TEMPERATURE_ONLY_SCHEMA_VERSION;
    pub const SCHEMA_HASH: u64 = TEMPERATURE_ONLY_GENERATED_SCHEMA_HASH;
    pub const TRANSPORT_NAME: &'static str = TEMPERATURE_ONLY_TRANSPORT_NAME;

    pub fn header_spec() -> SchemaHeaderSpec {
        TEMPERATURE_ONLY_SCHEMA_HEADER
    }

    pub fn encode(
        rows: &[TelemetryRowV1TemperatureOnly],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        Self::encode_owned(rows.to_vec(), max_response_bytes)
    }

    pub fn encode_owned(
        rows: Vec<TelemetryRowV1TemperatureOnly>,
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        temperature_only_validate_rows(&rows)?;
        let row_count = rows.len();
        let payload = TelemetryResponseV1PayloadTemperatureOnly {
            schema_version: TEMPERATURE_ONLY_SCHEMA_VERSION_VALUE,
            rows,
        };
        let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
            .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        let payload_len = payload_bytes.len();
        let total_len =
            HEADER_LEN
                .checked_add(payload_len)
                .ok_or(TransportError::ResponseTooLarge {
                    observed: usize::MAX,
                    cap: max_response_bytes,
                })?;
        if total_len > max_response_bytes {
            return Err(TransportError::ResponseTooLarge {
                observed: total_len,
                cap: max_response_bytes,
            });
        }
        let header = TransportHeader::new_with_schema(
            Self::header_spec(),
            row_count as u64,
            payload_len as u64,
            fnv1a64(&payload_bytes),
        );
        let mut header_bytes = [0_u8; HEADER_LEN];
        encode_header(&header, &mut header_bytes);
        let mut out = Vec::with_capacity(total_len);
        out.extend_from_slice(&header_bytes);
        out.extend_from_slice(&payload_bytes);
        Ok(out)
    }

    pub fn access(bytes: &[u8]) -> Result<TelemetryV1TemperatureOnlyView<'_>> {
        Ok(TelemetryV1TemperatureOnlyView {
            archived: Self::access_archived(bytes)?,
        })
    }

    pub(crate) fn access_archived(
        bytes: &[u8],
    ) -> Result<&ArchivedTelemetryResponseV1PayloadTemperatureOnly> {
        let (header, payload) = decode_payload(bytes, Self::header_spec())?;
        let archived =
            rkyv::access::<ArchivedTelemetryResponseV1PayloadTemperatureOnly, RkyvError>(payload)
                .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
        temperature_only_validate_archived_payload(archived, header.row_count)?;
        Ok(archived)
    }

    /// Returns an archived payload view for immutable bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for this schema and then stored or transported without mutation.
    pub unsafe fn access_archived_trusted_unchecked(
        bytes: &[u8],
    ) -> Result<&ArchivedTelemetryResponseV1PayloadTemperatureOnly> {
        let payload = trusted_payload_for_schema(bytes, Self::header_spec())?;
        Ok(unsafe {
            rkyv::access_unchecked::<ArchivedTelemetryResponseV1PayloadTemperatureOnly>(payload)
        })
    }

    pub fn inspect(bytes: &[u8]) -> Result<BinaryInspection> {
        temperature_only_inspect_archived_rows(Self::access_archived(bytes)?)
    }
}

impl MbtSchema for TelemetryV1TemperatureOnly {
    type Row = TelemetryRowV1TemperatureOnly;
    type View<'a> = TelemetryV1TemperatureOnlyView<'a>;

    fn encode_rows(rows: &[Self::Row], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode(rows, max_response_bytes)
    }
    fn encode_owned_rows(rows: Vec<Self::Row>, max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::encode_owned(rows, max_response_bytes)
    }
    fn access_view(bytes: &[u8]) -> Result<Self::View<'_>> {
        Self::access(bytes)
    }
    fn inspect_bytes(bytes: &[u8]) -> Result<BinaryInspection> {
        Self::inspect(bytes)
    }
}

pub struct TelemetryV1TemperatureOnlyView<'a> {
    archived: &'a ArchivedTelemetryResponseV1PayloadTemperatureOnly,
}

impl<'a> TelemetryV1TemperatureOnlyView<'a> {
    pub fn len(&self) -> usize {
        self.archived.rows.len()
    }
    pub fn is_empty(&self) -> bool {
        self.archived.rows.is_empty()
    }
    pub fn rows(&self) -> TelemetryV1TemperatureOnlyRows<'a> {
        TelemetryV1TemperatureOnlyRows {
            inner: self.archived.rows.iter(),
        }
    }
}

pub struct TelemetryV1TemperatureOnlyRows<'a> {
    inner: core::slice::Iter<'a, <TelemetryRowV1TemperatureOnly as Archive>::Archived>,
}

impl<'a> Iterator for TelemetryV1TemperatureOnlyRows<'a> {
    type Item = ArchivedTelemetryV1TemperatureOnlyRow<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        self.inner
            .next()
            .map(|row| ArchivedTelemetryV1TemperatureOnlyRow { row })
    }
}

pub struct ArchivedTelemetryV1TemperatureOnlyRow<'a> {
    row: &'a <TelemetryRowV1TemperatureOnly as Archive>::Archived,
}

impl<'a> ArchivedTelemetryV1TemperatureOnlyRow<'a> {
    pub fn schema_version(&self) -> u16 {
        self.row.schema_version.to_native()
    }
    pub fn device_ordinal(&self) -> u16 {
        self.row.device_ordinal.to_native()
    }
    pub fn device(&self) -> Result<&'static str> {
        device_symbol(self.row.device_ordinal.to_native())
    }
    pub fn recorded_at_ms(&self) -> i64 {
        self.row.recorded_at_ms.to_native()
    }
    pub fn temperature_c(&self) -> f64 {
        self.row.temperature_c.to_native()
    }
}

fn temperature_only_validate_archived_payload(
    archived: &ArchivedTelemetryResponseV1PayloadTemperatureOnly,
    expected_rows: u64,
) -> Result<()> {
    if archived.schema_version.to_native() != TEMPERATURE_ONLY_SCHEMA_VERSION_VALUE {
        return Err(TransportError::SchemaVersionMismatch {
            observed: archived.schema_version.to_native(),
            expected: TEMPERATURE_ONLY_SCHEMA_VERSION_VALUE,
        });
    }
    let expected = usize::try_from(expected_rows)
        .map_err(|err| TransportError::MalformedArchive(err.to_string()))?;
    if archived.rows.len() != expected {
        return Err(TransportError::RowCountMismatch {
            observed: archived.rows.len(),
            expected: expected_rows,
        });
    }
    temperature_only_validate_archived_rows(archived)
}

fn temperature_only_validate_archived_rows(
    archived: &ArchivedTelemetryResponseV1PayloadTemperatureOnly,
) -> Result<()> {
    let mut previous = None;
    for archived_row in archived.rows.iter() {
        let row = temperature_only_row_from_archived(archived_row);
        temperature_only_validate_row(&row, previous.as_ref())?;
        previous = Some(row);
    }
    Ok(())
}

fn temperature_only_inspect_archived_rows(
    archived: &ArchivedTelemetryResponseV1PayloadTemperatureOnly,
) -> Result<BinaryInspection> {
    let mut previous = None;
    let mut semantic_checksum = fnv1a64("mbt.example.telemetry.v1.temperature_only".as_bytes());
    let mut minimal_projection_checksum = semantic_checksum;
    for archived_row in archived.rows.iter() {
        let row = temperature_only_row_from_archived(archived_row);
        temperature_only_validate_row(&row, previous.as_ref())?;
        semantic_checksum =
            temperature_only_checksum_archived_row(semantic_checksum, archived_row, true);
        minimal_projection_checksum = temperature_only_minimal_projection_archived_row(
            minimal_projection_checksum,
            archived_row,
        );
        previous = Some(row);
    }
    Ok(BinaryInspection {
        row_count: archived.rows.len(),
        semantic_checksum,
        minimal_projection_checksum,
    })
}

fn temperature_only_row_from_archived(
    row: &<TelemetryRowV1TemperatureOnly as Archive>::Archived,
) -> TelemetryRowV1TemperatureOnly {
    TelemetryRowV1TemperatureOnly {
        schema_version: row.schema_version.to_native(),
        device_ordinal: row.device_ordinal.to_native(),
        recorded_at_ms: row.recorded_at_ms.to_native(),
        temperature_c: row.temperature_c.to_native(),
    }
}
#[derive(Archive, RkyvSerialize)]
struct TelemetryV1TemperatureOnlyProjectionPayloadRef<'a> {
    schema_version: u16,
    rows: TelemetryV1TemperatureOnlyProjectionRowsRef<'a>,
}

struct TelemetryV1TemperatureOnlyProjectionRowsRef<'a> {
    rows: &'a ArchivedVec<<TelemetryRowV1 as Archive>::Archived>,
}

impl<'a> Archive for TelemetryV1TemperatureOnlyProjectionRowsRef<'a> {
    type Archived = ArchivedVec<<TelemetryV1TemperatureOnlyProjectionRowRef as Archive>::Archived>;
    type Resolver = VecResolver;
    fn resolve(&self, resolver: Self::Resolver, out: Place<Self::Archived>) {
        ArchivedVec::resolve_from_len(self.rows.len(), resolver, out);
    }
}

impl<'a, S> RkyvSerialize<S> for TelemetryV1TemperatureOnlyProjectionRowsRef<'a>
where
    S: Fallible + Allocator + Writer + ?Sized,
    S::Error: Source,
{
    fn serialize(&self, serializer: &mut S) -> std::result::Result<Self::Resolver, S::Error> {
        ArchivedVec::serialize_from_iter::<TelemetryV1TemperatureOnlyProjectionRowRef, _, _>(
            TelemetryV1TemperatureOnlyProjectionRowsIter {
                inner: self.rows.as_slice().iter(),
            },
            serializer,
        )
    }
}

#[derive(Clone)]
struct TelemetryV1TemperatureOnlyProjectionRowsIter<'a> {
    inner: core::slice::Iter<'a, <TelemetryRowV1 as Archive>::Archived>,
}

impl<'a> Iterator for TelemetryV1TemperatureOnlyProjectionRowsIter<'a> {
    type Item = TelemetryV1TemperatureOnlyProjectionRowRef;
    fn next(&mut self) -> Option<Self::Item> {
        let source = self.inner.next()?;
        Some(TelemetryV1TemperatureOnlyProjectionRowRef {
            schema_version: source.schema_version.to_native(),
            device_ordinal: source.device_ordinal.to_native(),
            recorded_at_ms: source.recorded_at_ms.to_native(),
            temperature_c: source.temperature_c.to_native(),
        })
    }
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.inner.size_hint()
    }
}

impl<'a> ExactSizeIterator for TelemetryV1TemperatureOnlyProjectionRowsIter<'a> {
    fn len(&self) -> usize {
        self.inner.len()
    }
}

#[derive(Archive, RkyvSerialize)]
struct TelemetryV1TemperatureOnlyProjectionRowRef {
    schema_version: u16,
    device_ordinal: u16,
    recorded_at_ms: i64,
    temperature_c: f64,
}

const _: fn(&ArchivedTelemetryResponseV1Payload, usize) -> Result<Vec<u8>> =
    project_temperature_only_archived_direct;

impl TelemetryV1 {
    pub fn project_temperature_only(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        project_temperature_only_archived_direct(archived, max_response_bytes)
    }

    /// Projects immutable source bytes already validated for this schema.
    ///
    /// # Safety
    /// The caller guarantees that bytes were previously accepted by checked MBT access
    /// for the source schema and then stored or transported without mutation.
    pub unsafe fn project_temperature_only_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        project_temperature_only_archived_direct(archived, max_response_bytes)
    }
}

fn project_temperature_only_archived_direct(
    archived: &ArchivedTelemetryResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let row_count = archived.rows.len() as u64;
    let payload = TelemetryV1TemperatureOnlyProjectionPayloadRef {
        schema_version: TEMPERATURE_ONLY_SCHEMA_VERSION_VALUE,
        rows: TelemetryV1TemperatureOnlyProjectionRowsRef {
            rows: &archived.rows,
        },
    };
    let payload_bytes = rkyv::to_bytes::<RkyvError>(&payload)
        .map_err(|_err| TransportError::MalformedArchive(String::new()))?;
    let payload_len = payload_bytes.len();
    let total_len =
        HEADER_LEN
            .checked_add(payload_len)
            .ok_or(TransportError::ResponseTooLarge {
                observed: usize::MAX,
                cap: max_response_bytes,
            })?;
    if total_len > max_response_bytes {
        return Err(TransportError::ResponseTooLarge {
            observed: total_len,
            cap: max_response_bytes,
        });
    }
    let header = TransportHeader::new_with_schema(
        TelemetryV1TemperatureOnly::header_spec(),
        row_count,
        payload_len as u64,
        fnv1a64(&payload_bytes),
    );
    let mut header_bytes = [0_u8; HEADER_LEN];
    encode_header(&header, &mut header_bytes);
    let mut out = Vec::with_capacity(total_len);
    out.extend_from_slice(&header_bytes);
    out.extend_from_slice(&payload_bytes);
    Ok(out)
}
