// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=50001 schema_version=1 schema_hash=232196938863914698

use crate::telemetry_v1::*;
use mbt_adapter_csv::CsvWriter;
use mbt_core::error::Result;
use mbt_metamorphose::{CsvMetamorphoseSchema, runtime::TrustedUnchecked};
use rkyv::Archive;

const CSV_HEADER: &[u8] = b"schema_version,device,recorded_at_ms,recorded_at_utc,temperature_c,battery_percent,status,tags";

impl TelemetryV1 {
    pub fn metamorphose_csv(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        write_csv_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into CSV.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_csv_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        write_csv_response(archived, max_response_bytes)
    }
}

impl CsvMetamorphoseSchema for TelemetryV1 {
    fn metamorphose_csv(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_csv(bytes, max_response_bytes)
    }
    fn metamorphose_csv_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_csv_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn write_csv_response(
    archived: &ArchivedTelemetryResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = CsvWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.raw_static(CSV_HEADER)?;
    writer.newline()?;
    for row in archived.rows.iter() {
        write_csv_row(row, &mut writer)?;
    }
    Ok(writer.finish())
}

fn write_csv_row(
    row: &<TelemetryRowV1 as Archive>::Archived,
    writer: &mut CsvWriter,
) -> Result<()> {
    writer.u32_cell(u32::from(1_u16))?;
    writer.comma()?;
    writer.string_cell(device_symbol(row.device_ordinal.to_native())?)?;
    writer.comma()?;
    writer.i64_cell(row.recorded_at_ms.to_native())?;
    writer.comma()?;
    writer.utc_cell(row.recorded_at_ms.to_native())?;
    writer.comma()?;
    writer.f64_cell("temperature_c", row.temperature_c.to_native())?;
    writer.comma()?;
    if row.presence_bits.to_native() & PRESENCE_BATTERY_PERCENT != 0 {
        writer.f64_cell("battery_percent", row.battery_percent.to_native())?;
    }
    writer.comma()?;
    writer.string_cell(status_symbol(row.status_ordinal.to_native())?)?;
    writer.comma()?;
    write_csv_tag_bitmask(row.tags_mask.to_native(), writer)?;
    writer.newline()
}

fn write_csv_tag_bitmask(mask: u64, writer: &mut CsvWriter) -> Result<()> {
    writer.begin_array_cell()?;
    let mut first = true;
    if mask & (1_u64 << 0) != 0 {
        if first {
            first = false;
        } else {
            writer.array_cell_comma()?;
        }
        writer.array_string_cell("indoor")?;
    }
    if mask & (1_u64 << 1) != 0 {
        if first {
            first = false;
        } else {
            writer.array_cell_comma()?;
        }
        writer.array_string_cell("outdoor")?;
    }
    if mask & (1_u64 << 2) != 0 {
        if first {
            first = false;
        } else {
            writer.array_cell_comma()?;
        }
        writer.array_string_cell("test")?;
    }
    let _ = first;
    writer.end_array_cell()
}

const TEMPERATURE_ONLY_CSV_HEADER: &[u8] =
    b"schema_version,device,recorded_at_ms,recorded_at_utc,temperature_c";

impl TelemetryV1TemperatureOnly {
    pub fn metamorphose_csv(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        temperature_only_write_csv_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into CSV.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_csv_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        temperature_only_write_csv_response(archived, max_response_bytes)
    }
}

impl CsvMetamorphoseSchema for TelemetryV1TemperatureOnly {
    fn metamorphose_csv(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_csv(bytes, max_response_bytes)
    }
    fn metamorphose_csv_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_csv_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn temperature_only_write_csv_response(
    archived: &ArchivedTelemetryResponseV1PayloadTemperatureOnly,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = CsvWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.raw_static(TEMPERATURE_ONLY_CSV_HEADER)?;
    writer.newline()?;
    for row in archived.rows.iter() {
        temperature_only_write_csv_row(row, &mut writer)?;
    }
    Ok(writer.finish())
}

fn temperature_only_write_csv_row(
    row: &<TelemetryRowV1TemperatureOnly as Archive>::Archived,
    writer: &mut CsvWriter,
) -> Result<()> {
    writer.u32_cell(u32::from(1_u16))?;
    writer.comma()?;
    writer.string_cell(device_symbol(row.device_ordinal.to_native())?)?;
    writer.comma()?;
    writer.i64_cell(row.recorded_at_ms.to_native())?;
    writer.comma()?;
    writer.utc_cell(row.recorded_at_ms.to_native())?;
    writer.comma()?;
    writer.f64_cell("temperature_c", row.temperature_c.to_native())?;
    writer.newline()
}
