// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=50001 schema_version=1 schema_hash=232196938863914698

use crate::telemetry_v1::*;
use crate::telemetry_v1_transponding::*;
use mbt_adapter_arrow::{
    ArrowArrayRef, ArrowDataType, ArrowField, ArrowRecordBatch, ArrowSchema, field_metadata,
    record_batch,
};
use mbt_core::error::Result;
use mbt_metamorphose::{ArrowMetamorphoseSchema, runtime::TrustedUnchecked};
use std::sync::Arc;

impl TelemetryV1 {
    pub fn metamorphose_arrow(bytes: &[u8], max_response_bytes: usize) -> Result<ArrowRecordBatch> {
        let archived = Self::access_archived(bytes)?;
        let batch = Self::transpond_archived(archived, max_response_bytes)?;
        arrow_record_batch(batch, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into Arrow.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_arrow_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<ArrowRecordBatch> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        let batch = Self::transpond_archived(archived, max_response_bytes)?;
        arrow_record_batch(batch, max_response_bytes)
    }
}

impl ArrowMetamorphoseSchema for TelemetryV1 {
    type RecordBatch = ArrowRecordBatch;
    fn metamorphose_arrow(bytes: &[u8], max_response_bytes: usize) -> Result<Self::RecordBatch> {
        Self::metamorphose_arrow(bytes, max_response_bytes)
    }
    fn metamorphose_arrow_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Self::RecordBatch> {
        unsafe { Self::metamorphose_arrow_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn arrow_record_batch(
    batch: TelemetryV1ColumnBatch,
    max_response_bytes: usize,
) -> Result<ArrowRecordBatch> {
    let schema = Arc::new(ArrowSchema::new(vec![
        ArrowField::new("schema_version", ArrowDataType::UInt16, false).with_metadata(
            field_metadata("schema_version", "schema_version", None, None),
        ),
        ArrowField::new("device", ArrowDataType::UInt16, false).with_metadata(field_metadata(
            "device",
            "device_ordinal",
            Some("device"),
            None,
        )),
        ArrowField::new("recorded_at_ms", ArrowDataType::Int64, false).with_metadata(
            field_metadata("recorded_at_ms", "recorded_at_ms", None, None),
        ),
        ArrowField::new("temperature_c", ArrowDataType::Float64, false)
            .with_metadata(field_metadata("temperature_c", "temperature_c", None, None)),
        ArrowField::new("battery_percent", ArrowDataType::Float64, true).with_metadata(
            field_metadata("battery_percent", "battery_percent", None, None),
        ),
        ArrowField::new("status", ArrowDataType::UInt16, false).with_metadata(field_metadata(
            "status",
            "status_ordinal",
            Some("status"),
            None,
        )),
        ArrowField::new("tags", ArrowDataType::UInt64, false).with_metadata(field_metadata(
            "tags",
            "tags_mask",
            None,
            Some("tag"),
        )),
    ]));
    let columns: Vec<ArrowArrayRef> = vec![
        mbt_adapter_arrow::const_u16_array(batch.schema_version)?,
        mbt_adapter_arrow::u16_array(batch.device_ordinal)?,
        mbt_adapter_arrow::i64_array(batch.recorded_at_ms)?,
        mbt_adapter_arrow::f64_array(batch.temperature_c)?,
        mbt_adapter_arrow::optional_f64_array(batch.battery_percent)?,
        mbt_adapter_arrow::u16_array(batch.status_ordinal)?,
        mbt_adapter_arrow::u64_array(batch.tags_mask)?,
    ];
    record_batch(schema, columns, max_response_bytes)
}

impl TelemetryV1TemperatureOnly {
    pub fn metamorphose_arrow(bytes: &[u8], max_response_bytes: usize) -> Result<ArrowRecordBatch> {
        let archived = Self::access_archived(bytes)?;
        let batch = Self::transpond_archived(archived, max_response_bytes)?;
        temperature_only_arrow_record_batch(batch, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into Arrow.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_arrow_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<ArrowRecordBatch> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        let batch = Self::transpond_archived(archived, max_response_bytes)?;
        temperature_only_arrow_record_batch(batch, max_response_bytes)
    }
}

impl ArrowMetamorphoseSchema for TelemetryV1TemperatureOnly {
    type RecordBatch = ArrowRecordBatch;
    fn metamorphose_arrow(bytes: &[u8], max_response_bytes: usize) -> Result<Self::RecordBatch> {
        Self::metamorphose_arrow(bytes, max_response_bytes)
    }
    fn metamorphose_arrow_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Self::RecordBatch> {
        unsafe { Self::metamorphose_arrow_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn temperature_only_arrow_record_batch(
    batch: TelemetryV1TemperatureOnlyColumnBatch,
    max_response_bytes: usize,
) -> Result<ArrowRecordBatch> {
    let schema = Arc::new(ArrowSchema::new(vec![
        ArrowField::new("schema_version", ArrowDataType::UInt16, false).with_metadata(
            field_metadata("schema_version", "schema_version", None, None),
        ),
        ArrowField::new("device", ArrowDataType::UInt16, false).with_metadata(field_metadata(
            "device",
            "device_ordinal",
            Some("device"),
            None,
        )),
        ArrowField::new("recorded_at_ms", ArrowDataType::Int64, false).with_metadata(
            field_metadata("recorded_at_ms", "recorded_at_ms", None, None),
        ),
        ArrowField::new("temperature_c", ArrowDataType::Float64, false)
            .with_metadata(field_metadata("temperature_c", "temperature_c", None, None)),
    ]));
    let columns: Vec<ArrowArrayRef> = vec![
        mbt_adapter_arrow::const_u16_array(batch.schema_version)?,
        mbt_adapter_arrow::u16_array(batch.device_ordinal)?,
        mbt_adapter_arrow::i64_array(batch.recorded_at_ms)?,
        mbt_adapter_arrow::f64_array(batch.temperature_c)?,
    ];
    record_batch(schema, columns, max_response_bytes)
}
