// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=50001 schema_version=1 schema_hash=232196938863914698

use crate::telemetry_v1::*;
use mbt_adapter_protobuf::{self as proto, ProtoWriter};
use mbt_core::error::Result;
use mbt_core::output;
use mbt_metamorphose::{ProtobufMetamorphoseSchema, runtime::TrustedUnchecked};
use rkyv::Archive;

impl TelemetryV1 {
    pub fn metamorphose_protobuf(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        write_protobuf_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into protobuf.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_protobuf_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        write_protobuf_response(archived, max_response_bytes)
    }
}

impl ProtobufMetamorphoseSchema for TelemetryV1 {
    fn metamorphose_protobuf(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_protobuf(bytes, max_response_bytes)
    }
    fn metamorphose_protobuf_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_protobuf_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn write_protobuf_response(
    archived: &ArchivedTelemetryResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = ProtoWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.uint32(1, u32::from(SCHEMA_VERSION_VALUE))?;
    for row in archived.rows.iter() {
        let row_len = encoded_len_row(row, max_response_bytes)?;
        writer.message_prefix(2, row_len)?;
        write_protobuf_row(row, &mut writer)?;
    }
    Ok(writer.finish())
}

fn encoded_len_row(
    row: &<TelemetryRowV1 as Archive>::Archived,
    max_response_bytes: usize,
) -> Result<usize> {
    let mut len = 0_usize;
    len = output::checked_len_add(
        len,
        proto::encoded_len_uint32(1, u32::from(1_u16)),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_string(2, device_symbol(row.device_ordinal.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_int64(3, row.recorded_at_ms.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_message(4, output::utc_len(row.recorded_at_ms.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(5, row.temperature_c.to_native()),
        max_response_bytes,
    )?;
    if row.presence_bits.to_native() & PRESENCE_BATTERY_PERCENT != 0 {
        len = output::checked_len_add(
            len,
            proto::encoded_len_double(6, row.battery_percent.to_native()),
            max_response_bytes,
        )?;
    }
    len = output::checked_len_add(
        len,
        output::encoded_len_string(7, status_symbol(row.status_ordinal.to_native())?),
        max_response_bytes,
    )?;
    if row.tags_mask.to_native() & (1_u64 << 0) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(8, "indoor"),
            max_response_bytes,
        )?;
    }
    if row.tags_mask.to_native() & (1_u64 << 1) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(8, "outdoor"),
            max_response_bytes,
        )?;
    }
    if row.tags_mask.to_native() & (1_u64 << 2) != 0 {
        len = output::checked_len_add(
            len,
            output::encoded_len_string(8, "test"),
            max_response_bytes,
        )?;
    }
    Ok(len)
}

fn write_protobuf_row(
    row: &<TelemetryRowV1 as Archive>::Archived,
    writer: &mut ProtoWriter,
) -> Result<()> {
    writer.uint32(1, u32::from(1_u16))?;
    writer.string(2, device_symbol(row.device_ordinal.to_native())?)?;
    writer.int64(3, row.recorded_at_ms.to_native())?;
    writer.utc(4, row.recorded_at_ms.to_native())?;
    writer.double(5, "temperature_c", row.temperature_c.to_native())?;
    if row.presence_bits.to_native() & PRESENCE_BATTERY_PERCENT != 0 {
        writer.double(6, "battery_percent", row.battery_percent.to_native())?;
    }
    writer.string(7, status_symbol(row.status_ordinal.to_native())?)?;
    if row.tags_mask.to_native() & (1_u64 << 0) != 0 {
        writer.string(8, "indoor")?;
    }
    if row.tags_mask.to_native() & (1_u64 << 1) != 0 {
        writer.string(8, "outdoor")?;
    }
    if row.tags_mask.to_native() & (1_u64 << 2) != 0 {
        writer.string(8, "test")?;
    }
    Ok(())
}

impl TelemetryV1TemperatureOnly {
    pub fn metamorphose_protobuf(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        temperature_only_write_protobuf_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into protobuf.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_protobuf_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        temperature_only_write_protobuf_response(archived, max_response_bytes)
    }
}

impl ProtobufMetamorphoseSchema for TelemetryV1TemperatureOnly {
    fn metamorphose_protobuf(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_protobuf(bytes, max_response_bytes)
    }
    fn metamorphose_protobuf_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_protobuf_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn temperature_only_write_protobuf_response(
    archived: &ArchivedTelemetryResponseV1PayloadTemperatureOnly,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = ProtoWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.uint32(1, u32::from(SCHEMA_VERSION_VALUE))?;
    for row in archived.rows.iter() {
        let row_len = temperature_only_encoded_len_row(row, max_response_bytes)?;
        writer.message_prefix(2, row_len)?;
        temperature_only_write_protobuf_row(row, &mut writer)?;
    }
    Ok(writer.finish())
}

fn temperature_only_encoded_len_row(
    row: &<TelemetryRowV1TemperatureOnly as Archive>::Archived,
    max_response_bytes: usize,
) -> Result<usize> {
    let mut len = 0_usize;
    len = output::checked_len_add(
        len,
        proto::encoded_len_uint32(1, u32::from(1_u16)),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_string(2, device_symbol(row.device_ordinal.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_int64(3, row.recorded_at_ms.to_native()),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        output::encoded_len_message(4, output::utc_len(row.recorded_at_ms.to_native())?),
        max_response_bytes,
    )?;
    len = output::checked_len_add(
        len,
        proto::encoded_len_double(5, row.temperature_c.to_native()),
        max_response_bytes,
    )?;
    Ok(len)
}

fn temperature_only_write_protobuf_row(
    row: &<TelemetryRowV1TemperatureOnly as Archive>::Archived,
    writer: &mut ProtoWriter,
) -> Result<()> {
    writer.uint32(1, u32::from(1_u16))?;
    writer.string(2, device_symbol(row.device_ordinal.to_native())?)?;
    writer.int64(3, row.recorded_at_ms.to_native())?;
    writer.utc(4, row.recorded_at_ms.to_native())?;
    writer.double(5, "temperature_c", row.temperature_c.to_native())?;
    Ok(())
}
