// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=50002 schema_version=1 schema_hash=9409304714461393349

use crate::measurement_v1::*;
use mbt_adapter_json::JsonWriter;
use mbt_core::error::Result;
use mbt_metamorphose::{JsonMetamorphoseSchema, runtime::TrustedUnchecked};
use rkyv::Archive;

const JSON_SCHEMA_VERSION_FIELD: &[u8] = b"\"schema_version\":";
const JSON_ROWS_FIELD: &[u8] = b"\"rows\":";
const JSON_FIELD_SCHEMA_VERSION: &[u8] = b"\"schema_version\":";
const JSON_FIELD_DEVICE_ORDINAL: &[u8] = b"\"device\":";
const JSON_FIELD_INTERVAL_ORDINAL: &[u8] = b"\"interval\":";
const JSON_FIELD_STARTED_AT_MS: &[u8] = b"\"started_at_ms\":";
const JSON_FIELD_RECORDED_AT_MS: &[u8] = b"\"recorded_at_ms\":";
const JSON_FIELD_STARTED_AT_UTC: &[u8] = b"\"started_at_utc\":";
const JSON_FIELD_RECORDED_AT_UTC: &[u8] = b"\"recorded_at_utc\":";
const JSON_FIELD_VALUE_A: &[u8] = b"\"value_a\":";
const JSON_FIELD_VALUE_B: &[u8] = b"\"value_b\":";
const JSON_FIELD_VALUE_C: &[u8] = b"\"value_c\":";
const JSON_FIELD_VALUE_D: &[u8] = b"\"value_d\":";
const JSON_FIELD_VALUE_E: &[u8] = b"\"value_e\":";
const JSON_FIELD_VALUE_F: &[u8] = b"\"value_f\":";
const JSON_FIELD_VALUE_G: &[u8] = b"\"value_g\":";
const JSON_FIELD_VALUE_H: &[u8] = b"\"value_h\":";
const JSON_FIELD_VALUE_I: &[u8] = b"\"value_i\":";
const JSON_FIELD_VALUE_J: &[u8] = b"\"value_j\":";
const JSON_FIELD_COUNT_A: &[u8] = b"\"count_a\":";
const JSON_FIELD_COUNT_B: &[u8] = b"\"count_b\":";
const JSON_FIELD_AVERAGE_VALUE: &[u8] = b"\"average_value\":";
const JSON_FIELD_SAMPLE_COUNT: &[u8] = b"\"sample_count\":";
const JSON_FIELD_SOURCE_ORDINAL: &[u8] = b"\"metadata.source\":";
const JSON_FIELD_PROCESS_ORDINAL: &[u8] = b"\"metadata.process\":";
const JSON_FIELD_SITES_EXPECTED_MASK: &[u8] = b"\"metadata.sites_expected\":";
const JSON_FIELD_SITES_OBSERVED_MASK: &[u8] = b"\"metadata.sites_observed\":";
const JSON_FIELD_INGESTED_AT_MS: &[u8] = b"\"metadata.ingested_at_ms\":";
const JSON_FIELD_INGESTED_AT_UTC: &[u8] = b"\"metadata.ingested_at_utc\":";
const JSON_FIELD_TARGET_INGESTED_AT_MS: &[u8] = b"\"metadata.target_ingested_at_ms\":";
const JSON_FIELD_TARGET_INGESTED_AT_UTC: &[u8] = b"\"metadata.target_ingested_at_utc\":";
const JSON_FIELD_BUILT_AT_MS: &[u8] = b"\"metadata.built_at_ms\":";
const JSON_FIELD_BUILT_AT_UTC: &[u8] = b"\"metadata.built_at_utc\":";
const JSON_FIELD_COMMITTED_AT_MS: &[u8] = b"\"metadata.committed_at_ms\":";
const JSON_FIELD_COMMITTED_AT_UTC: &[u8] = b"\"metadata.committed_at_utc\":";
const JSON_FIELD_HARMONIZED_AT_MS: &[u8] = b"\"metadata.harmonized_at_ms\":";
const JSON_FIELD_HARMONIZED_AT_UTC: &[u8] = b"\"metadata.harmonized_at_utc\":";
const JSON_FIELD_RECOMPUTED_AT_MS: &[u8] = b"\"metadata.recomputed_at_ms\":";
const JSON_FIELD_RECOMPUTED_AT_UTC: &[u8] = b"\"metadata.recomputed_at_utc\":";
const JSON_FIELD_RECOMPUTED_REASON_ORDINAL: &[u8] = b"\"metadata.recomputed_reason\":";
const JSON_FIELD_COVERED_INTERVAL_COUNT: &[u8] = b"\"metadata.covered_interval_count\":";
const JSON_FIELD_EXPECTED_INTERVAL_COUNT: &[u8] = b"\"metadata.expected_interval_count\":";
const JSON_FIELD_COVERAGE_RATIO: &[u8] = b"\"metadata.coverage_ratio\":";
const JSON_FIELD_INPUTS_SOURCE_COUNTS_SENSOR: &[u8] = b"\"metadata.inputs_source_counts_sensor\":";
const JSON_FIELD_INPUTS_SOURCE_COUNTS_API: &[u8] = b"\"metadata.inputs_source_counts_api\":";
const JSON_FIELD_INPUTS_SOURCE_COUNTS_SYNTHETIC: &[u8] =
    b"\"metadata.inputs_source_counts_synthetic\":";
const JSON_FIELD_INPUTS_SOURCE_COUNTS_CORRECTED: &[u8] =
    b"\"metadata.inputs_source_counts_corrected\":";
const JSON_FIELD_SENSOR_WINDOW_INPUTS_COVERAGE_RATIO: &[u8] =
    b"\"metadata.sensor_window_inputs_coverage_ratio\":";
const JSON_FIELD_SENSOR_WINDOW_EXPECTED: &[u8] = b"\"metadata.sensor_window_expected\":";
const JSON_FIELD_SENSOR_WINDOW_SYNTHETIC_COUNT: &[u8] =
    b"\"metadata.sensor_window_synthetic_count\":";
const JSON_FIELD_SENSOR_WINDOW_SYNTHETIC_RATIO: &[u8] =
    b"\"metadata.sensor_window_synthetic_ratio\":";
const JSON_FIELD_SENSOR_WINDOW_OBSERVED_COUNT: &[u8] =
    b"\"metadata.sensor_window_observed_count\":";
const JSON_FIELD_SENSOR_WINDOW_OBSERVED_RATIO: &[u8] =
    b"\"metadata.sensor_window_observed_ratio\":";
const JSON_FIELD_AGE_MS: &[u8] = b"\"age_ms\":";

impl MeasurementV1 {
    pub fn metamorphose_json(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        write_json_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into JSON.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_json_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        write_json_response(archived, max_response_bytes)
    }
}

impl JsonMetamorphoseSchema for MeasurementV1 {
    fn metamorphose_json(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_json(bytes, max_response_bytes)
    }
    fn metamorphose_json_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_json_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn write_json_response(
    archived: &ArchivedMeasurementResponseV1Payload,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = JsonWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.begin_object()?;
    writer.raw_static(JSON_SCHEMA_VERSION_FIELD)?;
    writer.u32_value(u32::from(SCHEMA_VERSION_VALUE))?;
    writer.comma()?;
    writer.raw_static(JSON_ROWS_FIELD)?;
    writer.begin_array()?;
    let mut first_row = true;
    for row in archived.rows.iter() {
        if first_row {
            first_row = false;
        } else {
            writer.comma()?;
        }
        write_json_row(row, &mut writer)?;
    }
    writer.end_array()?;
    writer.end_object()?;
    Ok(writer.finish())
}

fn write_json_row(
    row: &<MeasurementRowV1 as Archive>::Archived,
    writer: &mut JsonWriter,
) -> Result<()> {
    writer.begin_object()?;
    let mut first = true;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_SCHEMA_VERSION)?;
    writer.u32_value(u32::from(1_u16))?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_DEVICE_ORDINAL)?;
    writer.string_value(device_symbol(row.device_ordinal.to_native())?)?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_INTERVAL_ORDINAL)?;
    writer.string_value(interval_symbol(row.interval_ordinal.to_native())?)?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_STARTED_AT_MS)?;
    writer.i64_value(row.started_at_ms.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_RECORDED_AT_MS)?;
    writer.i64_value(row.recorded_at_ms.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_STARTED_AT_UTC)?;
    writer.utc_value(row.started_at_ms.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_RECORDED_AT_UTC)?;
    writer.utc_value(row.recorded_at_ms.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_A)?;
    writer.f64_value("value_a", row.value_a.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_B)?;
    writer.f64_value("value_b", row.value_b.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_C)?;
    writer.f64_value("value_c", row.value_c.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_D)?;
    writer.f64_value("value_d", row.value_d.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_E)?;
    writer.f64_value("value_e", row.value_e.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_F)?;
    writer.f64_value("value_f", row.value_f.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_G)?;
    writer.f64_value("value_g", row.value_g.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_H)?;
    writer.f64_value("value_h", row.value_h.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_I)?;
    writer.f64_value("value_i", row.value_i.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_VALUE_J)?;
    writer.f64_value("value_j", row.value_j.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_COUNT_A)?;
    writer.i64_value(row.count_a.to_native())?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_COUNT_B)?;
    writer.i64_value(row.count_b.to_native())?;
    if row.presence_bits.to_native() & PRESENCE_AVERAGE_VALUE != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_AVERAGE_VALUE)?;
        writer.f64_value("average_value", row.average_value.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_SAMPLE_COUNT != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_SAMPLE_COUNT)?;
        writer.i64_value(row.sample_count.to_native())?;
    }
    write_json_field_prefix(writer, &mut first, JSON_FIELD_SOURCE_ORDINAL)?;
    writer.string_value(source_symbol(row.source_ordinal.to_native())?)?;
    if row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_PROCESS_ORDINAL)?;
        writer.string_value(process_symbol(row.process_ordinal.to_native())?)?;
    }
    write_json_field_prefix(writer, &mut first, JSON_FIELD_SITES_EXPECTED_MASK)?;
    write_json_site_bitmask(row.sites_expected_mask.to_native(), writer)?;
    write_json_field_prefix(writer, &mut first, JSON_FIELD_SITES_OBSERVED_MASK)?;
    write_json_site_bitmask(row.sites_observed_mask.to_native(), writer)?;
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_INGESTED_AT_MS)?;
        writer.i64_value(row.ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_INGESTED_AT_UTC)?;
        writer.utc_value(row.ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_TARGET_INGESTED_AT_MS)?;
        writer.i64_value(row.target_ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_TARGET_INGESTED_AT_UTC)?;
        writer.utc_value(row.target_ingested_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_BUILT_AT_MS)?;
        writer.i64_value(row.built_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_BUILT_AT_UTC)?;
        writer.utc_value(row.built_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_COMMITTED_AT_MS)?;
        writer.i64_value(row.committed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_COMMITTED_AT_UTC)?;
        writer.utc_value(row.committed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_HARMONIZED_AT_MS)?;
        writer.i64_value(row.harmonized_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_HARMONIZED_AT_UTC)?;
        writer.utc_value(row.harmonized_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_RECOMPUTED_AT_MS)?;
        writer.i64_value(row.recomputed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_RECOMPUTED_AT_UTC)?;
        writer.utc_value(row.recomputed_at_ms.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_RECOMPUTED_REASON_ORDINAL)?;
        writer.string_value(recomputed_reason_symbol(
            row.recomputed_reason_ordinal.to_native(),
        )?)?;
    }
    if row.presence_bits.to_native() & PRESENCE_COVERED_INTERVAL_COUNT != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_COVERED_INTERVAL_COUNT)?;
        writer.i64_value(row.covered_interval_count.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_EXPECTED_INTERVAL_COUNT != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_EXPECTED_INTERVAL_COUNT)?;
        writer.i64_value(row.expected_interval_count.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_COVERAGE_RATIO)?;
        writer.f64_value("metadata.coverage_ratio", row.coverage_ratio.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SENSOR != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_INPUTS_SOURCE_COUNTS_SENSOR)?;
        writer.i64_value(row.inputs_source_counts_sensor.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_INPUTS_SOURCE_COUNTS_API)?;
        writer.i64_value(row.inputs_source_counts_api.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0 {
        write_json_field_prefix(
            writer,
            &mut first,
            JSON_FIELD_INPUTS_SOURCE_COUNTS_SYNTHETIC,
        )?;
        writer.i64_value(row.inputs_source_counts_synthetic.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_CORRECTED != 0 {
        write_json_field_prefix(
            writer,
            &mut first,
            JSON_FIELD_INPUTS_SOURCE_COUNTS_CORRECTED,
        )?;
        writer.i64_value(row.inputs_source_counts_corrected.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_INPUTS_COVERAGE_RATIO != 0 {
        write_json_field_prefix(
            writer,
            &mut first,
            JSON_FIELD_SENSOR_WINDOW_INPUTS_COVERAGE_RATIO,
        )?;
        writer.f64_value(
            "metadata.sensor_window_inputs_coverage_ratio",
            row.sensor_window_inputs_coverage_ratio.to_native(),
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_EXPECTED != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_SENSOR_WINDOW_EXPECTED)?;
        writer.i64_value(row.sensor_window_expected.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_SYNTHETIC_COUNT != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_SENSOR_WINDOW_SYNTHETIC_COUNT)?;
        writer.i64_value(row.sensor_window_synthetic_count.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_SYNTHETIC_RATIO != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_SENSOR_WINDOW_SYNTHETIC_RATIO)?;
        writer.f64_value(
            "metadata.sensor_window_synthetic_ratio",
            row.sensor_window_synthetic_ratio.to_native(),
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_OBSERVED_COUNT != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_SENSOR_WINDOW_OBSERVED_COUNT)?;
        writer.i64_value(row.sensor_window_observed_count.to_native())?;
    }
    if row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_OBSERVED_RATIO != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_SENSOR_WINDOW_OBSERVED_RATIO)?;
        writer.f64_value(
            "metadata.sensor_window_observed_ratio",
            row.sensor_window_observed_ratio.to_native(),
        )?;
    }
    if row.presence_bits.to_native() & PRESENCE_AGE_MS != 0 {
        write_json_field_prefix(writer, &mut first, JSON_FIELD_AGE_MS)?;
        writer.i64_value(row.age_ms.to_native())?;
    }
    writer.end_object()
}

fn write_json_site_bitmask(mask: u64, writer: &mut JsonWriter) -> Result<()> {
    writer.begin_array()?;
    let mut first = true;
    if mask & (1_u64 << 0) != 0 {
        if first {
            first = false;
        } else {
            writer.comma()?;
        }
        writer.string_value("site_a")?;
    }
    if mask & (1_u64 << 1) != 0 {
        if first {
            first = false;
        } else {
            writer.comma()?;
        }
        writer.string_value("site_b")?;
    }
    if mask & (1_u64 << 2) != 0 {
        if first {
            first = false;
        } else {
            writer.comma()?;
        }
        writer.string_value("site_c")?;
    }
    let _ = first;
    writer.end_array()
}

fn write_json_field_prefix(
    writer: &mut JsonWriter,
    first: &mut bool,
    field: &'static [u8],
) -> Result<()> {
    if *first {
        *first = false;
    } else {
        writer.comma()?;
    }
    writer.raw_static(field)
}

const WITHOUT_DETAILS_PRESENCE_AVERAGE_VALUE: u64 = 1 << 0;
const WITHOUT_DETAILS_PRESENCE_SAMPLE_COUNT: u64 = 1 << 1;
const WITHOUT_DETAILS_PRESENCE_AGE_MS: u64 = 1 << 2;

const WITHOUT_DETAILS_JSON_SCHEMA_VERSION_FIELD: &[u8] = b"\"schema_version\":";
const WITHOUT_DETAILS_JSON_ROWS_FIELD: &[u8] = b"\"rows\":";
const WITHOUT_DETAILS_JSON_FIELD_SCHEMA_VERSION: &[u8] = b"\"schema_version\":";
const WITHOUT_DETAILS_JSON_FIELD_DEVICE_ORDINAL: &[u8] = b"\"device\":";
const WITHOUT_DETAILS_JSON_FIELD_INTERVAL_ORDINAL: &[u8] = b"\"interval\":";
const WITHOUT_DETAILS_JSON_FIELD_STARTED_AT_MS: &[u8] = b"\"started_at_ms\":";
const WITHOUT_DETAILS_JSON_FIELD_RECORDED_AT_MS: &[u8] = b"\"recorded_at_ms\":";
const WITHOUT_DETAILS_JSON_FIELD_STARTED_AT_UTC: &[u8] = b"\"started_at_utc\":";
const WITHOUT_DETAILS_JSON_FIELD_RECORDED_AT_UTC: &[u8] = b"\"recorded_at_utc\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_A: &[u8] = b"\"value_a\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_B: &[u8] = b"\"value_b\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_C: &[u8] = b"\"value_c\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_D: &[u8] = b"\"value_d\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_E: &[u8] = b"\"value_e\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_F: &[u8] = b"\"value_f\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_G: &[u8] = b"\"value_g\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_H: &[u8] = b"\"value_h\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_I: &[u8] = b"\"value_i\":";
const WITHOUT_DETAILS_JSON_FIELD_VALUE_J: &[u8] = b"\"value_j\":";
const WITHOUT_DETAILS_JSON_FIELD_COUNT_A: &[u8] = b"\"count_a\":";
const WITHOUT_DETAILS_JSON_FIELD_COUNT_B: &[u8] = b"\"count_b\":";
const WITHOUT_DETAILS_JSON_FIELD_AVERAGE_VALUE: &[u8] = b"\"average_value\":";
const WITHOUT_DETAILS_JSON_FIELD_SAMPLE_COUNT: &[u8] = b"\"sample_count\":";
const WITHOUT_DETAILS_JSON_FIELD_AGE_MS: &[u8] = b"\"age_ms\":";

impl MeasurementV1WithoutDetails {
    pub fn metamorphose_json(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        without_details_write_json_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into JSON.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_json_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        without_details_write_json_response(archived, max_response_bytes)
    }
}

impl JsonMetamorphoseSchema for MeasurementV1WithoutDetails {
    fn metamorphose_json(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_json(bytes, max_response_bytes)
    }
    fn metamorphose_json_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_json_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn without_details_write_json_response(
    archived: &ArchivedMeasurementResponseV1PayloadWithoutDetails,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = JsonWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.begin_object()?;
    writer.raw_static(WITHOUT_DETAILS_JSON_SCHEMA_VERSION_FIELD)?;
    writer.u32_value(u32::from(SCHEMA_VERSION_VALUE))?;
    writer.comma()?;
    writer.raw_static(WITHOUT_DETAILS_JSON_ROWS_FIELD)?;
    writer.begin_array()?;
    let mut first_row = true;
    for row in archived.rows.iter() {
        if first_row {
            first_row = false;
        } else {
            writer.comma()?;
        }
        without_details_write_json_row(row, &mut writer)?;
    }
    writer.end_array()?;
    writer.end_object()?;
    Ok(writer.finish())
}

fn without_details_write_json_row(
    row: &<MeasurementRowV1WithoutDetails as Archive>::Archived,
    writer: &mut JsonWriter,
) -> Result<()> {
    writer.begin_object()?;
    let mut first = true;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_SCHEMA_VERSION,
    )?;
    writer.u32_value(u32::from(1_u16))?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_DEVICE_ORDINAL,
    )?;
    writer.string_value(device_symbol(row.device_ordinal.to_native())?)?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_INTERVAL_ORDINAL,
    )?;
    writer.string_value(interval_symbol(row.interval_ordinal.to_native())?)?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_STARTED_AT_MS,
    )?;
    writer.i64_value(row.started_at_ms.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_RECORDED_AT_MS,
    )?;
    writer.i64_value(row.recorded_at_ms.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_STARTED_AT_UTC,
    )?;
    writer.utc_value(row.started_at_ms.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_RECORDED_AT_UTC,
    )?;
    writer.utc_value(row.recorded_at_ms.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_A,
    )?;
    writer.f64_value("value_a", row.value_a.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_B,
    )?;
    writer.f64_value("value_b", row.value_b.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_C,
    )?;
    writer.f64_value("value_c", row.value_c.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_D,
    )?;
    writer.f64_value("value_d", row.value_d.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_E,
    )?;
    writer.f64_value("value_e", row.value_e.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_F,
    )?;
    writer.f64_value("value_f", row.value_f.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_G,
    )?;
    writer.f64_value("value_g", row.value_g.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_H,
    )?;
    writer.f64_value("value_h", row.value_h.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_I,
    )?;
    writer.f64_value("value_i", row.value_i.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_VALUE_J,
    )?;
    writer.f64_value("value_j", row.value_j.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_COUNT_A,
    )?;
    writer.i64_value(row.count_a.to_native())?;
    without_details_write_json_field_prefix(
        writer,
        &mut first,
        WITHOUT_DETAILS_JSON_FIELD_COUNT_B,
    )?;
    writer.i64_value(row.count_b.to_native())?;
    if row.presence_bits.to_native() & WITHOUT_DETAILS_PRESENCE_AVERAGE_VALUE != 0 {
        without_details_write_json_field_prefix(
            writer,
            &mut first,
            WITHOUT_DETAILS_JSON_FIELD_AVERAGE_VALUE,
        )?;
        writer.f64_value("average_value", row.average_value.to_native())?;
    }
    if row.presence_bits.to_native() & WITHOUT_DETAILS_PRESENCE_SAMPLE_COUNT != 0 {
        without_details_write_json_field_prefix(
            writer,
            &mut first,
            WITHOUT_DETAILS_JSON_FIELD_SAMPLE_COUNT,
        )?;
        writer.i64_value(row.sample_count.to_native())?;
    }
    if row.presence_bits.to_native() & WITHOUT_DETAILS_PRESENCE_AGE_MS != 0 {
        without_details_write_json_field_prefix(
            writer,
            &mut first,
            WITHOUT_DETAILS_JSON_FIELD_AGE_MS,
        )?;
        writer.i64_value(row.age_ms.to_native())?;
    }
    writer.end_object()
}

fn without_details_write_json_field_prefix(
    writer: &mut JsonWriter,
    first: &mut bool,
    field: &'static [u8],
) -> Result<()> {
    if *first {
        *first = false;
    } else {
        writer.comma()?;
    }
    writer.raw_static(field)
}

const VALUES_ONLY_JSON_SCHEMA_VERSION_FIELD: &[u8] = b"\"schema_version\":";
const VALUES_ONLY_JSON_ROWS_FIELD: &[u8] = b"\"rows\":";
const VALUES_ONLY_JSON_FIELD_SCHEMA_VERSION: &[u8] = b"\"schema_version\":";
const VALUES_ONLY_JSON_FIELD_DEVICE_ORDINAL: &[u8] = b"\"device\":";
const VALUES_ONLY_JSON_FIELD_INTERVAL_ORDINAL: &[u8] = b"\"interval\":";
const VALUES_ONLY_JSON_FIELD_STARTED_AT_MS: &[u8] = b"\"started_at_ms\":";
const VALUES_ONLY_JSON_FIELD_RECORDED_AT_MS: &[u8] = b"\"recorded_at_ms\":";
const VALUES_ONLY_JSON_FIELD_STARTED_AT_UTC: &[u8] = b"\"started_at_utc\":";
const VALUES_ONLY_JSON_FIELD_RECORDED_AT_UTC: &[u8] = b"\"recorded_at_utc\":";
const VALUES_ONLY_JSON_FIELD_VALUE_A: &[u8] = b"\"value_a\":";
const VALUES_ONLY_JSON_FIELD_VALUE_B: &[u8] = b"\"value_b\":";
const VALUES_ONLY_JSON_FIELD_VALUE_C: &[u8] = b"\"value_c\":";
const VALUES_ONLY_JSON_FIELD_VALUE_D: &[u8] = b"\"value_d\":";
const VALUES_ONLY_JSON_FIELD_VALUE_E: &[u8] = b"\"value_e\":";

impl MeasurementV1ValuesOnly {
    pub fn metamorphose_json(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        let archived = Self::access_archived(bytes)?;
        values_only_write_json_response(archived, max_response_bytes)
    }

    /// Metamorphoses immutable bytes already validated for this schema into JSON.
    ///
    /// # Safety
    /// The caller guarantees checked schema validation happened before immutable storage or transport.
    pub unsafe fn metamorphose_json_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
    ) -> Result<Vec<u8>> {
        let archived = unsafe { Self::access_archived_trusted_unchecked(bytes)? };
        values_only_write_json_response(archived, max_response_bytes)
    }
}

impl JsonMetamorphoseSchema for MeasurementV1ValuesOnly {
    fn metamorphose_json(bytes: &[u8], max_response_bytes: usize) -> Result<Vec<u8>> {
        Self::metamorphose_json(bytes, max_response_bytes)
    }
    fn metamorphose_json_trusted_unchecked(
        bytes: &[u8],
        max_response_bytes: usize,
        _trusted: TrustedUnchecked,
    ) -> Result<Vec<u8>> {
        unsafe { Self::metamorphose_json_trusted_unchecked(bytes, max_response_bytes) }
    }
}

fn values_only_write_json_response(
    archived: &ArchivedMeasurementResponseV1PayloadValuesOnly,
    max_response_bytes: usize,
) -> Result<Vec<u8>> {
    let mut writer = JsonWriter::with_capacity(max_response_bytes, max_response_bytes.min(4096));
    writer.begin_object()?;
    writer.raw_static(VALUES_ONLY_JSON_SCHEMA_VERSION_FIELD)?;
    writer.u32_value(u32::from(SCHEMA_VERSION_VALUE))?;
    writer.comma()?;
    writer.raw_static(VALUES_ONLY_JSON_ROWS_FIELD)?;
    writer.begin_array()?;
    let mut first_row = true;
    for row in archived.rows.iter() {
        if first_row {
            first_row = false;
        } else {
            writer.comma()?;
        }
        values_only_write_json_row(row, &mut writer)?;
    }
    writer.end_array()?;
    writer.end_object()?;
    Ok(writer.finish())
}

fn values_only_write_json_row(
    row: &<MeasurementRowV1ValuesOnly as Archive>::Archived,
    writer: &mut JsonWriter,
) -> Result<()> {
    writer.begin_object()?;
    let mut first = true;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_SCHEMA_VERSION)?;
    writer.u32_value(u32::from(1_u16))?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_DEVICE_ORDINAL)?;
    writer.string_value(device_symbol(row.device_ordinal.to_native())?)?;
    values_only_write_json_field_prefix(
        writer,
        &mut first,
        VALUES_ONLY_JSON_FIELD_INTERVAL_ORDINAL,
    )?;
    writer.string_value(interval_symbol(row.interval_ordinal.to_native())?)?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_STARTED_AT_MS)?;
    writer.i64_value(row.started_at_ms.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_RECORDED_AT_MS)?;
    writer.i64_value(row.recorded_at_ms.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_STARTED_AT_UTC)?;
    writer.utc_value(row.started_at_ms.to_native())?;
    values_only_write_json_field_prefix(
        writer,
        &mut first,
        VALUES_ONLY_JSON_FIELD_RECORDED_AT_UTC,
    )?;
    writer.utc_value(row.recorded_at_ms.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_VALUE_A)?;
    writer.f64_value("value_a", row.value_a.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_VALUE_B)?;
    writer.f64_value("value_b", row.value_b.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_VALUE_C)?;
    writer.f64_value("value_c", row.value_c.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_VALUE_D)?;
    writer.f64_value("value_d", row.value_d.to_native())?;
    values_only_write_json_field_prefix(writer, &mut first, VALUES_ONLY_JSON_FIELD_VALUE_E)?;
    writer.f64_value("value_e", row.value_e.to_native())?;
    writer.end_object()
}

fn values_only_write_json_field_prefix(
    writer: &mut JsonWriter,
    first: &mut bool,
    field: &'static [u8],
) -> Result<()> {
    if *first {
        *first = false;
    } else {
        writer.comma()?;
    }
    writer.raw_static(field)
}
