// This file is @generated by mbt_codegen.
// Do not edit by hand.
// schema_id=50002 schema_version=1 schema_hash=9409304714461393349

use crate::measurement_v1::*;
use mbt_core::error::Result;
use mbt_transponding::*;

pub(crate) struct MeasurementV1ColumnBatch {
    pub(crate) schema_version: ConstU16Column,
    pub(crate) device_ordinal: U16Column,
    pub(crate) interval_ordinal: U16Column,
    pub(crate) started_at_ms: I64Column,
    pub(crate) recorded_at_ms: I64Column,
    pub(crate) value_a: F64Column,
    pub(crate) value_b: F64Column,
    pub(crate) value_c: F64Column,
    pub(crate) value_d: F64Column,
    pub(crate) value_e: F64Column,
    pub(crate) value_f: F64Column,
    pub(crate) value_g: F64Column,
    pub(crate) value_h: F64Column,
    pub(crate) value_i: F64Column,
    pub(crate) value_j: F64Column,
    pub(crate) count_a: I64Column,
    pub(crate) count_b: I64Column,
    pub(crate) average_value: OptionalF64Column,
    pub(crate) sample_count: OptionalI64Column,
    pub(crate) source_ordinal: U16Column,
    pub(crate) process_ordinal: OptionalU16Column,
    pub(crate) sites_expected_mask: U64Column,
    pub(crate) sites_observed_mask: U64Column,
    pub(crate) ingested_at_ms: OptionalI64Column,
    pub(crate) target_ingested_at_ms: OptionalI64Column,
    pub(crate) built_at_ms: OptionalI64Column,
    pub(crate) committed_at_ms: OptionalI64Column,
    pub(crate) harmonized_at_ms: OptionalI64Column,
    pub(crate) recomputed_at_ms: OptionalI64Column,
    pub(crate) recomputed_reason_ordinal: OptionalU16Column,
    pub(crate) covered_interval_count: OptionalI64Column,
    pub(crate) expected_interval_count: OptionalI64Column,
    pub(crate) coverage_ratio: OptionalF64Column,
    pub(crate) inputs_source_counts_sensor: OptionalI64Column,
    pub(crate) inputs_source_counts_api: OptionalI64Column,
    pub(crate) inputs_source_counts_synthetic: OptionalI64Column,
    pub(crate) inputs_source_counts_corrected: OptionalI64Column,
    pub(crate) sensor_window_inputs_coverage_ratio: OptionalF64Column,
    pub(crate) sensor_window_expected: OptionalI64Column,
    pub(crate) sensor_window_synthetic_count: OptionalI64Column,
    pub(crate) sensor_window_synthetic_ratio: OptionalF64Column,
    pub(crate) sensor_window_observed_count: OptionalI64Column,
    pub(crate) sensor_window_observed_ratio: OptionalF64Column,
    pub(crate) age_ms: OptionalI64Column,
}

impl MeasurementV1ColumnBatch {
    pub(crate) fn byte_len(&self) -> usize {
        let mut len = 0_usize;
        len = len.saturating_add(self.schema_version.byte_len());
        len = len.saturating_add(self.device_ordinal.byte_len());
        len = len.saturating_add(self.interval_ordinal.byte_len());
        len = len.saturating_add(self.started_at_ms.byte_len());
        len = len.saturating_add(self.recorded_at_ms.byte_len());
        len = len.saturating_add(self.value_a.byte_len());
        len = len.saturating_add(self.value_b.byte_len());
        len = len.saturating_add(self.value_c.byte_len());
        len = len.saturating_add(self.value_d.byte_len());
        len = len.saturating_add(self.value_e.byte_len());
        len = len.saturating_add(self.value_f.byte_len());
        len = len.saturating_add(self.value_g.byte_len());
        len = len.saturating_add(self.value_h.byte_len());
        len = len.saturating_add(self.value_i.byte_len());
        len = len.saturating_add(self.value_j.byte_len());
        len = len.saturating_add(self.count_a.byte_len());
        len = len.saturating_add(self.count_b.byte_len());
        len = len.saturating_add(self.average_value.byte_len());
        len = len.saturating_add(self.sample_count.byte_len());
        len = len.saturating_add(self.source_ordinal.byte_len());
        len = len.saturating_add(self.process_ordinal.byte_len());
        len = len.saturating_add(self.sites_expected_mask.byte_len());
        len = len.saturating_add(self.sites_observed_mask.byte_len());
        len = len.saturating_add(self.ingested_at_ms.byte_len());
        len = len.saturating_add(self.target_ingested_at_ms.byte_len());
        len = len.saturating_add(self.built_at_ms.byte_len());
        len = len.saturating_add(self.committed_at_ms.byte_len());
        len = len.saturating_add(self.harmonized_at_ms.byte_len());
        len = len.saturating_add(self.recomputed_at_ms.byte_len());
        len = len.saturating_add(self.recomputed_reason_ordinal.byte_len());
        len = len.saturating_add(self.covered_interval_count.byte_len());
        len = len.saturating_add(self.expected_interval_count.byte_len());
        len = len.saturating_add(self.coverage_ratio.byte_len());
        len = len.saturating_add(self.inputs_source_counts_sensor.byte_len());
        len = len.saturating_add(self.inputs_source_counts_api.byte_len());
        len = len.saturating_add(self.inputs_source_counts_synthetic.byte_len());
        len = len.saturating_add(self.inputs_source_counts_corrected.byte_len());
        len = len.saturating_add(self.sensor_window_inputs_coverage_ratio.byte_len());
        len = len.saturating_add(self.sensor_window_expected.byte_len());
        len = len.saturating_add(self.sensor_window_synthetic_count.byte_len());
        len = len.saturating_add(self.sensor_window_synthetic_ratio.byte_len());
        len = len.saturating_add(self.sensor_window_observed_count.byte_len());
        len = len.saturating_add(self.sensor_window_observed_ratio.byte_len());
        len = len.saturating_add(self.age_ms.byte_len());
        len
    }
}

impl MeasurementV1 {
    pub(crate) fn transpond_archived(
        archived: &ArchivedMeasurementResponseV1Payload,
        max_columnar_bytes: usize,
    ) -> Result<MeasurementV1ColumnBatch> {
        let row_count = archived.rows.len();
        let schema_version = ConstU16Column::new(1, row_count);
        let mut device_ordinal = U16Column::new(row_count);
        let mut interval_ordinal = U16Column::new(row_count);
        let mut started_at_ms = I64Column::new(row_count);
        let mut recorded_at_ms = I64Column::new(row_count);
        let mut value_a = F64Column::new(row_count);
        let mut value_b = F64Column::new(row_count);
        let mut value_c = F64Column::new(row_count);
        let mut value_d = F64Column::new(row_count);
        let mut value_e = F64Column::new(row_count);
        let mut value_f = F64Column::new(row_count);
        let mut value_g = F64Column::new(row_count);
        let mut value_h = F64Column::new(row_count);
        let mut value_i = F64Column::new(row_count);
        let mut value_j = F64Column::new(row_count);
        let mut count_a = I64Column::new(row_count);
        let mut count_b = I64Column::new(row_count);
        let mut average_value = OptionalF64Column::new(row_count);
        let mut sample_count = OptionalI64Column::new(row_count);
        let mut source_ordinal = U16Column::new(row_count);
        let mut process_ordinal = OptionalU16Column::new(row_count);
        let mut sites_expected_mask = U64Column::new(row_count);
        let mut sites_observed_mask = U64Column::new(row_count);
        let mut ingested_at_ms = OptionalI64Column::new(row_count);
        let mut target_ingested_at_ms = OptionalI64Column::new(row_count);
        let mut built_at_ms = OptionalI64Column::new(row_count);
        let mut committed_at_ms = OptionalI64Column::new(row_count);
        let mut harmonized_at_ms = OptionalI64Column::new(row_count);
        let mut recomputed_at_ms = OptionalI64Column::new(row_count);
        let mut recomputed_reason_ordinal = OptionalU16Column::new(row_count);
        let mut covered_interval_count = OptionalI64Column::new(row_count);
        let mut expected_interval_count = OptionalI64Column::new(row_count);
        let mut coverage_ratio = OptionalF64Column::new(row_count);
        let mut inputs_source_counts_sensor = OptionalI64Column::new(row_count);
        let mut inputs_source_counts_api = OptionalI64Column::new(row_count);
        let mut inputs_source_counts_synthetic = OptionalI64Column::new(row_count);
        let mut inputs_source_counts_corrected = OptionalI64Column::new(row_count);
        let mut sensor_window_inputs_coverage_ratio = OptionalF64Column::new(row_count);
        let mut sensor_window_expected = OptionalI64Column::new(row_count);
        let mut sensor_window_synthetic_count = OptionalI64Column::new(row_count);
        let mut sensor_window_synthetic_ratio = OptionalF64Column::new(row_count);
        let mut sensor_window_observed_count = OptionalI64Column::new(row_count);
        let mut sensor_window_observed_ratio = OptionalF64Column::new(row_count);
        let mut age_ms = OptionalI64Column::new(row_count);
        for row in archived.rows.iter() {
            device_ordinal.push_required(row.device_ordinal.to_native());
            interval_ordinal.push_required(row.interval_ordinal.to_native());
            started_at_ms.push_required(row.started_at_ms.to_native());
            recorded_at_ms.push_required(row.recorded_at_ms.to_native());
            value_a.push_required(row.value_a.to_native());
            value_b.push_required(row.value_b.to_native());
            value_c.push_required(row.value_c.to_native());
            value_d.push_required(row.value_d.to_native());
            value_e.push_required(row.value_e.to_native());
            value_f.push_required(row.value_f.to_native());
            value_g.push_required(row.value_g.to_native());
            value_h.push_required(row.value_h.to_native());
            value_i.push_required(row.value_i.to_native());
            value_j.push_required(row.value_j.to_native());
            count_a.push_required(row.count_a.to_native());
            count_b.push_required(row.count_b.to_native());
            average_value.push_optional(
                row.presence_bits.to_native() & PRESENCE_AVERAGE_VALUE != 0,
                row.average_value.to_native(),
            )?;
            sample_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_SAMPLE_COUNT != 0,
                row.sample_count.to_native(),
            )?;
            source_ordinal.push_required(row.source_ordinal.to_native());
            process_ordinal.push_optional(
                row.presence_bits.to_native() & PRESENCE_PROCESS_ORDINAL != 0,
                row.process_ordinal.to_native(),
            )?;
            sites_expected_mask.push_required(row.sites_expected_mask.to_native());
            sites_observed_mask.push_required(row.sites_observed_mask.to_native());
            ingested_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_INGESTED_AT_MS != 0,
                row.ingested_at_ms.to_native(),
            )?;
            target_ingested_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_TARGET_INGESTED_AT_MS != 0,
                row.target_ingested_at_ms.to_native(),
            )?;
            built_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_BUILT_AT_MS != 0,
                row.built_at_ms.to_native(),
            )?;
            committed_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_COMMITTED_AT_MS != 0,
                row.committed_at_ms.to_native(),
            )?;
            harmonized_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_HARMONIZED_AT_MS != 0,
                row.harmonized_at_ms.to_native(),
            )?;
            recomputed_at_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_RECOMPUTED_AT_MS != 0,
                row.recomputed_at_ms.to_native(),
            )?;
            recomputed_reason_ordinal.push_optional(
                row.presence_bits.to_native() & PRESENCE_RECOMPUTED_REASON_ORDINAL != 0,
                row.recomputed_reason_ordinal.to_native(),
            )?;
            covered_interval_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_COVERED_INTERVAL_COUNT != 0,
                row.covered_interval_count.to_native(),
            )?;
            expected_interval_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_EXPECTED_INTERVAL_COUNT != 0,
                row.expected_interval_count.to_native(),
            )?;
            coverage_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_COVERAGE_RATIO != 0,
                row.coverage_ratio.to_native(),
            )?;
            inputs_source_counts_sensor.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SENSOR != 0,
                row.inputs_source_counts_sensor.to_native(),
            )?;
            inputs_source_counts_api.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_API != 0,
                row.inputs_source_counts_api.to_native(),
            )?;
            inputs_source_counts_synthetic.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_SYNTHETIC != 0,
                row.inputs_source_counts_synthetic.to_native(),
            )?;
            inputs_source_counts_corrected.push_optional(
                row.presence_bits.to_native() & PRESENCE_INPUTS_SOURCE_COUNTS_CORRECTED != 0,
                row.inputs_source_counts_corrected.to_native(),
            )?;
            sensor_window_inputs_coverage_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_INPUTS_COVERAGE_RATIO != 0,
                row.sensor_window_inputs_coverage_ratio.to_native(),
            )?;
            sensor_window_expected.push_optional(
                row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_EXPECTED != 0,
                row.sensor_window_expected.to_native(),
            )?;
            sensor_window_synthetic_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_SYNTHETIC_COUNT != 0,
                row.sensor_window_synthetic_count.to_native(),
            )?;
            sensor_window_synthetic_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_SYNTHETIC_RATIO != 0,
                row.sensor_window_synthetic_ratio.to_native(),
            )?;
            sensor_window_observed_count.push_optional(
                row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_OBSERVED_COUNT != 0,
                row.sensor_window_observed_count.to_native(),
            )?;
            sensor_window_observed_ratio.push_optional(
                row.presence_bits.to_native() & PRESENCE_SENSOR_WINDOW_OBSERVED_RATIO != 0,
                row.sensor_window_observed_ratio.to_native(),
            )?;
            age_ms.push_optional(
                row.presence_bits.to_native() & PRESENCE_AGE_MS != 0,
                row.age_ms.to_native(),
            )?;
        }
        let batch = MeasurementV1ColumnBatch {
            schema_version,
            device_ordinal,
            interval_ordinal,
            started_at_ms,
            recorded_at_ms,
            value_a,
            value_b,
            value_c,
            value_d,
            value_e,
            value_f,
            value_g,
            value_h,
            value_i,
            value_j,
            count_a,
            count_b,
            average_value,
            sample_count,
            source_ordinal,
            process_ordinal,
            sites_expected_mask,
            sites_observed_mask,
            ingested_at_ms,
            target_ingested_at_ms,
            built_at_ms,
            committed_at_ms,
            harmonized_at_ms,
            recomputed_at_ms,
            recomputed_reason_ordinal,
            covered_interval_count,
            expected_interval_count,
            coverage_ratio,
            inputs_source_counts_sensor,
            inputs_source_counts_api,
            inputs_source_counts_synthetic,
            inputs_source_counts_corrected,
            sensor_window_inputs_coverage_ratio,
            sensor_window_expected,
            sensor_window_synthetic_count,
            sensor_window_synthetic_ratio,
            sensor_window_observed_count,
            sensor_window_observed_ratio,
            age_ms,
        };
        ensure_columnar_size(batch.byte_len(), max_columnar_bytes)?;
        Ok(batch)
    }
}

const WITHOUT_DETAILS_PRESENCE_AVERAGE_VALUE: u64 = 1 << 0;
const WITHOUT_DETAILS_PRESENCE_SAMPLE_COUNT: u64 = 1 << 1;
const WITHOUT_DETAILS_PRESENCE_AGE_MS: u64 = 1 << 2;

pub(crate) struct MeasurementV1WithoutDetailsColumnBatch {
    pub(crate) schema_version: ConstU16Column,
    pub(crate) device_ordinal: U16Column,
    pub(crate) interval_ordinal: U16Column,
    pub(crate) started_at_ms: I64Column,
    pub(crate) recorded_at_ms: I64Column,
    pub(crate) value_a: F64Column,
    pub(crate) value_b: F64Column,
    pub(crate) value_c: F64Column,
    pub(crate) value_d: F64Column,
    pub(crate) value_e: F64Column,
    pub(crate) value_f: F64Column,
    pub(crate) value_g: F64Column,
    pub(crate) value_h: F64Column,
    pub(crate) value_i: F64Column,
    pub(crate) value_j: F64Column,
    pub(crate) count_a: I64Column,
    pub(crate) count_b: I64Column,
    pub(crate) average_value: OptionalF64Column,
    pub(crate) sample_count: OptionalI64Column,
    pub(crate) age_ms: OptionalI64Column,
}

impl MeasurementV1WithoutDetailsColumnBatch {
    pub(crate) fn byte_len(&self) -> usize {
        let mut len = 0_usize;
        len = len.saturating_add(self.schema_version.byte_len());
        len = len.saturating_add(self.device_ordinal.byte_len());
        len = len.saturating_add(self.interval_ordinal.byte_len());
        len = len.saturating_add(self.started_at_ms.byte_len());
        len = len.saturating_add(self.recorded_at_ms.byte_len());
        len = len.saturating_add(self.value_a.byte_len());
        len = len.saturating_add(self.value_b.byte_len());
        len = len.saturating_add(self.value_c.byte_len());
        len = len.saturating_add(self.value_d.byte_len());
        len = len.saturating_add(self.value_e.byte_len());
        len = len.saturating_add(self.value_f.byte_len());
        len = len.saturating_add(self.value_g.byte_len());
        len = len.saturating_add(self.value_h.byte_len());
        len = len.saturating_add(self.value_i.byte_len());
        len = len.saturating_add(self.value_j.byte_len());
        len = len.saturating_add(self.count_a.byte_len());
        len = len.saturating_add(self.count_b.byte_len());
        len = len.saturating_add(self.average_value.byte_len());
        len = len.saturating_add(self.sample_count.byte_len());
        len = len.saturating_add(self.age_ms.byte_len());
        len
    }
}

impl MeasurementV1WithoutDetails {
    pub(crate) fn transpond_archived(
        archived: &ArchivedMeasurementResponseV1PayloadWithoutDetails,
        max_columnar_bytes: usize,
    ) -> Result<MeasurementV1WithoutDetailsColumnBatch> {
        let row_count = archived.rows.len();
        let schema_version = ConstU16Column::new(1, row_count);
        let mut device_ordinal = U16Column::new(row_count);
        let mut interval_ordinal = U16Column::new(row_count);
        let mut started_at_ms = I64Column::new(row_count);
        let mut recorded_at_ms = I64Column::new(row_count);
        let mut value_a = F64Column::new(row_count);
        let mut value_b = F64Column::new(row_count);
        let mut value_c = F64Column::new(row_count);
        let mut value_d = F64Column::new(row_count);
        let mut value_e = F64Column::new(row_count);
        let mut value_f = F64Column::new(row_count);
        let mut value_g = F64Column::new(row_count);
        let mut value_h = F64Column::new(row_count);
        let mut value_i = F64Column::new(row_count);
        let mut value_j = F64Column::new(row_count);
        let mut count_a = I64Column::new(row_count);
        let mut count_b = I64Column::new(row_count);
        let mut average_value = OptionalF64Column::new(row_count);
        let mut sample_count = OptionalI64Column::new(row_count);
        let mut age_ms = OptionalI64Column::new(row_count);
        for row in archived.rows.iter() {
            device_ordinal.push_required(row.device_ordinal.to_native());
            interval_ordinal.push_required(row.interval_ordinal.to_native());
            started_at_ms.push_required(row.started_at_ms.to_native());
            recorded_at_ms.push_required(row.recorded_at_ms.to_native());
            value_a.push_required(row.value_a.to_native());
            value_b.push_required(row.value_b.to_native());
            value_c.push_required(row.value_c.to_native());
            value_d.push_required(row.value_d.to_native());
            value_e.push_required(row.value_e.to_native());
            value_f.push_required(row.value_f.to_native());
            value_g.push_required(row.value_g.to_native());
            value_h.push_required(row.value_h.to_native());
            value_i.push_required(row.value_i.to_native());
            value_j.push_required(row.value_j.to_native());
            count_a.push_required(row.count_a.to_native());
            count_b.push_required(row.count_b.to_native());
            average_value.push_optional(
                row.presence_bits.to_native() & WITHOUT_DETAILS_PRESENCE_AVERAGE_VALUE != 0,
                row.average_value.to_native(),
            )?;
            sample_count.push_optional(
                row.presence_bits.to_native() & WITHOUT_DETAILS_PRESENCE_SAMPLE_COUNT != 0,
                row.sample_count.to_native(),
            )?;
            age_ms.push_optional(
                row.presence_bits.to_native() & WITHOUT_DETAILS_PRESENCE_AGE_MS != 0,
                row.age_ms.to_native(),
            )?;
        }
        let batch = MeasurementV1WithoutDetailsColumnBatch {
            schema_version,
            device_ordinal,
            interval_ordinal,
            started_at_ms,
            recorded_at_ms,
            value_a,
            value_b,
            value_c,
            value_d,
            value_e,
            value_f,
            value_g,
            value_h,
            value_i,
            value_j,
            count_a,
            count_b,
            average_value,
            sample_count,
            age_ms,
        };
        ensure_columnar_size(batch.byte_len(), max_columnar_bytes)?;
        Ok(batch)
    }
}

pub(crate) struct MeasurementV1ValuesOnlyColumnBatch {
    pub(crate) schema_version: ConstU16Column,
    pub(crate) device_ordinal: U16Column,
    pub(crate) interval_ordinal: U16Column,
    pub(crate) started_at_ms: I64Column,
    pub(crate) recorded_at_ms: I64Column,
    pub(crate) value_a: F64Column,
    pub(crate) value_b: F64Column,
    pub(crate) value_c: F64Column,
    pub(crate) value_d: F64Column,
    pub(crate) value_e: F64Column,
}

impl MeasurementV1ValuesOnlyColumnBatch {
    pub(crate) fn byte_len(&self) -> usize {
        let mut len = 0_usize;
        len = len.saturating_add(self.schema_version.byte_len());
        len = len.saturating_add(self.device_ordinal.byte_len());
        len = len.saturating_add(self.interval_ordinal.byte_len());
        len = len.saturating_add(self.started_at_ms.byte_len());
        len = len.saturating_add(self.recorded_at_ms.byte_len());
        len = len.saturating_add(self.value_a.byte_len());
        len = len.saturating_add(self.value_b.byte_len());
        len = len.saturating_add(self.value_c.byte_len());
        len = len.saturating_add(self.value_d.byte_len());
        len = len.saturating_add(self.value_e.byte_len());
        len
    }
}

impl MeasurementV1ValuesOnly {
    pub(crate) fn transpond_archived(
        archived: &ArchivedMeasurementResponseV1PayloadValuesOnly,
        max_columnar_bytes: usize,
    ) -> Result<MeasurementV1ValuesOnlyColumnBatch> {
        let row_count = archived.rows.len();
        let schema_version = ConstU16Column::new(1, row_count);
        let mut device_ordinal = U16Column::new(row_count);
        let mut interval_ordinal = U16Column::new(row_count);
        let mut started_at_ms = I64Column::new(row_count);
        let mut recorded_at_ms = I64Column::new(row_count);
        let mut value_a = F64Column::new(row_count);
        let mut value_b = F64Column::new(row_count);
        let mut value_c = F64Column::new(row_count);
        let mut value_d = F64Column::new(row_count);
        let mut value_e = F64Column::new(row_count);
        for row in archived.rows.iter() {
            device_ordinal.push_required(row.device_ordinal.to_native());
            interval_ordinal.push_required(row.interval_ordinal.to_native());
            started_at_ms.push_required(row.started_at_ms.to_native());
            recorded_at_ms.push_required(row.recorded_at_ms.to_native());
            value_a.push_required(row.value_a.to_native());
            value_b.push_required(row.value_b.to_native());
            value_c.push_required(row.value_c.to_native());
            value_d.push_required(row.value_d.to_native());
            value_e.push_required(row.value_e.to_native());
        }
        let batch = MeasurementV1ValuesOnlyColumnBatch {
            schema_version,
            device_ordinal,
            interval_ordinal,
            started_at_ms,
            recorded_at_ms,
            value_a,
            value_b,
            value_c,
            value_d,
            value_e,
        };
        ensure_columnar_size(batch.byte_len(), max_columnar_bytes)?;
        Ok(batch)
    }
}
